CMakeLists.txt
pkg_check_modules() requires `moduleSpec` name,
otherwise it prints out the error message:
```
-- Checking for modules ''
Please specify at least one package name on the command line.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/10)
=> common: fix checking for module libpmem2

.github/workflows/gha.yml, .travis.yml, utils/docker/images/push-image.sh
The 'push-image.sh' script is called in the following way now:
$ push-image.sh $OS-$OS_VER
but 'OS' and 'OS_VER' variables cannot be set in command line
in GHA yaml script, so value of tag '$' has to be set manually
inside the script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/22)
=> common: adjust push-image.sh script to GHA CI

src/CMakeLists.txt, src/include/librpma.h, src/librpma.c, src/librpma.map, src/rpma_err.c, src/rpma_err.h
+ rename rpma_errormsg() to rpma_err_get_msg()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/34)
=> rpma: introduce rpma_err_get_provider_error()

utils/docker/images/Dockerfile.fedora-31
It fixes following bug:
```
Checking copyright headers of modified files only...
../utils/check_license/check-headers.sh: line 103: file: command not found
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/56)
=> common: add missing 'file' package to Fedora Docker image

.codecov.yml
It increases code coverage by 73.11% ! ;-)
(from 17.12% to 90.24%)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/67)
=> common: ignore src/common/ files in checking code coverage

tests/CMakeLists.txt
It fixes the following error occurring on openSUSE Leap and CentOS 8:
```
CMake Error at tests/info-test/CMakeLists.txt:12 (target_link_libraries):
Target "test-rpma-utils" of type OBJECT_LIBRARY may not be linked into
another target.  One may link only to STATIC or SHARED libraries, or to
executables with the ENABLE_EXPORTS property set.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/77)
=> test: make the 'test-rpma-utils' library static

examples/connection/connection-client.c, examples/connection/connection-server.c, src/conn_req.c, src/conn_req.h, src/include/librpma.h, tests/CMakeLists.txt, tests/conn_req-test/CMakeLists.txt, tests/conn_req-test/conn_req-test.c
Additionally:
- removal of struct rpma_conn_cfg (for now)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/82)
=> rpma: rpma_conn_req_from_cm_event()/_delete() implementation & unit tests

src/conn.c, src/conn.h, tests/conn-test/conn-test.c
A CM ID can not be migrated to a separate event channel before it is
accepted and its connection request event is ACKed. It is repacked
into a rpma_conn at this point so it is convenient for the
rpma_conn_new() function to create an event channel for a CM ID and
migrate it while it is repacking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/89)
=> common: add an event channel creation and migration to rpma_conn_new

tests/conn_req-test/conn_req-test.c, tests/ep-test/ep-test.c
Some compilers prefer to initialize variables using double brackets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/98)
=> test: variable init (fix)

src/conn_req.c, src/include/librpma.h, tests/conn_req-test/conn_req-test.c
A CM ID encapsulated in the connection request on the active side of the connection is initially not attached to any event channel. In a result of this, it works in blocking mode till first call to ```rdma_migrate_id(3)```. Because this whole connection process is done before the return from ```rdma_connect(3)``` so after migrating the CM ID to an event channel you can not expect ```RDMA_CM_EVENT_ESTABLISHED``` to appear on the event channel of the connection.
An easy fix for this is to reverse the order: migrate the CM ID to an event channel, so the CM ID works in the non-blocking mode, and after that calling ```rdma_connect()``` so all events regarding the connection will be delivered to the event channel.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> common: _conn_req_connect (active side) fix

examples/connection/connection-client.c, examples/connection/connection-server.c, src/include/librpma.h, src/rpma.c, tests/utils-test/utils-test.c
```rdma_getaddrinfo(3)``` is more resilient than I have initially assumed. It allows getting address info even if the used IP address is not present on the expected side of the connection. The issue appears finally when we are trying to resolve/bind using obtained address info. So ```rpma_utils_get_ibv_context()``` needed a little bit rework to align to how ```rdma_getaddrinfo()``` behaves.
Taking into account all of the above I have come up with two implementations (active and passive) where the other is used when the first one fails. But with multiple fail paths. Testing this was a nightmare so I have decided to introduce additional argument to the API function which, this new argument, allows picking an applicable implementation. This new argument also allowed greatly simplified the …
=> common: _utils_get_ibv_context fix

examples/connection/connection-client.c, examples/connection/connection-server.c, src/include/librpma.h, src/librpma.map, src/rpma.c, src/rpma_err.c
1. introduce two new functions allowing converting error codes and connection events to strings
2. rework connection example to make it more useful for diagnosing connection issues
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/99)
=> common: examples rework using a two newly introduced functions

tests/private_data-test/private_data-test.c
Fix names of tests in private_data-test.c:
- replace the 'test_new__' prefix with 'test_store__'
- replace the '__1st_malloc_ENOMEM' suffix with '__malloc_ENOMEM'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/108)
=> test: fix names of tests in private_data-test.c

.github/workflows/gha.yml, .travis.yml, utils/docker/images/push-image.sh
Push Docker images from GHA instead of Travis CI,
because GHA builds finish faster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/74)
=> common: push Docker images from GHA instead of Travis CI

src/conn.c, src/conn_req.c, src/info.c, src/peer.c
We decided that if malloc() fails
than RPMA_E_NOMEM is always returned,
no matter what a value of errno is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/128)
=> rpma: remove all ASSERTeq(errno, ENOMEM) for malloc() calls

examples/common/common.c, src/common/util.h, src/conn_req.c, src/include/librpma.h, src/info.c, tests/conn-test/conn-test-common.c, tests/example-01-client/example-01-client.c, tests/mr-test/mr-test-common.c, tests/mr-test/mr-test-descriptor.c, tests/peer-test/peer-test.c, tests/private_data-test/private_data-test.c, utils/cstyle
A pronoun should always go together with its noun.
It is inhumane and cruel to separate them,
so let's find and rescue all orphaned pronouns!
Make cstyle detect orphaned pronouns at the end of the line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/150)
=> common: find and rescue orphaned pronouns at the end of the line

src/conn_req.c
Unnecesary goto in rpma_conn_req_from_cm_event removed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/151)
=> common: remove goto from rpma_conn_req_from_cm_event

examples/01-connection/client.c, examples/01-connection/server.c, examples/02-read-to-volatile/client.c, examples/02-read-to-volatile/server.c, examples/common/common.c, examples/common/common.h
Rename `print_error()` to `print_error_ex()`,
because cmocka (a unit test framework we use)
also has the `print_error()` function
and they can be confused by a linker.
It happened for me that cmocka used
the version of librpma examples
(instead of its own one)
and the printed errors were incorrect
and many important information were missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/163)
=> examples: rename print_error() to print_error_ex()

tests/integration/example-01-connection/CMakeLists.txt
LINK_FLAGS is set twice now, but the second one overwrites
the first one. LINK_FLAGS can be set only once.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/169)
=> examples: fix setting LINK_FLAGS in the example-01-connection test

src/log.c
Log performance and usability optimization:
- print only basename instead of whole path
- avoid unneeded memory copying
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/176)
=> Log performance and usability optimization

src/ep.c, src/include/librpma.h, tests/unit/ep-test/ep-test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/190)
=> common: rpma_ep_next_conn_req can return RPMA_E_NO_NEXT

src/conn.c, tests/unit/conn-test/conn-test-next-event.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/192)
=> common: rpma_conn_next_event can return RPMA_E_NO_NEXT

src/conn.c, src/flush.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/211)
=> rpma: fix two error handling paths in conn.c and flush.c

src/peer.c, tests/integration/common/mocks.c, tests/integration/common/mocks.h, tests/integration/example-01-connection/example-01-connection.c, tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, tests/unit/common/mocks-rpma-utils.c, tests/unit/common/test-common.h, tests/unit/peer-test/CMakeLists.txt, tests/unit/peer-test/peer-test.c
Includes:
- ODP detection - (rpma_utils_ibv_context_is_odp_capable)
- adding IBV_ACCESS_ON_DEMAND to the flags if regular memory
registration will fail with EOPNOTSUPP and ODP is supported
- tweaking existing tests to use upgraded implementation
Does not include:
- new tests for handling the fails of the introduced API calls
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/233)
=> common: fall back to On-Demand Paging registration if supported

examples/CMakeLists.txt, examples/log/log-example.c, examples/log/log-worker.c, src/CMakeLists.txt, src/include/librpma_log.h, src/librpma.c, src/librpma.map, src/log.c, src/log_default.c, src/log_default.h, src/log_internal.h, tests/integration/example-01-connection/CMakeLists.txt, tests/integration/example-02-read-to-volatile/CMakeLists.txt
The split recognizes three separate parts of the mechanism:
- the core logging (src/log.c) mechanism which has to call as soon as
possible the configured logging function taking into account the primary
threshold. It also holds the primary and the secondary threshold values
which are available for writing and reading via the default and the
user-provided logging functions.
- the default logging implementation (src/log_default.c) which
implements logging to syslog and/or stderr. syslog logging is controlled
via the primary logging threshold whereas stderr logging is controlled
via the secondary logging threshold. The syslog connection is opened via
the library constructor and closed on deconstructor.
- the initialization of the logging module is triggered via the main
library constructor …
=> common: split the log module

examples/02-read-to-volatile/client.c, examples/03-read-to-persistent/server.c, examples/04-write-to-persistent/client.c, examples/05-flush-to-persistent/client.c, tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c
ibv_poll_cq() may return zero when no CQEs are ready.
rpma_conn_prepare_completions() allows waiting for CQE to appear.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/231)
=> common: prepare examples for incoming completions

tests/unit/log/macros.c
The range is not needed as we could predict the expected log line number.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/263)
=> common: fixed line in macro tests

examples/log/log-example.c, src/include/librpma_log.h, src/log.c, src/log_default.c, src/log_internal.h, tests/unit/log/CMakeLists.txt, tests/unit/log/init-fini.c, tests/unit/log/macros.c
- reorganize librpma_log.h (thresholds first since they will probably
used more often)
- rename RPMA_LOG_DEFAULT_FUNCTION to RPMA_LOG_USE_DEFAULT_FUNCTION
- misc comments and changes to documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/260)
=> common: log module refactor

src/rpma.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/270)
=> rpma: fix 'missing braces around initializer' warning

utils/check_license/check-headers.sh
The condition `[[ $(echo $file) =~ ".c" ]]` matches also all `*.c*` files
(for example all `*.cmake` or `Dockerfile.centos`) what is incorrect,
so let's fix checking all file extensions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/281)
=> common: fix checking file extensions in check-headers.h

utils/docker/images/Dockerfile.fedora-31
Add 'rpm-build' package to Fedora docker image.
It will be required to make rpm packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/291)
=> common: add 'rpm-build' package to Fedora docker image

examples/03-read-to-persistent/client.c, examples/05-flush-to-persistent/client.c
Fix the rest of:
"error: '__builtin_strncpy' specified bound 1024 equals\
destination size [-Werror=stringop-truncation]"
errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/322)
=> examples: fix more '__builtin_strncpy specified bound 1024' errors

src/include/librpma.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/310)
=> rpma: op_context is not mandatory for rpma_recv

src/conn_req.c, src/conn_req.h, src/include/librpma.h, src/info.c, src/info.h, src/rpma.c, tests/unit/common/mocks-rdma_cm.c, tests/unit/common/mocks-rpma-info.c, tests/unit/common/test-common.h, tests/unit/conn_req/conn_req-common.c, tests/unit/conn_req/conn_req-new.c, tests/unit/info/info-resolve_addr.c, tests/unit/utils/utils-common.c
This one of many steps leading to allow configuring various aspects of the library behaviour.
TODO:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/313)
=> common: remove hardcoded timeout from info.c module

src/conn.c, src/conn_req.c, src/include/librpma.h, src/mr.c, src/mr.h, tests/unit/common/mocks-rpma-mr.c, tests/unit/conn/conn-recv.c
Remove the 'flags' argument from rpma_recv(),
because the 'ibv_recv_wr' structure has no receive flags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/327)
=> rpma: remove flags from rpma_recv()

examples/run-all-on-SoftRoCE.sh
While running 'make test_softroce' the '07-atomic-write' example
fails always with the following error now:
`*ERROR*: rdma_bind_addr() failed: Address already in use`
Make sure the server's process is finished,
before starting a new one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/333)
=> examples: make sure the server's process is finished

examples/07-atomic-write/server.c
When LOG_DATA_SIZE==100000 `ibv_reg_mr()` is called with length==200016
and it fails on SoftRoCE. Decrease LOG_DATA_SIZE to 1024 to fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/336)
=> examples: fix 07-atomic-write example on SoftRoCE

examples/07-atomic-write/server.c
Fix the following compilation error:
```
[100%] Building C object examples/CMakeFiles/example-07-atomic-write-server.dir/07-atomic-write/server.c.o
/rpma/examples/07-atomic-write/server.c:26:0: error: macro "LOG_HDR_SIGNATURE" is not used [-Werror=unused-macros]
#define LOG_HDR_SIGNATURE "LOG"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/343)
=> examples: fix error: macro "LOG_HDR_SIGNATURE" is not used

INSTALL.md
New column "Default" to present what CMake parameters are set to active values
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/344)
=> common: default CMake settings added to the documentation

doc/CMakeLists.txt
Replace 'list(TRANSFORM' with 'foreach' in doc/CMakeLists.txt
because 'list(TRANSFORM' requires CMake>=v3.12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/346)
=> doc: replace 'list(TRANSFORM' with 'foreach' in doc/CMakeLists.txt

src/log_internal.h
```
In file included from /rpma/src/conn.c:14:0:
/rpma/src/conn.c: In function 'rpma_conn_new':
/rpma/src/log_internal.h:57:49: error: implicit declaration of function 'strerror' [-Werror=implicit-function-declaration]
RPMA_LOG_ERROR(f " failed: %s", ##__VA_ARGS__, strerror(e));
^
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/351)
=> rpma: include string.h for strerror()

cmake/librpma.pc.in
Fix librpma pkg-config file:
1) do not require pkg-config files of libibverbs and librdmacm,
because older versions of them do not provide pkg-config files
2) add the link flags specific to this package and other required
libraries that don't support pkg-config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/361)
=> common: fix librpma pkg-config file

utils/check_license/check-headers.sh
This fix is required to support CentOS-7 and CentOS-6.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/364)
=> common: fix error: unknown option: '-C' of the 'git' command

utils/check_license/check-headers.sh
$0 has to be replaced with $SELF (set at the beginning to $0),
because there were several 'shift' commands
and $0 can be something else than it was initially.
It fixes the following error existing on master:
```
../utils/check_license/check-headers.sh: line 190: ../utils/check_license/check-ms-license.pl: No such file or directory
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/374)
=> common: fix running check-ms-license.pl in check-headers.sh

examples/08-messages-ping-pong/client.c
Librpma already provide WARNING when the result is != IBV_WC_SUCCESS
Here a high level message is only needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/360)
=> common: redundant error message removed

examples/06-multiple-connections/client.c
Forced by the static analyzer which has pointed out
that strncpy *theoretically* may not null-terminate the output string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/371)
=> examples: fix non null terminated string

examples/05-flush-to-persistent/server.c
'ON_STR' should be defined only
if 'USE_LIBPMEM' had been already defined before.
```
/rpma/examples/05-flush-to-persistent/server.c:24: error: macro "ON_STR" is not used [-Werror=unused-macros]
#define ON_STR "on"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/394)
=> examples: fix defining ON_STR

utils/docker/images/install-txt2man.sh
Install src2man and txt2man in /usr instead of /usr/local.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/383)
=> common: fix installing txt2man in /usr

tests/match, utils/check_whitespace
This change is required to support building librpma on CentOS-6.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/365)
=> common: require Perl v5.10 instead of v5.16

utils/docker/run-build.sh
The 'all' target depends on the 'doc' target,
so the 'doc' target is already run during the 'all' target.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/387)
=> common: remove redundant 'make doc' test

doc/manuals_3.txt, examples/05-flush-to-persistent/client.c, examples/05-flush-to-persistent/server.c, examples/common/common-conn.h, src/include/librpma.h, src/librpma.map, src/peer_cfg.c, tests/unit/peer_cfg/peer_cfg-common.h, tests/unit/peer_cfg/peer_cfg-descriptor.c
Missing:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/407)
=> rpma: remove rpma_peer_cfg_descriptor

CMakeLists.txt
As there is no valgrind tests yet so, to avoid cmake warning when valgrind is
not found, this option should be off by default
```
CMake Warning at tests/cmake/ctest_helpers.cmake:55 (message):
Valgrind not found.  Valgrind tests will not be performed.
Call Stack (most recent call first):
tests/CMakeLists.txt:28 (find_packages)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/405)
=> common: Do not use valgiring by default

utils/check_license/check-headers.sh
This is a fix of b4ce4ab.
The b4ce4ab commit has not fixed the issue:
```
../utils/check_license/check-headers.sh: line 190: ../utils/check_license/check-ms-license.pl: No such file or directory
```
because the c17026a commit was also merged just before it.
c17026a changes the current directory and makes b4ce4ab does not work.
This patch fixes it ultimately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/402)
=> common: fix running check-ms-license.pl in check-headers.sh ultimately

cmake/functions.cmake
Older compilers may not support the '-Werror=discarded-qualifiers' flag.
In this case a signature of rdma_getaddrinfo() has to be verified
by grepping the 'rdma_cma.h' header file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/395)
=> common: fix checking signature of rdma_getaddrinfo()

src/conn.c, src/rpma.c, tests/unit/utils/utils-conn_event_2str.c
There is no message when connection could not be properly established on a client side  (server close it just after accepting)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/415)
=> rpma: avoid silent shutdown in case of unknown comunication event

src/include/librpma.h
It is workaround for the following src2man issue:
```
$ make doc
src2man: errors found in the "/home/ldorau/work/rpma/\
src/include/librpma.h" file:
gawk: cmd. line:145: (FILENAME=- FNR=22) fatal: invalid regexp:\
Unmatched ( or \(: /\<rpma_log_set_threshold(rpma_threshold\>/
Built target doc
```
and rpma_log_set_threshold.3.md is corrupted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/437)
=> rpma: fix generating rpma_log_set_threshold.3.md by 'make doc'

examples/CMakeLists.txt
We cannot use list(FILTER) in CMake,
because it is available starting from CMake v3.6,
but we require CMake v3.3, so we have to workaround it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/424)
=> examples: workaround list(FILTER) from CMake >= v3.6

cmake/FindLIBPROTOBUFC.cmake
Add missing FindLIBPROTOBUFC.cmake.
If there is no 'libprotobuf-c' pkgconfig file found,
the following CMake error is printed:
```
-- Checking for module 'libprotobuf-c'
--   No package 'libprotobuf-c' found
CMake Error at CMakeLists.txt:26 (find_package):
By not providing "FindLIBPROTOBUFC.cmake" in CMAKE_MODULE_PATH this project
has asked CMake to find a package configuration file provided by
"LIBPROTOBUFC", but CMake did not find one.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/413)
=> common: add missing FindLIBPROTOBUFC.cmake

utils/docker/run-build.sh
Skip testing standalone compilation of the 09 example on CIs,
if libprotobuf-c is missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/421)
=> common: skip example 09 if libprotobuf-c is missing

cmake/functions.cmake, examples/01-connection/CMakeLists.txt, examples/02-read-to-volatile/CMakeLists.txt, examples/03-read-to-persistent/CMakeLists.txt, examples/04-write-to-persistent/CMakeLists.txt, examples/05-flush-to-persistent/CMakeLists.txt, examples/06-multiple-connections/CMakeLists.txt, examples/07-atomic-write/CMakeLists.txt, examples/08-messages-ping-pong/CMakeLists.txt, examples/09-flush-to-persistent-GPSPM/CMakeLists.txt, examples/CMakeLists.txt, examples/template-example/CMakeLists.txt
clock_gettime() requires linking with -lrt
for glibc versions before 2.17
See: https://man7.org/linux/man-pages/man2/clock_gettime.2.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/440)
=> examples: link with -lrt for clock_gettime() for glibc < v2.17

src/log_default.c, tests/unit/common/mocks-getpid.c, tests/unit/common/mocks-getpid.h, tests/unit/log_default/CMakeLists.txt, tests/unit/log_default/function.c, tests/unit/log_default/init-fini.c
- add procid to stderr message (instead of user-defined prefix)
- adjust stderr time format to follow syslog one
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/447)
=> Unify stderr and syslog messages

examples/06-multiple-connections/server.c, src/conn.c, src/ep.c, src/include/librpma.h, src/rpma_err.c, tests/unit/conn/conn-next-event.c, tests/unit/ep/ep-next_conn_req.c, tests/unit/error/error.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/465)
=> common: add missing cases to rpma_err_2str() + replace RPMA_E_NO_NEXT with RPMA_E_NO_EVENT

utils/docker/images/Dockerfile.fedora-31, utils/docker/images/Dockerfile.ubuntu-19.10
Add pandoc package to Ubuntu 19.10 Docker image,
to enable generation of Markdown documentation:
```
CMake Warning at doc/CMakeLists.txt:13 (message):
pandoc not found - Markdown documentation will not be generated
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/473)
=> common: add pandoc package to Ubuntu 19.10 Docker image

examples/common/common-conn.c, examples/common/common-conn.h, src/conn.c, src/conn.h, src/conn_req.c, src/conn_req.h, src/ep.c, src/flush.c, src/flush.h, src/include/librpma.h, src/mr.c, src/mr.h, src/peer.c, src/peer.h, src/peer_cfg.c, tests/unit/common/mocks-rpma-conn.c, tests/unit/common/mocks-rpma-flush.c, tests/unit/common/mocks-rpma-mr.c, tests/unit/common/mocks-rpma-peer.c, tests/unit/ep/ep-common.c, tests/unit/peer/peer-create_qp.c, tests/unit/peer/peer-mr_reg.c
const removed from all public API calls if pointers passed to functions are related to resources that might be modified 
e.g.
mr as destination RMA operation
peer where ibv_pd is modified
connection - almost in all cases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/482)
=> rpma: remove const where related RDMA resources might be modified

src/include/librpma.h
`rpma_log_set_threshold()/rpma_log_get_threshold()`
is incorrectly formatted by pandoc to:
`**rpma\_log\_set\_threshold**()/rpma\_log\_get\_threshold()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/493)
=> rpma: fix DEBUGGING AND ERROR HANDLING description

CMakeLists.txt, examples/CMakeLists.txt, tests/CMakeLists.txt
- add `make examples` to compile all examples at once
- move `make tests` into tests dir, not to have this target if e.g. `BUILD_TESTS=OFF`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/539)
=> common: enhance custom make targets

examples/09-flush-to-persistent-GPSPM/client.c
Fix the compilation error:
```
examples/09-flush-to-persistent-GPSPM/client.c:99:6: error: variable 'is_pmem' set but not used [-Werror=unused-but-set-variable]
```
See: https://github.com/ldorau/rpma/actions/runs/291154483
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/544)
=> examples: fix error: variable 'is_pmem' set but not used

examples/run-all-on-SoftRoCE.sh
The `STATE_OK` variable was used in the line no. 23,
but it has never been set in this script,
so the script has been working correctly so far
only because there was always exactly one good (active and up)
network interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/541)
=> examples: fix setting unset variable STATE_OK

CMakeLists.txt
It blocked also under-source builds (a subdir inside tree, as suggested
by the documentation), and completely external directories.  On the other
hand, after removing this block, in-source builds work perfectly.
Closes #301 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/513)
=> common: remove broken block for in-source builds

src/log_internal.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/551)
=> rpma: abs(errno) because ibv_* likes to return -errno

examples/config_softroce.sh
Add support for running examples on SoftRoCE
on a USB Ethernet network interfaces,
which may not have 'state UP',
but only 'UP' and 'state UNKNOWN', for example:
```
enp0s29u1u3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT  group default qlen 1000
```
is a correct network interface that can be used
for running examples on SoftRoCE.
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/542)
=> examples: add support for USB Ethernet network interfaces

README.md, cmake/librpma.pc.in, cmake/packages.cmake, examples/README.md, src/include/librpma.h
librpma is a C library to simplify accessing
persistent memory (PMem) and not persistent memory devices.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/546)
=> common: fix description of librpma

index.md
librpma is a C library to simplify accessing
persistent memory (PMem) and not persistent memory devices.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/549)
=> doc: fix description of librpma

.travis.yml
We do not use Coverity now and do not plan to do it
in the near future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/554)
=> common: remove unused Coverity job from the Travis build

doc/CMakeLists.txt, utils/src2mans.sh
The common header of markup manuals has to be given
using the absolute path so that it works in case of out-of-tree builds.
Ref: #562
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/583)
=> common: add an argument for common header of markup manuals

src/include/librpma.h
The unquoted '..' string is interpreted by 'man' as undefined macro
and produces the following warning:
```
$ man --warnings >/dev/null ./rpma_log_set_function.3
troff: <standard input>:45: warning: macro '..' not defined
```
Ref: #564
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/584)
=> rpma: fix documentation of rpma_log_function()

src/mr.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/576)
=> rpma: remove redundant assignment in usage_to_access()

src/flush.c, tests/unit/flush/flush-apm_do.c
Current rpma_flush() always uses RPMA_F_COMPLETION_ALWAYS and
ignores RPMA_F_COMPLETION_ON_ERROR.  In this case, rpma_flush()
cannot choose that the completion event is only generated on
error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/580)
=> rpma: make rpma_flush() use custom flags

examples/08-messages-ping-pong/client.c, examples/08-messages-ping-pong/server.c
void* is supposed to be compatible with any other pointer, but printf format checks disagree.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/586)
=> -Wformat fixes

utils/docker/images/Dockerfile.fedora-rawhide
Remove the 'hub' package from Fedora rawhide docker file,
because it is no longer available in this version:
```
No match for argument: hub
Error: Unable to find a match: hub
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/588)
=> common: remove the 'hub' package from Fedora rawhide docker file

.github/workflows/gha.yml
The coverity job is not used now, so comment it out
to save the GHA resources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/590)
=> common: remove the coverity job from the regular GHA builds

utils/docker/build.sh, utils/docker/pull-or-rebuild-image.sh
The "Nightly" cron builds have been skipping
all building and testing so far. This patch fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/589)
=> common: do not skip regular jobs if build is triggered by cron

.github/workflows/nightly.yml, utils/docker/pull-or-rebuild-image.sh
Always rebuild docker images of rolling and testing distros
in the Nightly build, because they change very often.
Rebuild always only the "GCC" jobs, because only they push images out.
The "CLANG" jobs will use the old image but the new one will be used
during the next build (on the day after).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/592)
=> common: always rebuild docker images of rolling and testing distros

examples/05-flush-to-persistent/client.c, examples/05-flush-to-persistent/server.c
For server with pmem support in 05-flush-to-persistent, rpma_mr_reg()
should call RPMA_MR_USAGE_FLUSH_TYPE_VISIBILITY instead of
RPMA_MR_USAGE_FLUSH_TYPE_PERSISTENT if direct-pmem-write parameter
is not specified.
Also remove unneeded initialization of flush_type for client.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/577)
=> examples: support FLUSH_TYPE_VISIBILITY on pmem

tools/ddio.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/597)
=> common: tools: ddio.sh

tools/ib_read_lat.sh, tools/rpma_read_lat.sh
`ssh -v` allows collecting verbose error output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/615)
=> common: tools: ib/rpma_read_lat sshpass -v for verbosity

src/conn.c, src/mr.c, src/mr.h, tests/unit/common/mocks-rpma-mr.c, tests/unit/common/test-common.h, tests/unit/conn/conn-write.c, tests/unit/conn/conn-write_atomic.c, tests/unit/mr/mr-write.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/603)
=> rpma: Atomic write with IBV_SEND_FENCE flag

tools/csv_compare.py
Please welcome the very very preliminary implementation of the CSV comparison tool. Stay tuned for more.
FYI: The script needs standardized-CSVs introduced by PR #620.
Currently, a product of the script looks as follows:
Errata:
- now the x-axis label is `block size [B]`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/621)
=> common: tools: CSV files compare

tools/csv_compare.py
Requires:
```sh
$ ./csv_compare.py --output_layout lat ib_read_lat-20-12-07-165933.csv rpma_read_lat-20-12-03-203633.csv \
--output_title 'Title of the example comparison' --legend "ib_read_lat" "rpma_read"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/629)
=> tools: allow custom legend for CSV compare

tools/csv_compare.py
```sh
$ ./csv_compare.py --output_layout bw_vs_th --legend ib_read_bw --output_title "A show off of the new layout" \
ib_read_bw-th-4096bs-20-12-09-124331.csv
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/649)
=> tools: introduce a bw(threads) comparison layout

tools/fio_jobs/librpma-client-read-bw.fio, tools/ib_read.sh
... and iodepth=2 for fio librpma_client engine
and make it asynchronous.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/655)
=> tools: set size of tx queue equal 2 for ib_read_bw

tools/csv_compare.py
Introduce a more intelligent way of calculating all possible x-axis values and at the same time fixes the related issue which has not allowed to have a data table in case the input CSVs does not have the exactly the same x-range covered.
Now it works both ways:
and another way:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/658)
=> tools: fix building a x-values set and fill blanks in the table

tools/csv_compare.py
Replace `bw_vs_bs` and `bw_vs_threads` layouts (and `bw_vs_iopdeth` which is coming soon) with a single `bw` layout with an additional argument: `--arg_axis` which allows set a configurable axis to be used by layouts allowing that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/665)
=> tools: introduce --arg_axis in place of bw_vs_<arg_axis>

tools/rpma_fio_bench.sh
Save whole path of the mmap directory:
- save `dev_dax1.0` instead of `dax1.0` in case of `mmap:/dev/dax1.0`
- save `tmp_dir` instead of `dir` in case of `mmap:/tmp/dir`
- save `d1_d2_d3_d4` instead of `2/d3/d4` in case of `mmap:/d1/d2/d3/d4`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/681)
=> tools: save whole path of mmap directory

tools/ib_read.sh, tools/rpma_fio_bench.sh
sshpass doesn't work well when .ssh/known_hosts doesn't have the
related public key record(e.g. do scp/ssh for the first time).
For example:
\-------------------------------------------------------
Are you sure you want to continue connecting (yes/no/[fingerprint])?
SSHPASS detected host authentication prompt. Exiting.
Host key verification failed.
\-------------------------------------------------------
Make sshpass work well by disabling StrictHostKeyChecking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/699)
=> tools: Disable StrictHostKeyChecking for scp/ssh

tools/csv_compare.py
Automatically peak and write down all parameters which are assumed constant.
In this case:
- iodepth=2
- block size=4096B
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/703)
=> tools: introduce constant parameters description

tools/csv_compare.py
Having a properly named files e.g.:
```sh
$ ls | grep \\.csv
rpma_fio_read_lat__WP_135_137__-20-12-14-110446.csv
rpma_fio_read_lat__WP_146_145__-20-12-14-113257.csv
rpma_fio_read_lat__WP_202_203__-20-12-14-092316.csv
```
you can easily generate:
```sh
$ ./csv_compare.py --output_layout lat_avg --output_with_tables --legend_from_file_names *.csv
```
a nifty comparison:
Should play nicely with #691.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/695)
=> tools: generate legend from file names __COMMENT__s

tools/fio_jobs/librpma_gpspm-server.fio
Ref: pmem/fio#76
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/712)
=> tools: librpma_gpspm_server has to run as long as the client needs

src/include/librpma.h
The argument flags is not suitable for rpma_recv().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/748)
=> rpma: Remove wrong section of rpma_recv.3 manual

examples/03-read-to-persistent/client.c, examples/03-read-to-persistent/server.c, examples/04-write-to-persistent/client.c, examples/04-write-to-persistent/server.c, examples/05-flush-to-persistent/client.c, examples/05-flush-to-persistent/server.c, examples/07-atomic-write/server.c, examples/09-flush-to-persistent-GPSPM/client.c, examples/09-flush-to-persistent-GPSPM/server.c
Explicit error message to stderr in case example could not
open pmem file.
Renaming dst_ptr -> mr_ptr for examples uniformity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/708)
=> rpma: error message on pmem_map_file() failure

tools/rpma_fio_bench.sh
Required env vars are not verified now when the GPSPM mode is set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/770)
=> tools: fix checking if required env vars are set in GPSPM mode

tools/create_report.py, tools/templates/.gitignore, tools/templates/audience.md.template, tools/templates/authors.md.template, tools/templates/bios.md.template, tools/templates/configuration_common.md.template, tools/templates/configuration_target.md.template, tools/templates/report.md, tools/templates/security.md.template
New sections are:
- authors
- audience
- configuration_common
- configuration_target
- bios
- security
Using the following command:
```sh
$ ./create_report.py --report_dir report_trial/ --release 0.9 --test_date "December 2020"
```
initially, you will get the following result:
If you just copy the predefined *.md.template files:
```sh
$ for t in templates/*.template; do cp $t ${t//\.template/}; done
```
place holders will take their place:
which when filled with actual content will look similar to the following pictures:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/764)
=> tools: add further sections to the report

tools/ddio.sh
'-eq' and '-ne' should be used only for integers, not for strings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/773)
=> tools: fix test expressions in ddio.sh

tools/.gitignore, tools/report_bench.sh
Since `rpma_fio_bench.sh` does a lot more than it is specified for the upcoming report format I have created a separate script doing just that - runs all benchmarks required to prepare the report. All comments are very welcome.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/781)
=> tools: report_bench.sh to all benchmarks required for the report

examples/01-connection/client.c, src/conn.c, src/include/librpma.h, src/rpma.c, tests/unit/conn/conn-next_event.c, tests/unit/utils/utils-conn_event_2str.c
Improve examples?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/802)
=> rpma: add RDMA_CM_EVENT_REJECTED event handler

examples/01-connection/CMakeLists.txt
It fixes the following compilation error:
```
/rpma/examples/01-connection/client.c: In function 'main':
/rpma/examples/01-connection/client.c:72:2: error: 'for' loop \
initial declarations are only allowed in C99 mode
for (int retry = 0; retry < MAX_RETRY; retry++) {
^
/rpma/examples/01-connection/client.c:72:2: note: use option \
-std=c99 or -std=gnu99 to compile your code
make[2]: *** [CMakeFiles/client.dir/client.c.o] Error 1
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/822)
=> examples: fix compilation error of 01-example

tools/templates/configuration_common.md.template
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/829)
=> tools: rename OFED -> rdma-core and get rid of the irrelevant NIC

tools/templates/layout.html
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/848)
=> tools: remove the hamburger menu (does not look good on printouts)

examples/02-read-to-volatile/CMakeLists.txt, examples/03-read-to-persistent/CMakeLists.txt, examples/04-write-to-persistent/CMakeLists.txt, examples/05-flush-to-persistent/CMakeLists.txt, examples/06-multiple-connections/CMakeLists.txt, examples/07-atomic-write/CMakeLists.txt, examples/08-messages-ping-pong/CMakeLists.txt, examples/09-flush-to-persistent-GPSPM/CMakeLists.txt
According to the readme, examples' executable names shall be
either client or server, without 'example-' prefix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/768)
=> common: remove unnecessary prefix in example executable name

src/conn.c, tests/unit/conn/conn-completion_get.c
`wc_flags` is of `int` type in older versions of libibverbs.
This patch fixes the following two errors:
```
/rpma/src/conn.c:542:19: error: implicit conversion changes \
signedness: 'int' to 'unsigned int' [-Werror,-Wsign-conversion]
cmpl->flags = wc.wc_flags;
~ ~~~^~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/rpma.dir/conn.c.o] Error 1
```
See: 
https://github.com/ldorau/rpma/actions/runs/538381902 - 14 builds failed
and:
```
/rpma/tests/unit/conn/conn-completion_get.c:196:18: \
error: implicit conversion changes signedness: \
'unsigned int' to 'int' [-Werror,-Wsign-conversion]
wc.wc_flags = flags[i];
~ ^~~~~~~~
1 error generated.
```
See: 
https://github.com/ldorau/rpma/actions/runs/538410281 - 14 builds failed.
---
This change is [<img …
=> rpma: fix the implicit conversion error

tools/templates/tc1_read.md, tools/templates/tc2_write.md
Fix one typo in tools/templates/tc1_read.md:19:
- 'Taraget' ==> 'Target'
and another one in tools/templates/tc2_write.md:4
- 'Taget' ==> 'Target'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/854)
=> tools: fix typos in tc1_read.md and tc2_write.md

examples/10-send-with-imm/CMakeLists.txt
`clock_gettime()` requires linking with `librt` for `glibc` versions before 2.17.
```
/usr/lib64/librpma.so: undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
/make[2]: *** [server] Error 1
```
See: https://github.com/ldorau/rpma/actions/runs/538482802 - 2 builds failed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/853)
=> examples: link 10-send-with-imm example with librt for glibc<2.17

utils/docker/images/Dockerfile.centos-8
Replace `PowerTools` with `powertools` in the CentOS-8 docker file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/859)
=> common: fix name of powertools repo in CentOS-8

utils/docker/images/Dockerfile.centos-6
Disable CentOS-6 Base repo, because CentOS-6 has been EOL-ed:
https://wiki.centos.org/About/Product
and enable the CentOS-10 Vault repo:
https://vault.centos.org/6.10/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/861)
=> common: fix EOL-ed CentOS 6 repo - switch to the Vault repo

src/flush.c, src/flush.h, src/include/librpma.h, tests/integration/common/mocks.c, tests/integration/common/mocks.h, tests/integration/example-01-connection/CMakeLists.txt, tests/integration/example-01-connection/example-01-connection.c, tests/integration/example-02-read-to-volatile/CMakeLists.txt, tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, tests/integration/example-04-write-to-persistent/CMakeLists.txt, tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, tests/unit/common/mocks-rpma-mr.c, tests/unit/common/mocks-stdlib.c, tests/unit/common/mocks-stdlib.h, tests/unit/conn/conn-new.c, tests/unit/flush/CMakeLists.txt, tests/unit/flush/flush-common.c, tests/unit/flush/flush-common.h, tests/unit/flush/flush-new.c
The memory region passed to `rpma_mr_reg()` (`ibv_mr_reg()`)
cannot be allocated from the heap (using `malloc()`
or `posix_memalign()`), but should be mapped using `mmap()`.
Rationale:
If `ibv_fork_init()` was called, the memory region
passed to `ibv_mr_reg()` is marked by this function
with the DC (“do not copy on fork”) flag
and after having called `fork()`, the child process
does not receive this range of virtual addresses.
If this memory region was allocated from the heap,
the child process receives a corrupted heap
with a “hole” of inaccessible addresses inside.
A memory allocator knows nothing about this “hole”
and if it tries to access (read or write)
that range of virtual addresses, it causes a segfault.
Ref: #751
---
This change is [<img …
=> rpma: mmap() memory for rpma_mr_reg() in rpma_flush_apm_new()

src/conn.c
The continuation line of the 'if' condition
should be indented by 4 spaces, not by tabs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/884)
=> rpma: fix indentation of the 'if' conditions

examples/run-all-on-SoftRoCE.sh
Change the default port for examples from 8765 to 7204.
- port 8765 can be used by Ultraseek HTTP, while
https://www.speedguide.net/port.php?port=8765
- port 7204 is unassigned yet:
https://www.speedguide.net/port.php?port=7204
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/885)
=> examples: change the default port for examples

src/mr.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/881)
=> rpma: correct the order of src_addr and dst_addr

src/conn_req.c, tests/unit/conn_req/conn_req-connect.c
The resources freed under the 'err_conn_req_delete' label
had been already freed by rpma_conn_delete(&conn)
under the 'err_conn_delete' label.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/888)
=> rpma: fix double free in rpma_conn_req_connect_active()

src/mr.c
Make sure the size of the usage field in the `rpma_mr_get_descriptor()`
and `rpma_mr_remote_from_descriptor()` functions (`uint8_t` as for now)
is big enough to store all possible `RPMA_MR_USAGE_*` values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/901)
=> rpma: clarify restrictions for size of the usage field

tests/multithreaded/utils/rpma_utils_get_ibv_context.c
addr[MAX_ADDR] is too small to store the whole IP address
so that running rpma_utils_get_ibv_context always failed.
For example: ./rpma_utils_get_ibv_context 32 192.168.122.189
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/908)
=> test: increase MAX_ADDR in rpma_utils_get_ibv_context.c

src/rpma_err.c, tests/unit/error/error.c
Print out "Success" instead of "Unknown error" when ret == 0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/904)
=> rpma: handle success in rpma_err_2str()

examples/02-read-to-volatile/client.c, examples/02-read-to-volatile/server.c, examples/04-write-to-persistent/client.c, examples/04-write-to-persistent/server.c, tests/integration/example-02-read-to-volatile/CMakeLists.txt, tests/integration/example-04-write-to-persistent/CMakeLists.txt
Separate mocking main() from including cmocka headers,
because one can want to mock the main() function
without using the cmocka framework.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/910)
=> test: include cmocka only #ifdef TEST_USE_CMOCKA

examples/02-read-to-volatile/server.c, examples/03-read-to-persistent/client.c, examples/04-write-to-persistent/server.c, examples/05-flush-to-persistent/server.c, examples/06-multiple-connections/client.c, examples/07-atomic-write/server.c, examples/09-flush-to-persistent-GPSPM/server.c
Zero the common_data data structure,
so that the whole 'descriptors' array:
```
char descriptors[DESCRIPTORS_MAX_SIZE];
```
was initialized.
See: https://github.com/pmem/fio/pull/236
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/913)
=> examples: zero the common_data data structure

tools/perf/rpma_fio_bench.sh
There is on my machine:
```
$ lscpu | egrep 'Core'
Core(s) per socket:              6
Model name:                      Intel(R) Core(TM) i7-3960X CPU @ 3.30GHz
$ lscpu | egrep 'Core' | sed 's/[^0-9]*//g'
6
73960330
```
So the command should be:
```
$ lscpu | egrep 'Core\(s\) per socket:' | sed 's/[^0-9]*//g'
6
```
in order to get the correct number of cores per socker.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/957)
=> tools: fix setting CORES_PER_SOCKET

tools/perf/rpma_fio_bench.sh
make sar and emon use the same directory of results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/972)
=> tools: replace REMOTE_SAR_RESULTS_DIR with REMOTE_RESULTS_DIR

CMakeLists.txt
Add TESTS_USE_VALGRIND_PMEMCHECK==OFF by default to silent
the following warning:
```
CMake Warning at cmake/functions.cmake:148 (message):
Valgrind pmemcheck NOT found.  Pmemcheck tests will not be performed.
Call Stack (most recent call first):
CMakeLists.txt:218 (find_pmemcheck)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/987)
=> common: add TESTS_USE_VALGRIND_PMEMCHECK==OFF by default

tests/multithreaded/common/mtt.c, tests/multithreaded/common/mtt.h, tests/multithreaded/utils/rpma_utils_get_ibv_context.c
- rename MTT-API macros:
- MTT_THREAD_ERR -> MTT_ERR
- MTT_THREAD_RPMA_ERR -> MTT_RPMA_ERR
- rename internal MTT error helpers:
- MTT_ERR -> MTT_INTERNAL_ERR
- MT_TEST_ERR -> MTT_TEST_ERR (fix)
- add to the error messages: file name, line, and function
- MTT_ERR, MTT_RPMA_ERR
An error message after this change will look as follow:
```
[thread #31] rpma_utils_get_ibv_context.c:33 thread() -> rpma_utils_get_ibv_context() failed: Unknown error
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1003)
=> test: mt: clean up error handling

.github/workflows/nightly.yml, .github/workflows/nightly_experimental.yml, utils/docker/build.sh, utils/docker/run-build.sh, utils/docker/set-ci-vars.sh
Move the Fedora Rawhide with sanitizers build to Nightly_Experimental,
because sanitizers fail all tests for unknown reason for a long time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1004)
=> common: CI: move Fedora Rawhide with sanitizers build to Nightly_Experimental

src/mr.c, src/peer.c, src/peer.h, tests/integration/common/mocks.c, tests/integration/common/mocks.h, tests/unit/common/mocks-ibverbs.c, tests/unit/common/mocks-ibverbs.h, tests/unit/common/mocks-rpma-peer.c, tests/unit/mr/mr-reg.c, tests/unit/peer/peer-common.c, tests/unit/peer/peer-common.h, tests/unit/peer/peer-mr_reg.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1044)
=> rpma: adopt usage_to_access to support iWARP specificity

tests/unit/private_data/private_data-common.c, tests/unit/private_data/private_data-common.h, tests/unit/private_data/private_data-store.c
Use unified MOCK_OK for return value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1024)
=> test: replace SUCCESS with MOCK_OK

examples/07-atomic-write/client.c
Fixes: #1010
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1057)
=> examples: delete completion_get() appearing before completion_wait()

src/include/librpma.h
Add missing RPMA_OP_RECV_RDMA_WITH_IMM in rpma_conn_completion_get.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1059)
=> rpma: add missing rpma operation in manual

tests/unit/common/test-common.h, tests/unit/ep/ep-listen.c, tests/unit/ep/ep-next_conn_req.c
replace real errno (e.g. EAGAIN, ENOMEM) with simulated
errno (e.g. MOCK_ERRNO, MOCK_ERRNO2) on all ep unit tests.
Note:
except ENODATA because it is processed by librpma specially.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1061)
=> test: use simulated errno on all ep unit tests

examples/02-read-to-volatile/client.c, examples/02-read-to-volatile/server.c, examples/03-read-to-persistent/client.c, examples/03-read-to-persistent/server.c, examples/04-write-to-persistent/client.c, examples/04-write-to-persistent/server.c, examples/05-flush-to-persistent/client.c, examples/05-flush-to-persistent/server.c, examples/06-multiple-connections/client.c, examples/07-atomic-write/client.c, examples/07-atomic-write/server.c, examples/08-messages-ping-pong/client.c, examples/09-flush-to-persistent-GPSPM/client.c, examples/10-send-with-imm/client.c, examples/11-write-with-imm/client.c, examples/common/common-conn.c, examples/common/common-conn.h
pass conn_cfg into client_connect() and server_accept_connection().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1067)
=> examples: make common functions accept conn_cfg

utils/docker/images/install-txt2man.sh
Force removing txt2man directory in install-txt2man.sh to suppress the following questions:
```
rm: remove write-protected regular file 'txt2man/.git/objects/pack/pack-28804f9ef8a7e6b537d8fd2abae16c2ec7e91c92.pack'? y
rm: remove write-protected regular file 'txt2man/.git/objects/pack/pack-28804f9ef8a7e6b537d8fd2abae16c2ec7e91c92.idx'? y
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1092)
=> common: force removing txt2man directory in install-txt2man.sh

.circleci/config.yml, .gitignore
To prevent gh-pages CircleCI builds from failing.
Lack of the CircleCI configuration causes a fail.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1085)
=> common: add circleci nop build

tools/perf/BENCHMARKING.md
1) remove the useless backslash (\) because it doesn't work if the word
is enclosed by backquote (``)
2) also enclose other commands/scripts by backquote (``)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1136)
=> tools: remove the useless backslash (\)

examples/04-write-to-persistent/client.c, examples/common/common-conn.c
Generally, program should exit with non-zero if there is something wrong
Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1140)
=> examples/04-write-to-persistent: correct the return value

cmake/functions.cmake
For the default C compiler ("cc"), check_signature_rdma_getaddrinfo()
doesn't catch it and doesn't add "-Werror=discarded-qualifiers" to
check the version of rdma_getaddrinfo().  In this case,
RDMA_GETADDRINFO_NEW_SIGNATURE cannot show the correct value.
Ref: #1138
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1139)
=> common: add "-Werror=discarded-qualifiers" for the "cc" symlink 

src/conn.c, tests/unit/conn/conn-new.c
rpma_conn_delete() cannot call rdma_destroy_qp() before rdma_destroy_id() when rpma_flush_delete() gets an error so fix the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1160)
=> rpma: call rdma_destroy_qp() when rpma_flush_delete() gets an error

utils/cstyle
Previously, cstyle will complain 'missing space before - operator'
with an array like:
static int rets[] = {-1, EAI_SYSTEM, EAI_AGAIN};
^^^
Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1156)
=> common: Fix 'missing space before - operator' in first element of array

tools/perf/tests/lib/benchmark/test_run.py
Replace `tmp_path` with `tmpdir` to fix the error:
```
E       fixture 'tmp_path' not found
```
and cast `tmpdir` to `str` in `join()` to fix the error:
```
>        elif not path or path.endswith(sep):
E        AttributeError: 'LocalPath' object has no attribute 'endswith'
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1165)
=> tools: replace tmp_path with tmpdir

tools/perf/lib/Figure.py, tools/perf/tests/lib/figure/test_html_data_table.py
Replace `_` with `\_` in `oneseries['label']` to prevent converting strings to italics.
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1172)
=> tools: replace '_' with '\_' in oneseries['label']

tests/multithreaded/conn/CMakeLists.txt
Disable the `multithreaded-conn-rpma_conn_get_private_data_0_none` test
temporarily, because it fails very often:
```
*NOTE*  conn_req.c: 317: rpma_conn_req_new: Requesting a connection to 10.142.2.219:7204
*NOTE*  conn.c: 189: rpma_conn_next_event: Connection rejected
error: rpma_conn_get_private_data.c:74 prestate_init() -> rpma_conn_next_event returned an unexpected event
```
Enable it again, when the correct synchronization in MT-tests is implemented
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1175)
=> test: disable the multithreaded-conn-rpma_conn_get_private_data test

tools/perf/lib/Part.py, tools/perf/lib/Report.py, tools/perf/templates/part_preamble.md, tools/perf/templates/part_read.md, tools/perf/tests/lib/part/test_init.py
- lib.Part:
- call items read from part_*.json as constants
- add set_variables() for variables
- skip markdown processing for menu() (unnecessary `<p/>`)
- allow calling content() without custom arguments
- lib.Report:
- add preamble as the first part of the report
- provide a dummy variables required for it to render
- templates/part_preamble.md:
- a slighly adopted copy of various templates/* files
- updated disclaimer
- refer variables as it seems to be convenient in the future
- templates/part_read.md:
- move `<a>Introduction</a>` to part_preamble.md (fix)
- add missing `<h2>Read from PMem</h2>`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1176)
=> tools: perf: add preamble to the report

tools/perf/lib/Figure.py, tools/perf/tests/lib/figure/test_html_data_table.py
lib/Figure.py:201
/rpma/tools/perf/lib/Figure.py:201: DeprecationWarning: invalid escape sequence \_
html += "<tr><td>" + oneseries['label'].replace('_', '\_') + "</td>"
-- Docs: https://docs.pytest.org/en/stable/warnings.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1183)
=> tools: fix invalid escape sequence + fix typo

tools/perf/lib/Bench.py, tools/perf/tests/lib/bench/test_carry_on.py
- result_dir is calculated each time from the bench.json location
- it allows moving freely and using bench.json from various locations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1189)
=> tools: perf: do not cache result_dir in bench.json

tools/perf/BENCHMARKING.md
The librpma FIO engines are already upstreamed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1190)
=> tools: perf: update the fio references

examples/03-read-to-persistent/client.c, examples/common/common-conn.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1185)
=> examples: print a message in case no pmem provided or able to be used

CMakeLists.txt
Ref: #1089
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1200)
=> common: print a message in case pmem won't be able to be used

src/info.c, tests/unit/common/mocks-netdb.c, tests/unit/common/mocks-netdb.h, tests/unit/common/mocks-rdma_cm.c, tests/unit/common/mocks-string.c, tests/unit/common/mocks-string.h, tests/unit/info/CMakeLists.txt, tests/unit/info/info-bind_addr.c, tests/unit/info/info-new.c, tests/unit/info/info-resolve_addr.c
Per rdma_getaddrinfo man page
```
RETURN VALUE
Returns 0 on success, or -1 on error (errno will be set to indicate the failure reason), or one of the following nonzero error codes:
...
EAI_SYSTEM  Other system error, check errno for details.  The gai_strerror() function translates these error codes to a human readable string, suitable for error reporting.
```
errno will be used when -1 or EAI_SYSTEM is returned.
Before:
$ build/examples/03-read-to-persistent/client r92.168.1.10 9999
Next value: Hello world!
Jul 14 18:33:16.543688 [93128] *ERROR* info.c:  60: rpma_info_new: rdma_getaddrinfo(node=r92.168.1.10, service=(null), ai_flags=active, ai_qp_type=IBV_QPT_RC, ai_port_space=RDMA_PS_TCP) failed: No such file or directory
After:
$ build/examples/03-read-to-persistent/client r92.168.1.10 …
=> rpma_info_new: log the real error message

src/include/librpma.h
Markdown formatting is not handled by src2man.
Ref: #1170
Ref: #518
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1208)
=> rpma: fix the rpma_conn_completion_get() documentation

tools/perf/lib/bench.py, tools/perf/lib/figure.py
It fixes the following errors:
```
************* Module lib.bench
rpma/tools/perf/lib/bench.py:64:13:  W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
************* Module lib.figure
rpma/tools/perf/lib/figure.py:150:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1228)
=> tools: set encoding in open() (fix)

tools/perf/lib/figure.py
Fix:
```
RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1240)
=> tools: perf: close matplotlib.pyplot.figure's

.github/workflows/nightly.yml, utils/docker/images/Dockerfile.rockylinux-8.4, utils/docker/images/Dockerfile.vzlinux-latest
Add Rocky Linux and VzLinux (successors of CentOS) to the nightly CI builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1205)
=> common: add Rocky Linux and VzLinux to the nightly CI builds

tools/perf/report_create.py
Do nothing if src and dst specify the same file
when copying report.json file to the result dir
for future reference.
```
Traceback (most recent call last):
File "/mnt/files/repos/rpma/tools/perf/./report_create.py", line 45, in <module>
main()
File "/mnt/files/repos/rpma/tools/perf/./report_create.py", line 40, in main
copy(args.report['input_file'], bench.result_dir)
File "/usr/lib/python3.9/shutil.py", line 418, in copy
copyfile(src, dst, follow_symlinks=follow_symlinks)
File "/usr/lib/python3.9/shutil.py", line 244, in copyfile
raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: './report_python/report.json' and '/mnt/files/repos/rpma/tools/perf/report_python/report.json' are the same file
```
---
This change …
=> tools: do nothing if src and dst specify the same file

tools/perf/rpma_fio_bench.sh
When we run server ioengine with DRAM, setup_files() in fio will create the unused 'malloc' file by some operations (e.g. fallocate, ftruncate). This behavior makes server spend more time to prepare the connection so that client always triggers the "The maximum number of retries exceeded" error.  See the detailed output:
```
Thread [7]: The maximum number of retries exceeded. Closing. IOPS][eta 01m:00s]
Thread [7]: Connected after retry #10
Thread [29]: Connected after retry #9
Thread [2]: The maximum number of retries exceeded. Closing.
Thread [9]: The maximum number of retries exceeded. Closing.
Thread [2]: Connected after retry #10
Thread [9]: Connected after retry #10
Thread [15]: The maximum number of retries exceeded. Closing.
Thread [15]: Connected after retry #10
Thread [19]: The …
```
=>  tools: add --create_on_open=1 for the DRAM mode 

tests/unit/ep/ep-common.c, tests/unit/ep/ep-common.h, tests/unit/ep/ep-listen.c, tests/unit/info/info-common.c, tests/unit/info/info-common.h, tests/unit/info/info-new.c
some macros in info-common.h has been defined by test-common.h.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1198)
=> test: remove duplicate macros in info-common.h

utils/docker/images/Dockerfile.archlinux-latest, utils/docker/images/Dockerfile.centos-7, utils/docker/images/Dockerfile.centos-8, utils/docker/images/Dockerfile.debian-10, utils/docker/images/Dockerfile.debian-9, utils/docker/images/Dockerfile.debian-experimental, utils/docker/images/Dockerfile.debian-stable, utils/docker/images/Dockerfile.debian-testing, utils/docker/images/Dockerfile.fedora-26, utils/docker/images/Dockerfile.fedora-27, utils/docker/images/Dockerfile.fedora-28, utils/docker/images/Dockerfile.fedora-29, utils/docker/images/Dockerfile.fedora-30, utils/docker/images/Dockerfile.fedora-31, utils/docker/images/Dockerfile.fedora-32, utils/docker/images/Dockerfile.fedora-33, utils/docker/images/Dockerfile.fedora-rawhide, utils/docker/images/Dockerfile.opensuse-leap-latest, utils/docker/images/Dockerfile.opensuse-tumbleweed-latest, utils/docker/images/Dockerfile.rockylinux-8.4, utils/docker/images/Dockerfile.ubuntu-18.04, utils/docker/images/Dockerfile.ubuntu-20.04, utils/docker/images/Dockerfile.ubuntu-rolling, utils/docker/images/Dockerfile.vzlinux-latest
Add matplotlib, pytest and other required python packages
to Docker files of OSes tested in nightly CI builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1256)
=> common: add matplotlib, pytest and co. to Docker files

utils/docker/images/Dockerfile.fedora-34
See commit ce36455
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1261)
=> common: add missing upgrade of pip to Fedora 34 docker image

.github/workflows/nightly.yml, .github/workflows/nightly_experimental.yml
Move all Fedora Rawhide CI builds to Nightly_Experimental,
since they have been failing for a long time,
because of the following error:
```
Curl error (6): Couldn't resolve host name for \
https://mirrors.fedoraproject.org/metalink?repo=rawhide&arch=x86_64 [getaddrinfo() thread failed to start]
```
See:
https://www.mail-archive.com/devel@lists.fedoraproject.org/msg169919.html
https://github.com/actions/virtual-environments/issues/3812
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1275)
=> common: move all Fedora Rawhide CI builds to Nightly_Experimental

CMakeLists.txt, cmake/functions.cmake, doc/manuals_3.txt, src/include/librpma.h, src/mr.c, tests/unit/common/mocks-ibverbs.c, tests/unit/common/mocks-ibverbs.h, tests/unit/mr/CMakeLists.txt, tests/unit/mr/mr-advise.c, tests/unit/mr/mr-common.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1220)
=> rpma: add rpma_mr_advise()

.github/workflows/nightly_experimental.yml, .github/workflows/nightly_rebuild.yml
Move the last Fedora Rawhide CI build
from Nightly_Rebuild to Nightly_Experimental.
See: #1275 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1277)
=> common: move the last Fedora Rawhide CI build to Nightly_Experimental

.github/workflows/nightly_rebuild.yml, utils/docker/images/Dockerfile.centos-stream
There is NO official docker image of CentOS Stream,
so we use tgagor/centos-stream.
See:
https://hub.docker.com/r/tgagor/centos-stream/tags
https://timor.site/2021/02/centos-8-stream-docker-image/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1278)
=> common: add CentOS Stream CI build to Nightly_Rebuild

tools/perf/figures/read.json, tools/perf/figures/write.json, tools/perf/report.json.example, tools/perf/templates/part_mix.md, tools/perf/templates/part_write.md
- encourage defining DW2PMem (the default) vs non-DW2PMem configuration in report.json
- highlight where the non-default (non-DW2PMem) configuration is used
- which replaces the not-futureproof DDIO=ON
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1279)
=> tools: perf: precisely define DW2PMem vs non-DW2PMem

.github/workflows/nightly.yml, .github/workflows/nightly_experimental.yml, .github/workflows/nightly_rebuild.yml, .github/workflows/on_pull_request.yml
1. Add a description to all GHA workflow files.
2. Re-add Debian9 to Nightly builds
(reverted from the commit 45484c8),
so that it contains all OSes supported by librpma now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1283)
=> common: add description to all GHA workflow files

utils/pylint.rc
Disable the pylint 'consider-using-f-string' warning, see:
https://github.com/pmem/rpma/runs/3627503704
We cannot use f-strings, because they are not supported
on Debian 9 with python v3.5.3 and pylint3 v1.6.5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1287)
=> common: disable consider-using-f-string in pylint

tools/perf/bench_common.sh
Do really skip the test when REMOTE_DIRECT_WRITE_TO_PMEM does not have the required value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1288)
=> tools: do really skip the test

_data/libs_map.yml, _data/releases_linux.yml
Ref: #1080 #1220
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1216)
=> doc: separate receive CQ & rpma_mr_advise()

src/include/librpma.h
1) add structure rpma_completion to the documentation
2) describe fields of the structure rpma_completion
3) add missing rpma_conn_req_recv(3) reference
Ref: #1211 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1214)
=> doc: describe structure rpma_completion

.github/workflows/nightly.yml, .github/workflows/nightly_experimental.yml, .github/workflows/nightly_rebuild.yml
Move the OpenSUSE_Tumbleweed build to Nightly_Experimental,
because of the following bug:
https://bugzilla.opensuse.org/show_bug.cgi?id=1190670
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1301)
=> common: move OpenSUSE_Tumbleweed build to Nightly_Experimental

utils/docker/images/install-cmocka.sh
```
Cloning into 'cmocka'...
fatal: unable to access 'https://git.cryptomilk.org/projects/cmocka.git/': server certificate verification failed. CAfile: none CRLfile: none
Exited with code exit status 128
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1302)
=> common: retry installing cmocka after updating certificates

examples/02-read-to-volatile/client.c, examples/03-read-to-persistent/server.c, examples/04-write-to-persistent/client.c, examples/05-flush-to-persistent/client.c, examples/06-multiple-connections/server.c, examples/07-atomic-write/client.c, examples/08-messages-ping-pong/client.c, examples/08-messages-ping-pong/server.c, examples/10-send-with-imm/client.c, examples/10-send-with-imm/server.c, examples/11-write-with-imm/client.c, examples/11-write-with-imm/server.c
Ref: #1212
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1271)
=> Update all examples to use new APIs

utils/docker/images/Dockerfile.debian-11, utils/docker/images/Dockerfile.debian-experimental, utils/docker/images/Dockerfile.debian-stable, utils/docker/images/Dockerfile.debian-testing, utils/docker/images/Dockerfile.fedora-34, utils/docker/images/Dockerfile.fedora-rawhide, utils/docker/images/Dockerfile.opensuse-tumbleweed-latest, utils/docker/images/Dockerfile.ubuntu-21.04, utils/docker/images/Dockerfile.ubuntu-rolling
use of libpmem2 instead of libpmem for mapping PMem allows decreasing number of resources needed to run examples
Ref: #991
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1306)
=> common: add libpmem2 to docker images

tools/perf/csv2standardized.py, tools/perf/fio_json2csv.py, tools/perf/lib/Report.py, tools/perf/lib/bench.py, tools/perf/lib/common.py, tools/perf/lib/figure.py
Add the 'encoding' argument to all open() calls to avoid the error:
```
W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1323)
=> common: add encoding argument to all open() calls

examples/09-flush-to-persistent-GPSPM/server.c
cfg can leak here - fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1325)
=> examples: fix memory leak in the 09 example

tools/perf/lib/Requirement.py
- REMOTE_SUDO_NOPASSWD
- REMOTE_RNIC_PCIE_ROOT_PORT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1327)
=> tools: perf: do not assume presence of optional vars

tools/perf/BENCHMARKING.md, tools/perf/lib/Report.py, tools/perf/lib/compare.py, tools/perf/lib/figure.py, tools/perf/report_figures.py, tools/perf/tests/lib/report/test_init.py, utils/pylint.rc
Continuation #1298
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1319)
=> tools: perf: introduce report_figures.py compare mode

tools/perf/lib/benchmark/runner/ib_read.py
```
"rpma/tools/perf/lib/benchmark/runner/ib_read.py", line 25, in __validate
if self.__benchmark.oneseries[key] != value:
KeyError: 'rw'
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1342)
=> tools: verify if key is in the figure (fix)

tools/perf/lib/figure.py
Fix the following error:
```
rpma/tools/perf/lib/figure.py:33:23: \
C0103: Argument name "f" doesn't conform to snake_case naming style (invalid-name)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1353)
=> tools: fix name of the f argument in figure.py

tests/tools/perf/kvtable/test_dict2kvtable.py
Fix the following error:
```
E   ModuleNotFoundError: No module named 'lib.kvtable'
ERROR tests/tools/perf/kvtable/test_dict2kvtable.py
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1389)
=> test: fix the test_dict2kvtable.py test

tools/perf/lib/report/base.py
Fix following error:
```
tools/perf/lib/report/base.py:133:34: \
C0201: Consider iterating the dictionary directly instead of calling .keys() (consider-iterating-dictionary)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1396)
=> tools: iterate the dictionary directly instead of calling .keys() (fix)

tools/perf/lib/benchmark/runner/ib_read.py
`AUX_PARAMS` and `REMOTE_AUX_PARAMS` are strings
and can contain many arguments, so they have to be splitted
by the space ' ' to lists.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1405)
=> tools: fix reading AUX_PARAMS and REMOTE_AUX_PARAMS

tools/perf/lib/benchmark/runner/ib_read.py
`capture_output` and `text` were introduced in pyton-3.7.
There is an error in case of python-3.6:
```
File "/usr/lib64/python3.6/subprocess.py", line 423, in run
with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```
and:
```
File "/usr/lib64/python3.6/subprocess.py", line 423, in run
with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1404)
=> tools: fix capturing stdout and stderr in subprocess.run()

tools/perf/lib/benchmark/runner/ib_read.py, tools/perf/lib/format/ib_read_bw.py, tools/perf/lib/format/ib_read_lat.py
Remove not allowed spaces:
```
/rpma/tools/perf/lib/format/ib_read_bw.py:49:26: \
C0326: No space allowed before :
def parse(cls, output : str, pattern : str, ... \
^ (bad-whitespace)
/rpma/tools/perf/lib/benchmark/runner/ib_read.py:138:38: \
C0326: No space allowed around keyword argument assignment
text = True, check = True)
^ (bad-whitespace)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1407)
=> tools: remove not allowed spaces (fix)

tools/perf/lib/Requirement.py
This message does not say too much:
```
Skip: the requirement is not met: {
"direct_write_to_pmem": true
}
Benchmarking incomplete.
```
so add the following ones to tell a user more:
```
WARNINIG: REMOTE_RNIC_PCIE_ROOT_PORT is not set in config.json, so DDIO cannot be set!
```
and/or:
```
WARNINIG: REMOTE_SUDO_NOPASSWD is not True in config.json, so DDIO cannot be set!
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1409)
=> tools: add warning message if variables are not set

tests/unit/common/mocks-unistd.c, tests/unit/common/mocks-unistd.h, tests/unit/flush/flush-apm_do.c, tests/unit/flush/flush-new.c
The clang ASAN sanitizer calls sysconf() during
the initialization step before main() and it fails
all unit tests using the mock of this syscall.
This patch introduces possibility to enable chosen
(only sysconf in this patch) unistd mocks
only during the main() function of unit tests.
Fixes: #1397
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1410)
=> test: enable the sysconf mock only in the main of unit tests

tools/perf/lib/benchmark/runner/common.py
`result[x_key]` and `x_value` can have the same value,
but they can be of different types, so casting them to `str`
will solve the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1414)
=> tools: fix result_is_done()

tools/perf/lib/benchmark/runner/common.py
A result can be a tuple (read, write),
in this case it is enough to check the first dict (read),
because they both have to have the same keys.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1415)
=> tools: enable checking tuples in result_is_done() (fix)

tools/perf/lib/benchmark/runner/fio.py
Add `cpuload` to `X_KEYS` and move `__set_settings_by_mode()`,
because it is required before looking for the x-axis key
(`cpuload` can be an x-axis key, but it has to be set before).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1413)
=> tools: add cpuload to X_KEYS (fix)

tools/perf/lib/benchmark/runner/fio.py
`busy_wait_polling` has to have a numeric value 0 or 1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1422)
=> tools: fio.py: fix setting busy_wait_polling

tools/perf/lib/benchmark/runner/fio.py
Do not use the cpuio engine when cpuload==0,
because it requires cpuload > 0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1425)
=> tools: do not use cpuio engine when cpuload==0 (fix)

tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py
We have to stop the server when the client failed in order to:
1) have server logs (otherwise there are no server logs)
2) clean the server's environment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1423)
=> tools: stop the server when the client failed

tools/perf/lib/figure/image.py
Strings are sorted differently than ints ...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1429)
=> tools: make sure all values are ints before sorting them

tools/perf/lib/benchmark/runner/fio.py
'op' and 'cpuload' were missing in the message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1428)
=> tools: fix message in __server_start()

.github/workflows/on_pull_request.yml
Debian 10 is a representative of OSes that have
different behavior of the pytest "bad-whitespace" error (C0326):
https://github.com/ldorau/rpma/runs/4592854642
Debian 10 will replace Debian 9 soon.
Leave Debian 9 for a while, because it will have
Long Term Support (LTS) until the end of June 2022.
**(into pmem:devel-new-python)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1443)
=> common: add Debian 10 to On_Pull_Request CI builds

tools/perf/lib/benchmark/runner/common.py, tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py
Add checking required keys of oneseries in fio.py
and define the `MISSING_KEY_MSG` message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1446)
=> tools: check required keys of oneseries

utils/pylint.rc
Long names are required for unit test functions.
The default pylint limit is set to 30.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1465)
=> tools: pylint accepts long name

utils/pylint.rc
bad-continuation has been removed from pylint
https://github.com/PyCQA/pylint/pull/3571
It is still enabled in old releases producing a lot of
false warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1468)
=> tools: disable bad-continuation pylint warning

tests/tools/perf/kvtable/test_dict2kvtable.py
On Debian 9 the keys in the dictionary:
```
kvt = {str(k): str(k + 1) for k in range(10)}
```
are not sorted in the ascending order (0, 1, ..., 10):
https://github.com/ldorau/rpma/runs/4667689633
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1466)
=> test: fix test_dict2kvtable.py

tools/perf/lib/Requirement.py
Verify if the `REMOTE_DIRECT_WRITE_TO_PMEM` key is present in the config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1472)
=> tools: verify if REMOTE_DIRECT_WRITE_TO_PMEM is in config

tools/perf/tests/lib/benchmark/conftest.py, tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py
introduce unit tests for fio and ib_read runner
several fixes related to unhandled inputs errors to run all tests smoothly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1452)
=> tools: unit tests for runners initialization

utils/docker/images/Dockerfile.debian-experimental, utils/docker/images/Dockerfile.debian-testing
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1475)
=> common: Debian testing and experimental use pylint instead of pylint3

tools/perf/figures/read.json, tools/perf/lib/benchmark/runner/ib_read.py
Use _tool_mode in figures to avoid hardcoded tool name settings in the code
and to have a common definition of settings for fio and ib_read
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1455)
=> tools: ib_read_[lat|bw] defined in figure

tools/perf/CONFIG.JSON.md, tools/perf/lib/benchmark/runner/fio.py
If the server fails while running,
the client crashes while waiting for completion.
To get logs from the server we kill the client process
after the timeout
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1480)
=> tools: set timeout

.github/workflows/nightly_experimental.yml, .github/workflows/nightly_rebuild.yml
Move CentOS_Stream CI build to Nightly_Experimental,
because the 'epel-release' repo of CentOS Stream cannot be found
and this build has been failing for a long time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1483)
=> common: move CentOS_Stream CI build to Nightly_Experimental

tools/perf/CONFIG.JSON.md, tools/perf/lib/Requirement.py, tools/perf/lib/bench.py, tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py
Add the `SKIP_REMOTE_CMDS` config.json variable to skip running
all remote commands including copying files to the remote node.
Fixes: #1488
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1518)
=> tools: add DEBUG_SKIP_REMOTE_CMDS config.json variable

CHANGELOG.md, src/include/librpma.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1525)
=> rpma: mark as deprecated rpma_cq_get_completion(), struct rpma_completion and enum rpma_op

src/include/librpma.h
Re-mark enum rpma_op as deprecated.
It was marked as deprecated in #1525 and by accident removed in #1529.
Ref: #1525
Ref: #1529
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1538)
=> rpma: re-mark enum rpma_op as deprecated

examples/07-atomic-write/client.c
The same range of the local MR cannot be used as a source of writing
in a subsequent rpma_write() or rpma_write_atomic() calls,
because these calls are asynchronous and the first call can be
not finished yet when we modify the local MR to write there different
data for the second rpma_write() or rpma_write_atomic() call.
A different ranges of the local MR have be used as a source of writing
in a subsequent rpma_write() or rpma_write_atomic() calls instead.
Fix: #1527
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1533)
=> examples: fix example 07

CHANGELOG.md, src/include/librpma.h
Ref: #978
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1537)
=> rpma: document default values of struct rpma_conn_cfg

examples/08-messages-ping-pong/CMakeLists.txt
Add the '-std=gnu99' option to CMAKE_C_FLAGS in 08 example
in order to prevent the following error on CentOS 7:
```
/rpma/examples/08-messages-ping-pong/messages-ping-pong-common.c:66:3:\
error: 'for' loop initial declarations are only allowed in C99 mode
for (int i = 0; i < num_got; i++) {
^
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1551)
=> examples: add -std=gnu99 option to CMAKE_C_FLAGS in 08 example

src/include/librpma.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1552)
=> rpma: fix listing default values of struct rpma_conn_cfg

utils/docker/images/Dockerfile.archlinux-latest
This PR contains two fixes:
1) common: add ndctl required by pmdk to Arch Linux Dockerfile
Add the ndctl package (required by pmdk) to Arch Linux Dockerfile.
See: https://github.com/ldorau/rpma/runs/5107934970
```
==> Missing dependencies:
-> ndctl>=63
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
```
and:
2) common: fix allowing members of group wheel to execute any command
Fix allowing members of group wheel to execute any command
without a password on Arch Linux. The format of the `/etc/sudoers`
has been changed recently and the current pattern does not match
any longer.
See: https://github.com/ldorau/rpma/runs/5108094502
```
sudo: a terminal is required to read the password; \
either use the -S option to read from standard input \
or configure …
```
=> common: fix Arch Linux CI build

utils/docker/images/Dockerfile.opensuse-leap-latest, utils/docker/images/Dockerfile.opensuse-tumbleweed-latest
Fix allowing members of group wheel to execute any command
without a password on OpenSUSE Leap and Tumbleweed.
The format of the `/etc/sudoers` has been changed recently
and the current pattern does not match any longer.
Ref: 12965c4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1562)
=> common: fix allowing members of group wheel to execute any command

.github/workflows/nightly.yml, .github/workflows/nightly_experimental.yml
Move temporarily Arch Linux build to Nightly Experimental,
because of the following bug during installation of PMDK:
```
==> Starting build()...
test -f .skip-doc || make -C doc all
make[1]: Entering directory '/pmdk/src/pmdk-1.11.1/doc'
../utils/md2man.sh libpmem/libpmem.7.md default.man libpmem/libpmem.7
pandoc: /usr/lib/libc.so.6: version `GLIBC_2.34' not found \
(required by pandoc)
make[1]: *** [Makefile:257: libpmem/libpmem.7] Error 1
make[1]: Leaving directory '/pmdk/src/pmdk-1.11.1/doc'
make: *** [Makefile:62: doc] Error 2
Command exited with non-zero status 2
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1580)
=> common: move temporarily Arch Linux build to Nightly Experimental

utils/docker/run-doc-update.sh
When the build is run from a tag, then the `CI_BRANCH` variable
is set to a name of this tag instead of a branch name
and it should be handled in a different way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1585)
=> common: fix run-doc-update.sh for builds from a tag

examples/01-connection/client.c, examples/01-connection/server.c, examples/common/common-conn.c, src/cq.c, src/cq.h, src/include/librpma.h, src/rpma.c, tests/integration/common/mocks.c, tests/integration/common/mocks.h, tests/multithreaded/conn/rpma_conn_get_private_data.c, tests/multithreaded/conn/rpma_conn_req_new.c, tests/multithreaded/conn/server_rpma_conn_get_private_data.c, tests/multithreaded/ep/rpma_ep_get_fd.c, tests/multithreaded/ep/rpma_ep_listen.c, tests/multithreaded/mr/rpma_mr_get_descriptor.c, tests/multithreaded/mr/rpma_mr_get_ptr.c, tests/multithreaded/mr/rpma_mr_get_size.c, tests/multithreaded/mr/rpma_mr_reg.c, tests/multithreaded/peer/rpma_peer_new.c, tests/multithreaded/utils/rpma_utils_get_ibv_context.c, tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, tests/unit/common/mocks-ibverbs.c, tests/unit/common/mocks-ibverbs.h, tests/unit/common/mocks-rpma-cq.c, tests/unit/common/mocks-rpma-utils.c, tests/unit/utils/utils-get_ibv_context.c, tests/unit/utils/utils-ibv_context_is_odp_capable.c
ibv_context is referring by either ibv_ctx or ibv_ctx_ptr.
dev name is not used anywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1590)
=> rpma: ibv_context naming unification

.github/workflows/nightly_experimental.yml
There is still no official Docker image of CentOS Stream yet:
https://hub.docker.com/_/centos
and the unofficial one used so far (tgagor/centos:stream)
has stopped working, so we have to disable it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1599)
=> common: disable CentOS Stream CI build

src/include/librpma.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1602)
=> rpma: fix indentations in enum rpma_conn_event

CHANGELOG.md, src/log.c, tests/unit/common/mocks-rpma-log_default.c, tests/unit/log/CMakeLists.txt, tests/unit/log/macros.c, tests/unit/log/threshold.c
Fix `rpma_log_init()` - it cannot fail to set the default log function since now.
Fix unit tests of `rpma_log_set_threshold()` and `RPMA_LOG_*` macros.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1617)
=> rpma: fix rpma_log_init() and log's unit test

CHANGELOG.md, src/conn.c, src/include/librpma.h, src/rpma.c, tests/unit/conn/conn-next_event.c, tests/unit/utils/utils-conn_event_2str.c
RDMA_CM_EVENT_UNREACHABLE occurs sometimes in MT-tests.
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1606)
=> rpma: add RPMA_CONN_UNREACHABLE to handle RDMA_CM_EVENT_UNREACHABLE

tests/multithreaded/conn/CMakeLists.txt, tests/multithreaded/conn/rpma_conn_get_private_data.c
The client sometimes has to wait for the server to start listening,
so the client should retry to connect to the server several
times.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1604)
=> test: fix and enable the rpma_conn_get_private_data MT test

utils/docker/images/Dockerfile.opensuse-tumbleweed-latest
Install the 'shadow' package in OpenSUSE Tumbleweed,
because it contains the required command: 'useradd'.
Failed build: https://github.com/ldorau/rpma/runs/5644264113
Build with this fix: https://github.com/ldorau/rpma/actions/runs/2022470624
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1627)
=> common: install shadow package in OpenSUSE Tumbleweed

utils/docker/images/Dockerfile.vzlinux-latest
Apply the workaround (WA): temporarily do not verify SSL certificates in VzLinux,
because they have expired and the Docker image fails to rebuild:
```
Step 3/28 : RUN dnf update -y
Errors during downloading metadata for repository 'virtuozzolinux-base':
- Curl error (60): Peer certificate cannot be authenticated with \
given CA certificates for
https://repo.virtuozzo.com/vzlinux/mirrorlist/mirrors-8-os
[SSL certificate problem: certificate has expired]
Error: Failed to download metadata for repo 'virtuozzolinux-base': \
Cannot prepare internal mirrorlist: \
Curl error (60): Peer certificate cannot be authenticated with \
given CA certificates for \
https://repo.virtuozzo.com/vzlinux/mirrorlist/mirrors-8-os \
[SSL certificate problem: certificate has expired]
The command '/bin/sh -c dnf …
```
=> common: temporarily do not verify SSL certificates in VzLinux

utils/docker/images/Dockerfile.fedora-rawhide
Temporarily downgrade `python3-wrapt` in Fedora Rawhide
from v1.14.0 to v1.13.3-2 to fix the following error:
```
pkg_resources.ContextualVersionConflict: \
(wrapt 1.14.0 (/usr/lib64/python3.10/site-packages), \
Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})
```
Failed build: https://github.com/pmem/rpma/runs/5715501437
Build with this fix: https://github.com/ldorau/rpma/runs/5716445498
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1632)
=> common: temporarily downgrade python3-wrapt in Fedora Rawhide

tests/multithreaded/common/mtt_connect.c, tests/multithreaded/common/mtt_connect.h, tests/multithreaded/conn/CMakeLists.txt, tests/multithreaded/conn/rpma_conn_get_private_data.c, tests/multithreaded/conn/server_rpma_conn_get_private_data.c
Extract common connection code from `rpma_conn_get_private_data.c` for a future use.
This patch only refactors the code and does not make any functional modifications.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1635)
=> test: extract common code for MT tests

CHANGELOG.md, src/conn.c, src/conn.h, src/conn_cfg.c, src/conn_cfg.h, src/conn_req.c, src/cq.c, src/cq.h, src/include/librpma.h, src/librpma.map, src/rpma.c, src/rpma.h, src/rpma_err.c, tests/unit/common/mocks-rpma-conn.c, tests/unit/common/mocks-rpma-conn_cfg.c, tests/unit/common/mocks-rpma-cq.c, tests/unit/conn/conn-common.c, tests/unit/conn/conn-new.c, tests/unit/cq/cq-common.c, tests/unit/cq/cq-new_delete.c, tests/unit/error/error.c
Add the common completion channel, shared by CQ and RCQ.
Missing:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1637)
=> rpma: add shared completion channel

tests/unit/conn/conn-common.c, tests/unit/conn/conn-common.h, tests/unit/conn/conn-get_compl_fd.c, tests/unit/conn/conn-new.c, tests/unit/conn/conn-wait.c
Rename predefined structures:
- Conn_without_rcq to Conn_no_rcq_no_channel
- Conn_with_rcq to Conn_with_rcq_no_channel
- Conn_with_rcq_channel to Conn_with_rcq_and_channel
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1669)
=> test: rename predefined structures

examples/CMakeLists.txt
There is no `USE_LIBPMEM2_IF_FOUND` variable,
but there is only `USE_LIBPMEM_IF_FOUND` variable,
so we have to use `EXAMPLE_USE_LIBPMEM_IF_FOUND`
instead of `EXAMPLE_USE_LIBPMEM2_IF_FOUND` here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1690)
=> examples: fix EXAMPLE_USE_LIBPMEM_IF_FOUND variable in CMakeLists.txt

src/conn_req.c
It fixes the following valgrind issue:
```
==34690== Syscall param write(buf) points to uninitialised byte(s)
==34690==    at 0x497F1E7: write (write.c:26)
==34690==    by 0x4A893B4: rdma_resolve_addr2 (cma.c:961)
==34690==    by 0x4A89575: rdma_resolve_addr (cma.c:985)
==34690==    by 0x4854A84: rpma_info_resolve_addr (info.c:127)
==34690==    by 0x48520EC: rpma_conn_req_new (conn_req.c:421)
==34690==    by 0x1094BB: main (client.c:67)
==34690==  Address 0x1ffefff7ac is on thread 1's stack
==34690==  in frame #1, created by rdma_resolve_addr2 (cma.c:947)
==34690==
==34690== Syscall param write(buf) points to uninitialised byte(s)
==34690==    at 0x497F1E7: write (write.c:26)
==34690==    by 0x4A896A8: rdma_resolve_route (cma.c:1048)
==34690==    by 0x485210A: rpma_conn_req_new …
```
=> rpma: make timeout_ms always initialized (fix)

src/conn_req.c
It fixes the following valgrind issue:
```
==34306== Conditional jump or move depends on uninitialised value(s)
==34306==    at 0x4850FD6: rpma_conn_req_from_id (conn_req.c:96)
==34306==    by 0x48521A7: rpma_conn_req_new (conn_req.c:434)
==34306==    by 0x1094BB: main (client.c:67)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1688)
=> rpma: make shared always initialized (fix)

tests/unit/peer/peer-common.c, tests/unit/peer/peer-new.c
Roll back changes in teardown__peer() from 879ca10.
It fixes the following failed unit test on CentOS-7:
https://github.com/pmem/rpma/runs/6121538988
```
[ RUN      ] delete__dealloc_pd_ERRNO
[  FAILED  ] delete__dealloc_pd_ERRNO
[==========] tests: 12 test(s) run.
-- Stderr:
[  ERROR   ] --- Test failed with exception: Bus error(7)
[  PASSED  ] 11 test(s).
[  FAILED  ] tests: 1 test(s), listed below:
[  FAILED  ] delete__dealloc_pd_ERRNO
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1692)
=> test: fix the delete__dealloc_pd_ERRNO unit test

tests/unit/peer/peer-common.c, tests/unit/peer/peer-common.h, tests/unit/peer/peer-create_qp.c, tests/unit/peer/peer-mr_reg.c, tests/unit/peer/peer-new.c
Use `struct prestate` as an argument in both `setup__peer()`
and `teardown__peer()` instead of `in_out`.
Replace `setup__peer_prestates` with `setup__peer`
and `teardown__peer_prestates` with `teardown__peer`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1693)
=> test: change type of arguments of setup__peer() and teardown__peer()

src/log_internal.h
```
rpma/src/log_internal.h:38:9: error: implicit declaration of function \
‘rpma_log_default_function’
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1701)
=> rpma: include log_default.h in log_internal.h (fix)

tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c
Add rpma_mr_remote_delete() in the error handling path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1707)
=> test: fix error handling path of rpma_mr_remote_from_descriptor MT test

tests/multithreaded/common/mtt_connect.c, tests/multithreaded/common/mtt_connect.h, tests/multithreaded/conn/rpma_conn_get_private_data.c, tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c
Move `rpma_peer_new()` out of `mtt_client_connect()`
in order to enable creating multiple connections for one peer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1710)
=> test: move rpma_peer_new() out of mtt_client_connect()

src/conn_req.c, tests/unit/conn_req/conn_req-connect.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1727)
=> rpma: fix memory leak in error handling of rpma_conn_req_connect()

utils/docker/run-build.sh
The '-k' option is not needed and can be removed.
The '-S' option is used inside the function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1724)
=> common: fix usage of sudo_password

src/conn_req.c, src/ep.c, tests/unit/conn_req/conn_req-common.c, tests/unit/conn_req/conn_req-connect.c, tests/unit/conn_req/conn_req-delete.c, tests/unit/conn_req/conn_req-from_cm_event.c, tests/unit/conn_req/conn_req-private_data.c, tests/unit/ep/ep-common.c, tests/unit/ep/ep-next_conn_req.c
ACK the connection request event and free it
in `rpma_ep_next_conn_req()` and do not pass it
to the connection request. Use `is_passive` instead of `edata`
to distinguish between active and passive side.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1703)
=> rpma: ack the connection request event in rpma_ep_next_conn_req()

tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c
Running multithreaded rpma_mr_remote_from_descriptor test
built with -fsanitize=address detects memory leaks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1729)
=> test: fix memory leaks for rpma_mr_remote_from_descriptor

cmake/functions.cmake
CHECK_C_SOURCE_COMPILES() is used to check if the provided
<code> argument can be compiled successfully. So we don't
need to set different return values for main().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1722)
=> common: simplfy CHECK_C_SOURCE_COMPILES()'s <code> argument

examples/08-messages-ping-pong/server.c
It fixes the following valgrind error when `rpma_conn_req_connect()` fails:
```
==34021== 144 (64 direct, 80 indirect) bytes in 1 blocks are definitely lost in loss record 9 of 22
==34021==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==34021==    by 0x48516A8: rpma_conn_req_from_id (conn_req.c:123)
==34021==    by 0x485232F: rpma_conn_req_from_cm_event (conn_req.c:352)
==34021==    by 0x48548FA: rpma_ep_next_conn_req (ep.c:217)
==34021==    by 0x10A708: main (server.c:79)
==34021==
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1738)
=> examples: fix memory leak in example 08

examples/08-messages-ping-pong/messages-ping-pong-common.c
It fixes the following valgrind error, when `rpma_cq_get_wc()` fails with `RPMA_E_NO_COMPLETION`:
```
==32483== Conditional jump or move depends on uninitialised value(s)
==32483==    at 0x10B053: wait_and_process_completions \
(messages-ping-pong-common.c:66)
==32483==    by 0x10A89D: main (client.c:121)
==32483==
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1739)
=> examples: fix error handling in example 08

examples/08-messages-ping-pong/messages-ping-pong-common.c
`rpma_cq_get_wc()` should not return `RPMA_E_NO_COMPLETION` when it is run in the current loop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1741)
=> examples: fix wait_and_process_completions() in example 08

src/log_default.c, tests/unit/log_default/function.c
It fixes 3 Klocwork issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1752)
=> rpma: make conditions of logging in rpma_log_default_function more clear

THREAD_SAFETY.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1774)
=> rpma: only one librpma API call is not thread-safe

utils/docker/build.sh
It was tested on the devel branch: https://github.com/pmem/rpma/pull/1778
The following build:
https://github.com/pmem/rpma/runs/6624424359
did not trigger the automatic documentation update, what proves that this fix is correct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1780)
=> common: doc update should be run only on the master branch (fix)

utils/docker/prepare-for-build.sh
This is fix for: https://github.com/actions/checkout/issues/766 (git CVE-2022-24765)
```
fatal: unsafe repository ('/rpma' is owned by someone else)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1782)
=> common: set WORKDIR as a safe directory

utils/docker/images/install-archlinux-aur.sh, utils/docker/prepare-for-build.sh
It fixes the following warning:
```sh
chown: warning: '.' should be ':': ‘user.user’
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1753)
=> common: fix chown command on Arch Linux

utils/docker/images/Dockerfile.archlinux-latest, utils/docker/images/install-pmdk.sh, utils/docker/prepare-for-build.sh
It fixes the following error during compilation of PMDK:
```
../../src/../src/libpmem2/region_namespace_ndctl.c:9:10: \
fatal error: ndctl/libdaxctl.h: No such file or directory
9 | #include <ndctl/libdaxctl.h>
|          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1754)
=> common: install PMDK from sources instead of AUR on Arch Linux

.circleci/install-pkgs-ubuntu.sh
Add --allow-unauthenticated to apt-get in CircleCI.
It skips the GPG signature checks of apt on Ubuntu
and bypasses the errors while installing packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1793)
=> common: add --allow-unauthenticated to apt-get in CircleCI

THREAD_SAFETY.md
Five more functions are not thread-safe:
- rpma_ep_listen
- rpma_ep_next_conn_req
- rpma_ep_shutdown
- rpma_mr_reg
- rpma_mr_dereg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1798)
=> rpma: five more functions are not thread-safe

utils/docker/images/Dockerfile.opensuse-tumbleweed-latest
openSUSE Tumbleweed has been fixed, remove the workaround:
Ref: a3486883cfc333ba193cecdbe51aa86116e87413
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1806)
=> common: openSUSE Tumbleweed has been fixed, remove workaround

tests/multithreaded/run_group.cmake
It works just "out-of-box" now:
- https://app.circleci.com/pipelines/github/ldorau/rpma/4055/workflows/3875a8cf-a028-4203-bca3-4bf3c3a8507b/jobs/4122
- https://app.circleci.com/pipelines/github/ldorau/rpma/4056/workflows/4498f3c9-ad1f-4128-b88b-5ffd1527659f/jobs/4123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1807)
=> test: revert running 32 threads in MT tests

utils/docker/prepare-for-build.sh
WORKDIR has to be set as a safe directory always (not only on CIs),
because this issue occurs everywhere.
Ref: 69ac575c
Ref: dec98f68
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1819)
=> common: always set WORKDIR as a safe directory

examples/run-all-examples.sh
Do not wait additional 1 sec for running server.
This will reduce duration of the integration test by
1008 seconds what is about 17 minutes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1821)
=> examples: do not wait additional 1 sec for running server

utils/docker/images/Dockerfile.opensuse-leap-latest
Fix the CI build of openSUSE Leap by adding the python3 package.
Failed build: https://github.com/pmem/rpma/runs/6853969337
There is no python36 package:
https://github.com/ldorau/rpma/runs/6858757885
The build with the fix:
https://github.com/ldorau/rpma/runs/6858837416
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1829)
=> common: add python3 to openSUSE Leap Docker image (fix)

tests/multithreaded/common/mtt.c
Increase timeout for pthread_cond_timedwait() to 60 seconds, because the error:
```
mtt.c:80 mtt_thread_main() -> pthread_cond_timedwait() failed: Connection timed out
```
still occurs:
https://app.circleci.com/pipelines/github/haichangsi/rpma/61/workflows/a241ab1b-5230-4a75-b4f1-3a3ae2b91005/jobs/61
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1830)
=> test: increase timeout for pthread_cond_timedwait() to 60 seconds

src/conn.c
It fixes the following fault-injection error:
```
==378809== Conditional jump or move depends on uninitialised value(s)
==378809==    at 0x4E46584: rpma_flush (conn.c:555)
==378809==    by 0x4021E8: main (client.c:182)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1852)
=> rpma: initialize flush_type to prevent a fault-injection error

src/log_default.c, tests/drd.supp, tests/helgrind.supp, tests/unit/common/mocks-time.c, tests/unit/log_default/CMakeLists.txt, tests/unit/log_default/function.c
Replace localtime() with localtime_r() in rpma_get_timestamp_prefix(),
because:
- localtime_r() has "MT-Safe env locale" attributes(7),
while
- localtime() has "MT-Unsafe race:tmbuf env locale" attributes(7).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1859)
=> rpma: replace localtime() with localtime_r()

CMakeLists.txt, cmake/functions.cmake, tests/cmake/ctest_helpers.cmake
The 'valgrind -s date' command can fail also because of valgrind
issues in the 'date' command, not only because of unknown '-s' option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1866)
=> test: fix checking if valgrind -s option is supported

tests/multithreaded/common/mtt.c, tests/multithreaded/common/mtt.h
Postpone starting the child process after starting
and unblocking the threads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1933)
=> test: postpone starting the child process in MT tests

utils/docker/prepare-for-build.sh
Replace the old syntax:
```sh
$ chown [OWNER][.[GROUP]]
```
with the new one:
```sh
$ chown [OWNER][:[GROUP]]
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1935)
=> common: replace dot with colon in chown

.github/workflows/nightly.yml
Temporarily disable testing performance tools on OpenSUSE Tumbleweed
due to the following issue:
https://github.com/ldorau/rpma/runs/7464261110?check_suite_focus=true#step:4:1390
```
Traceback (most recent call last):
File "/home/user/.local/bin/coverage", line 5, in <module>
from coverage.cmdline import main
File "/home/user/.local/lib/python3.10/site-packages/coverage/__init__.py", line 15, in <module>
from coverage.control import Coverage, process_startup
File "/home/user/.local/lib/python3.10/site-packages/coverage/control.py", line 23, in <module>
from coverage.data import CoverageData, combine_parallel_data
File "/home/user/.local/lib/python3.10/site-packages/coverage/data.py", line 18, in <module>
from coverage.sqldata import CoverageData
File …
```
=> common: disable testing performance tools on OpenSUSE Tumbleweed

src/conn_cfg.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1936)
=> rpma: remove redundant _Atomic declaration in the rpma_conn_cfg struct

src/log.c
rpma_log_set_threshold() should use rpma_log_get_threshold()
to get the current value of threshold.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1948)
=> rpma: use rpma_log_get_threshold() in rpma_log_set_threshold() (fix)

src/conn_cfg.c
_Atomic declarations are required to ensure the alignment requirements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1949)
=> rpma: add missing _Atomic declarations (fix)

CHANGELOG.md, src/log.c, src/log_internal.h, tests/multithreaded/log/CMakeLists.txt, tests/multithreaded/log/rpma_log_set_threshold.c, tests/unit/common/mocks-rpma-log.c
Add a mtt test for rpma_log_set_threshold.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1951)
=> rpma: make rpma_log_set_threshold() thread-safe

examples/CMakeLists.txt
This reverts commit f2a9efbfdbc0ed3a720d9364f01e640449253afc.
All examples have support for libpmem2 now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1960)
=> Revert "examples: fix building examples with libpmem"

examples/08-messages-ping-pong/README.md, examples/08-messages-ping-pong/client.c
Remove the `#` character (a comment?), because the last argument
of the client can be an optional `<sleep>` expressed in microseconds:
```sh
$ client <server_address> <port> <seed> <rounds> [<sleep>]
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1967)
=> examples: fix the client command in README of example 08

.circleci/install-pkgs-ubuntu.sh
Set `DEBIAN_FRONTEND` to `noninteractive` in CircleCI.
It fixes the CircleCI build stopping at the question:
```
Restarting services...
Package configuration
Daemons using outdated libraries
Which services should be restarted?
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1972)
=> common: set DEBIAN_FRONTEND=noninteractive in CircleCI

examples/08-messages-ping-pong/messages-ping-pong-common.c
When rpma_cq_wait() gets a completion event and rpma_cq_get_wc()
retrieves two completions, it is possible that rpma_cq_wait()
can get another completion event successfully but rpma_cq_get_wc()
returns RPMA_E_NO_COMPLETION in the next loop.
The RPMA_E_NO_COMPLETION breaks wait_and_process_completions() and
make 08-messages-ping-pong end too early on real RDMA HW. For example:
```sh
$ ./examples/08-messages-ping-pong/client 192.168.1.11 8765 1 5
...
... rpma_conn_req_new: Requesting a connection to 192.168.1.11:8765
... rpma_conn_next_event: Connection established
Value sent: 1
Value received: 2
Value sent: 2
... rpma_conn_disconnect: Requesting for disconnection
... rpma_conn_next_event: Connection closed
```
- - -
This change is [<img …
=> examples: continue when rpma_cq_get_wc() returns RPMA_E_NO_COMPLETION

src/cq.c
Fault injection cannot falsify the results of `rpma_cq_get_wc()`,
because the application can hang on waiting for the next completion.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1975)
=> rpma: fault injection cannot falsify the results of rpma_cq_get_wc()

src/conn_cfg.c
RPMA_FAULT_INJECTION() in rpma_conn_cfg_get_compl_channel()
should be moved just before 'return 0' because the function
is used as void in rpma_conn_req_from_id().
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1980)
=> rpma: move RPMA_FAULT_INJECTION() in rpma_conn_cfg_get_compl_channel()

src/conn_cfg.c
`rpma_conn_cfg_get_timeout()` has to always return the correct value,
even in case of fault injection, because it is called
as "`void`" in `rpma_conn_req_new()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1982)
=> rpma: rpma_conn_cfg_get_timeout() has to return correct value

src/srq_cfg.c
Fault injection has to be located after freeing all resources.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1988)
=> rpma: fix fault injection in rpma_srq_cfg_delete()

examples/08srq-simple-messages-ping-pong-with-srq/README.md, examples/08srq-simple-messages-ping-pong-with-srq/server.c
expand 08srq-simple-messages-ping-pong-with-srq so that it can
get receive completions by one of the following CQs:
- the receive CQ of the shared RQ
- the main CQ of the connection
- the separate receive CQ of the connection
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1985)
=> examples: expand 08srq-simple-messages-ping-pong-with-srq

src/include/librpma.h
"\f[B]Direct Write to PMem\f[R]" has to be in one line.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1996)
=> doc: fix bolding Direct Write to PMem

utils/src2mans.sh
Replace `\fP` with `\fR` in groff manuals,
because pandoc does not interpret `\fP` correctly
and generates incorrect markdown files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1998)
=> common: replace \fP with \fR in groff manuals

DEVELOPMENT.md
`CMAKE_BUILD_TYPE` must be set to `Debug` when running the tests, because the tests runs valgrind with suppressions that require debug symbols.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2028)
=> doc: running tests requires CMAKE_BUILD_TYPE set to Debug

CHANGELOG.md, utils/docker/images/Dockerfile.fedora-rawhide
Fix the rebuild of Fedora Rawhide by installing the python3-devel package.
See failed builds: https://github.com/pmem/rpma/actions/workflows/nightly_experimental.yml
See the build with this fix: https://github.com/ldorau/rpma/runs/8299831697?check_suite_focus=true
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2029)
=> common: install python3-devel in Fedora Rawhide (fix)

CHANGELOG.md, utils/docker/run-build.sh
Use `cmake3` instead of `cmake` if a version of `cmake` is v2.x, because the minimum required version of `cmake` is 3.3.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2034)
=> common: use cmake3 if cmake is v2.x

CHANGELOG.md, utils/check_license/check-headers.sh
fix the following error when running 'make check-license': 
---------------------------------------------------------
Checking copyright headers of all files...
../utils/check_license/check-headers.sh: line 191: \
../utils/check_license/check-ms-license.pl: No such file or directory
...
---------------------------------------------------------
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2035)
=> common: correct the path of check-ms-license.pl

CHANGELOG.md, src/include/librpma.h
Add security warnings to the documentation
of the following functions of the API:
- rpma_conn_get_private_data()
- rpma_conn_req_get_private_data()
- rpma_mr_get_descriptor()
- rpma_mr_remote_from_descriptor()
- rpma_peer_cfg_from_descriptor()
- rpma_peer_cfg_get_descriptor()
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2040)
=> rpma: add security warnings to librpma.h

CHANGELOG.md, utils/check_license/check-headers.sh
It silents the following warnings:
```
grep: warning: * at start of expression
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2042)
=> common: remove unneeded '*' at start of expression

CHANGELOG.md, examples/03-read-to-persistent/client.c, examples/03-read-to-persistent/server.c, examples/04-write-to-persistent/client.c, examples/04-write-to-persistent/server.c, examples/05-flush-to-persistent/client.c, examples/05-flush-to-persistent/server.c, examples/09-flush-to-persistent-GPSPM/client.c, examples/09-flush-to-persistent-GPSPM/server.c, examples/09scch-flush-to-persistent-GPSPM/client.c, examples/09scch-flush-to-persistent-GPSPM/server.c, examples/common/common-hello.c, examples/common/common-hello.h, examples/common/common-map_file_with_signature_check.c, examples/common/common-map_file_with_signature_check.h
Do not use 0 size when mapping PMem.
A size of PMem should be set explicitly.
Add to common_pmem_map_file_with_signature_check()
a function pointer argument to a function writing the initial data to PMem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2048)
=> examples: do not use 0 size when mapping PMem

CHANGELOG.md, examples/13-messages-ping-pong-with-srq/server.c
Fix detecting no free slot for a new connection request in example 13.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2062)
=> examples: fix detecting no free slot for a new connection request

examples/03-read-to-persistent/server.c
Do not overwrite the previous errors (ret = -1)
set when `(wc.status != IBV_WC_SUCCESS)` or `(wc.opcode != IBV_WC_RDMA_READ)`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2061)
=> examples: do not overwrite the previous errors

utils/docker/run-coverity.sh
`COVERITY_SCAN_PROJECT_NAME` should be "librpma", not "$CI_REPO_SLUG".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2066)
=> common: fix COVERITY_SCAN_PROJECT_NAME

src/peer.c, tests/drd.supp, tests/memcheck-libibverbs-librdmacm.supp, tests/unit/common/mocks-rdma_cm.c, tests/unit/peer/peer-create_qp.c
1) Make rpma_peer_setup_qp() call rdma_create_qp_ex().
2) Update the related unit tests.
3) Update suppresions for the rdma_create_qp_ex().
This change is to prepare for new libibverbs flush and atomic write.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2084)
=> rpma: replace rdma_create_qp() with rdma_create_qp_ex()

CHANGELOG.md, tests/multithreaded/common/mtt_connect.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2087)
=> test: add sleep(1) to mtt_client_connect() before the next retry

.github/workflows/on_pull_request.yml, CHANGELOG.md
Remove Debian 10 from the on_pull_request CI workflow.
Debian 10 is a representative of OSes that have
different behavior of the pytest bad-whitespace error (C0326) (see commit 48f8068330c2be1743c77707a8956f6ea805fa7e), but we do not use pytest any more, so remove it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2088)
=> common: remove Debian 10 from the on_pull_request CI workflow

CHANGELOG.md, utils/docker/build.sh, utils/docker/run-build.sh, utils/docker/run-doc-update.sh
Introduce a possibility to verify if the changed documentation
is correctly formatted before merging it upstream.
If $AUTO_DOC_UPDATE == "1" then pull requests
with the generated documentation are created
only on $GITHUB_REPO and only on the main branch,
otherwise the git diff is printed out to be able
to verify if the new changes in the documentation
are correct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2096)
=> common: show git diff of the generated documentation

CMakeLists.txt, cmake/functions.cmake, src/mr.c, src/peer.c, src/utils.c, tests/unit/common/mocks-ibverbs.c, tests/unit/common/mocks-ibverbs.h, tests/unit/common/mocks-rdma_cm.c, tests/unit/mr/mr-atomic_write.c, tests/unit/peer/peer-create_qp.c, tests/unit/utils/utils-ibv_context_is_atomic_write_capable.c
Both IBV_WR_ATOMIC_WRITE_SUPPORTED and is_ibv_wr_atomic_write_supported() are used to check if libibverbs supports the whole native atomic write instead of ibv_wr_atomic_write() so rename them to the following names: 1) IBV_WR_ATOMIC_WRITE_SUPPORTED => NATIVE_ATOMIC_WRITE_SUPPORTED 2) is_ibv_wr_atomic_write_supported() => is_ibv_atomic_write_supported()
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2103)
=> common: rename atomic write macro and function

tests/unit/common/mocks-ibverbs.c, tests/unit/common/mocks-ibverbs.h
When ON_DEMAND_PAGING_SUPPORTED is false and NATIVE_ATOMIC_WRITE_SUPPORTED is true, the following compiler error will be triggered: 
...
error: 'ibv_query_device_ex_mock' undeclared (first use in this function);
did you mean 'ibv_query_device_ex'?
...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2106)
=> test: fix the "ibv_query_device_ex_mock undeclared" compiler error

utils/docker/images/Dockerfile.rockylinux-8, utils/docker/images/Dockerfile.rockylinux-9, utils/docker/images/install-pmdk.sh
Install a newer PMDK with fixes required for Rocky Linux 8 and 9.
Ref: https://github.com/pmem/pmdk/issues/5540
Ref: https://github.com/pmem/rpma/pull/2109
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2112)
=> common: install a newer PMDK with required fixes

utils/docker/images/Dockerfile.archlinux-latest, utils/docker/images/Dockerfile.vzlinux-latest
Add missing PMDK dependencies to Arch Linux and VzLinux docker files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2115)
=> common: add missing PMDK dependencies to docker files

utils/docker/run-build.sh
Fix preventing from failing the build when `rpm -q` or `dpkg-deb` fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2121)
=> common: do not fail build when rpm -q fails

.github/workflows/on_pull_request.yml, utils/docker/images/Dockerfile.fedora-latest-with-rdma-core-45, utils/docker/images/Dockerfile.ubuntu-latest-with-rdma-core-45, utils/docker/images/install-rdma-core.sh
Add CI builds with rdma-core v44.0 installed from sources
(with support for both native atomic write and native flush)
on Ubuntu-latest and Fedora-latest CIs.
Requires:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2119)
=> common: add builds with rdma-core v44.0 on Ubuntu and Fedora CIs

CHANGELOG.md, CMakeLists.txt, examples/01-connection/CMakeLists.txt, examples/02-read-to-volatile/CMakeLists.txt, examples/03-read-to-persistent/CMakeLists.txt, examples/04-write-to-persistent/CMakeLists.txt, examples/05-flush-to-persistent/CMakeLists.txt, examples/06-multiple-connections/CMakeLists.txt, examples/06scch-multiple-connections/CMakeLists.txt, examples/07-atomic-write/CMakeLists.txt, examples/08-messages-ping-pong/CMakeLists.txt, examples/08srq-simple-messages-ping-pong-with-srq/CMakeLists.txt, examples/09-flush-to-persistent-GPSPM/CMakeLists.txt, examples/09scch-flush-to-persistent-GPSPM/CMakeLists.txt, examples/10-send-with-imm/CMakeLists.txt, examples/11-write-with-imm/CMakeLists.txt, examples/12-receive-completion-queue/CMakeLists.txt, examples/12scch-receive-completion-queue/CMakeLists.txt, examples/13-messages-ping-pong-with-srq/CMakeLists.txt, examples/cmake/common.cmake
Update cmake_minimum_required version from 3.3 to 3.5, because of:
```
CMake Deprecation Warning at CMakeLists.txt:7 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2136)
=> test: update cmake_minimum_required version from 3.3 to 3.5
