README.md

Tomasz Gromaszki -> Tomasz Gromadzki
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2)

common: fix typo in name

---

utils/check-area.sh
utils/check-commit.sh

check-area.sh is called by utils/check-commit.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/5)

common: add missing check-area.sh script

---

tests/test_backtrace.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/6)

test: remove __cplusplus ifdefs

---

CMakeLists.txt
src/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/8)

common: add FAULT_INJECTION option to compile

---

utils/docker/images/install-pmdk.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/11)

common: fix installing libpmem2 from sources

---

utils/check-commits.sh
utils/docker/build.sh
utils/docker/images/push-image.sh
utils/docker/pull-or-rebuild-image.sh
utils/docker/run-coverity.sh
utils/docker/run-doc-update.sh
utils/docker/set-ci-vars.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/9)

common: unify code for Travis and GitHub Actions CIs

---

utils/docker/images/Dockerfile.fedora-31
utils/docker/images/Dockerfile.ubuntu-19.10

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/12)

common: add missing packages to Docker images

---

src/CMakeLists.txt
src/common/alloc.c
src/common/alloc.h
src/common/fault_injection.h
src/common/out.h
src/common/util.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/4)

common: add common

---

utils/check_license/check-headers.sh
utils/check_license/check-ms-license.pl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/14)

common: import check-ms-license.pl from PMDK

---

utils/docker/build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/15)

common: pass missing variables to Docker

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/13)

rpma: add public RPMA headers

---

cmake/functions.cmake
utils/cstyle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/16)

common: make cstyle recognizes src2man block comments

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/25)

doc: update contact info

---

src/common/out.h
src/common/util.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/24)

common: replace strings PMDK with RPMA in common files

---

CMakeLists.txt
examples/CMakeLists.txt
examples/template-example/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/23)

common: set LIBRPMA_ directories

---

utils/docker/images/Dockerfile.ubuntu-19.10

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/21)

common: add curl package needed by Coverage and Coverity builds

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/26)

rpma: update to public RPMA headers

---

src/CMakeLists.txt
src/librpma.map
src/rpma.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/28)

rpma: add empty functions

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/31)

common: Reference to RPMEM over traditional RDMA added.

---

examples/CMakeLists.txt
examples/connection/CMakeLists.txt
examples/connection/README.md
examples/connection/connection-client.c
examples/connection/connection-server.c
src/include/librpma.h
src/librpma.map
src/rpma.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/29)

examples: connection + rpma_conn_req

---

README.md
_data/libs_map.yml
_data/releases_linux.yml
_includes/pagefooter.html
_layouts/manual.html
_layouts/pmdk.html
index.md
master/librpma.7.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/30)

doc: web page skeleton

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/33)

doc: add build to .gitignore

---

utils/docker/run-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/36)

common: enable running utils/docker/run-build.sh locally

---

examples/connection/CMakeLists.txt
examples/template-example/CMakeLists.txt
utils/docker/run-build.sh

Fixes: #32 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/37)

common: test standalone compilation of all examples

---

utils/docker/images/Dockerfile.fedora-31
utils/docker/images/Dockerfile.ubuntu-19.10
utils/docker/images/install-cmocka.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/39)

common: install cmocka in Docker images

---

tests/cmake/ctest_helpers.cmake
tests/cmocka_headers.h
tests/template-test/template-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/41)

test: use cmocka in the template test

---

tests/cmake/ctest_helpers.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/43)

test: particularise message about libunwind

---

utils/docker/images/Dockerfile.fedora-31
utils/docker/images/Dockerfile.ubuntu-19.10
utils/docker/images/patch-src2man.sh

Patch src2man to fix the following bug:
https://github.com/mvertes/txt2man/issues/23
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/47)

common: patch src2man in Docker images

---

utils/src2mans.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/45)

common: fix one sed command in src2mans.sh

---

doc/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/48)

doc: add requirement for groff

---

utils/src2mans.sh

It is a continuation of 2c48229.
Starting from 2c48229 src2man prints out names of manuals to stdout
and gawk's warnings and errors to stderr.
Redirect stdout and stderr of src2man to two different files,
so that messages do not get mixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/49)

common: redirect stdout and stderr of src2man to two different files

---

src/include/librpma.h

The NAME section must be on a single line. Longer comments are temporarily moved to the DESCRIPTION section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/51)

rpma: update comments to manual

---

utils/src2mans.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/54)

common: ignore warnings of src2man

---

CMakeLists.txt
tests/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/52)

common: move setting most CFLAGs from tests to main CMake file

---

CMakeLists.txt
src/CMakeLists.txt
src/common/out.c
src/common/util.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/53)

common: add out.c and util.c to commons

---

CMakeLists.txt
examples/connection/connection-client.c
examples/connection/connection-server.c
src/CMakeLists.txt
src/common/cmocka_alloc.h
src/include/librpma.h
src/peer.c
src/rpma.c
tests/CMakeLists.txt
tests/cmake/ctest_helpers.cmake
tests/peer-test/peer-test.c
tests/peer-test/peer-test_0.cmake

Requires:
WIP:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/35)

rpma: add peer implementation

---

LICENSE
utils/docker/images/Dockerfile.fedora-31
utils/docker/images/Dockerfile.ubuntu-19.10
utils/docker/images/patch-txt2man.sh
utils/docker/images/txt2man.patch

Patch txt2man with:
https://github.com/mvertes/txt2man/pull/18
to fix the following bug:
https://github.com/mvertes/txt2man/issues/21
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/55)

common: patch txt2man in Docker images

---

src/CMakeLists.txt
src/ep.c
src/rpma.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/59)

rpma: endpoint pre-implementation cleanup

---

tests/peer-test/peer-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/60)

test: fix code alignment in peer-test

---

src/common/out.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/58)

common: replace PMDK_LOG_ALIGN with RPMA_LOG_ALIGN

---

src/include/librpma.h
src/rpma.c
tests/CMakeLists.txt
tests/utils-test/utils-test.c
tests/utils-test/utils-test_0.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/50)

rpma: add rpma_utils_get_ibv_context()

---

src/include/librpma.h
src/peer.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/62)

rpma: small peer fixes

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/64)

rpma: fix manual of rpma_peer_new()

---

src/CMakeLists.txt
src/conn.c
src/conn.h
src/conn_req.c
src/conn_req.h
src/ep.c
src/info.c
src/info.h
src/peer.c
src/peer.h
src/rpma.c
src/rpma_err.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/61)

rpma: initial modules structure

---

tests/CMakeLists.txt
tests/cmake/ctest_helpers.cmake
tests/peer-test/CMakeLists.txt
tests/template-test/CMakeLists.txt
tests/utils-test/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/65)

test: add a separate CMakeLists file for each test

---

src/conn_req.h
src/info.c
src/info.h
tests/CMakeLists.txt
tests/info-test/CMakeLists.txt
tests/info-test/info-test.c
tests/peer-test/CMakeLists.txt

Requires:
WIP:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/63)

rpma: info module

---

tests/peer-test/peer-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/69)

test: add test for rpma_peer_create_qp()

---

examples/connection/connection-client.c
examples/connection/connection-server.c
src/conn.c
src/conn_req.c
src/include/librpma.h
src/librpma.map

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/75)

common: allow passing any private data on conn setup

---

src/info.c
src/info.h
tests/info-test/info-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/79)

rpma: rpma_info_new() has to accept NULL service

---

tests/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/81)

test: sort unit tests alphabetically

---

src/ep.c
src/include/librpma.h
tests/CMakeLists.txt
tests/ep-test/CMakeLists.txt
tests/ep-test/ep-test.c

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/68)

rpma: ep implementation & unit tests

---

src/include/librpma.h
src/rpma.c
tests/utils-test/CMakeLists.txt
tests/utils-test/utils-test.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/80)

rpma: use info module in rpma_utils_get_ibv_context()

---

src/conn_req.h
src/peer.c
src/peer.h
tests/peer-test/peer-test.c

- rpma_peer_create_qp() implementation & unit tests
- new conn_req.h defines:
-- RPMA_DEFAULT_Q_SIZE
-- RPMA_MAX_SGE
-- RPMA_MAX_INLINE_DATA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/83)

common: implement & test rpma_peer_create_qp()

---

src/conn.c
src/conn.h
src/include/librpma.h
tests/CMakeLists.txt
tests/conn-test/CMakeLists.txt
tests/conn-test/conn-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/84)

rpma: conn implementation & unit tests

---

src/include/librpma.h
src/rpma.c
tests/utils-test/utils-test.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/66)

rpma: resolve address for use on active side of connection

---

examples/connection/connection-client.c
examples/connection/connection-server.c
src/conn.c
src/conn_req.c
src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/92)

common: combine ptr and len into rpma_conn_private_data

---

src/conn_req.c
src/include/librpma.h
tests/conn_req-test/conn_req-test.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/91)

rpma: add rpma_conn_req_new()

---

src/conn.h
src/conn_req.c
src/include/librpma.h
tests/conn_req-test/conn_req-test.c

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/90)

 rpma: rpma_conn_req_connect() implementation & unit tests

---

src/conn.c
src/include/librpma.h
tests/conn-test/conn-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/93)

rpma: add rpma_conn_next_event()

---

src/conn.c
src/include/librpma.h
tests/conn-test/conn-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/95)

rpma: add rpma_conn_disconnect()

---

src/conn.c
src/include/librpma.h
tests/conn-test/conn-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/96)

rpma: add cases in rpma_conn_next_event()

---

tests/conn_req-test/conn_req-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/102)

rpma: add missing tests

---

tests/error-test/error-test.c
tests/utils-test/utils-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/105)

rpma: add missing tests (error and utils)

---

src/private_data.c
src/private_data.h
tests/private_data-test/private_data-test.c

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/110)

rpma: private_data_copy

---

src/conn.c
src/conn.h
src/conn_req.c
src/conn_req.h
src/include/librpma.h
tests/conn-test/conn-test.c
tests/conn_req-test/conn_req-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/109)

rpma: use the private data module

---

src/private_data.c
src/private_data.h

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/111)

rpma: private data (assumptions)

---

examples/connection/connection-client.c
examples/connection/connection-server.c

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/106)

examples: pass private data in the connection example

---

src/conn.c
src/private_data.c
src/private_data.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/112)

rpma: private data fixes

---

examples/connection/connection-server.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/113)

examples: message on waiting for incoming connections

---

tests/conn-test/conn-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/114)

test: add more tests for private data

---

.github/workflows/gha.yml
.travis.yml
utils/docker/build.sh
utils/docker/run-doc-update.sh

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/76)

common: run automatic gh-pages docs update on GHA instead of Travis

---

tests/conn-test/conn-test.c
tests/conn_req-test/conn_req-test.c
tests/ep-test/ep-test.c
tests/info-test/info-test.c
tests/peer-test/peer-test.c

If I see NO_ERROR, my first thought is "an error occurred".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/104)

test: replace string NO_ERROR with SUCCESS

---

tests/conn-test/conn-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/116)

test: unify teardown functions in the conn-test unit test

---

src/peer.c
src/peer.h
tests/peer-test/peer-test.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/118)

 rpma: implement rpma_peer_mr_reg() and its unit tests

---

tests/conn-test/conn-test.c
tests/conn_req-test/conn_req-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/121)

test: add missing assert to mock of rpma_private_data_store()

---

src/include/librpma.h
src/librpma.map
src/mr.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/120)

rpma: scaffolding of mr, _read and _conn_next_completion (part 2)

---

src/peer.c
tests/peer-test/peer-test.c
utils/cstyle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/123)

common: make cstyle allow long line if it is an URL

---

tests/utils-test/utils-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/129)

test: add two missing comments to utils-test

---

src/conn.c
src/include/librpma.h
tests/conn-test/conn-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/131)

rpma: implement rpma_read() and its unit tests

---

utils/cstyle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/132)

common: error out on extra space before or after ++/-- operators

---

tests/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/135)

test: if COVERAGE then do not run examples (WA)

---

src/include/librpma.h
src/mr.c
tests/example-01-client/example-01-client.c
tests/mr-test/mr-test.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/124)

rpma: implement rpma_mr_reg()/rpma_mr_dereg() and their unit tests

---

src/mr.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/144)

rpma: two minor changes in mr.c

---

src/mr.c
src/mr.h
tests/mr-test/CMakeLists.txt
tests/mr-test/mr-test-common.c
tests/mr-test/mr-test-common.h
tests/mr-test/mr-test-descriptor.c
tests/mr-test/mr-test-read.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/137)

rpma: implement rpma_mr_read() and its unit tests

---

examples/02-read-to-volatile/server.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/145)

examples: 02 add missing private data length

---

tests/conn-test/conn-test-common.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/141)

test: add missing asserts to mock of rpma_mr_read() in conn-test

---

tests/conn-test/conn-test-disconnect.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/143)

test: fix one errno check

---

tests/cmocka_headers.h
tests/conn-test/CMakeLists.txt
tests/conn-test/conn-test-common.h
tests/conn-test/conn-test-disconnect.c
tests/conn-test/conn-test-new.c
tests/conn-test/conn-test-next-completion.c
tests/conn-test/conn-test-next-event.c
tests/conn-test/conn-test-private-data.c
tests/conn-test/conn-test-read.c
tests/conn-test/conn-test.c
tests/mr-test/CMakeLists.txt
tests/mr-test/mr-test-common.h
tests/mr-test/mr-test-descriptor.c
tests/mr-test/mr-test-read.c
tests/mr-test/mr-test-reg.c
tests/mr-test/mr-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/148)

test: group conn and mr unit tests

---

examples/01-connection/server.c
tests/CMakeLists.txt
tests/example-01-connection/CMakeLists.txt
tests/example-01-connection/example-01-connection.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/140)

rpma: add integration test, example connection server

---

examples/02-read-to-volatile/client.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/154)

examples: fix one print_error() message

---

src/conn.c
src/include/librpma.h
src/librpma.map
src/mr.c
src/mr.h
tests/unit/conn-test/CMakeLists.txt
tests/unit/conn-test/conn-test-write.c
tests/unit/conn-test/conn-test.c
tests/unit/mr-test/CMakeLists.txt
tests/unit/mr-test/mr-test-write.c
tests/unit/mr-test/mr-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/152)

common: scaffolding of rpma_write()

---

tests/unit/private_data-test/private_data-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/155)

test: fix indentation

---

examples/02-read-to-volatile/client.c
examples/02-read-to-volatile/server.c
examples/CMakeLists.txt
examples/common/common.c
examples/common/common.h

- make add_example cmake function more flexible
- allow arbitrarily picking disconnection initiative (the examples common)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/158)

examples: preparing the ground for coming examples

---

src/mr.c
tests/unit/mr-test/mr-test-read.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/161)

common: set wr.next to NULL

---

examples/CMakeLists.txt
examples/log/README.md
examples/log/log-example.c
examples/log/log-worker.c
src/CMakeLists.txt
src/include/librpma_log.h
src/librpma.map
src/log.c
src/log_internal.h

This is a logging mechanism for the librpma library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/107)

common: log implementation based on SPDK

---

src/conn.c
tests/unit/conn-test/conn-test-common.c
tests/unit/conn-test/conn-test-common.h
tests/unit/conn-test/conn-test-read.c
tests/unit/conn-test/conn-test-write.c
tests/unit/conn-test/conn-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/165)

rpma: implement rpma_write() and unit tests

---

CMakeLists.txt
examples/CMakeLists.txt
utils/docker/images/Dockerfile.fedora-31
utils/docker/images/Dockerfile.ubuntu-19.10

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/159)

common: allow building examples using libpmem API

---

.github/workflows/gha.yml
tests/CMakeLists.txt
utils/docker/build.sh
utils/docker/images/0001-fix-generating-gcov-files-and-turn-off-verbose-log.patch
utils/docker/images/Dockerfile.ubuntu-19.10
utils/docker/images/download-scripts.sh
utils/docker/run-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/166)

common: fix gcov

---

tests/integration/example-01-connection/example-01-connection.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/170)

examples: fix names of tests in example-01-connection.c

---

src/cmocka_alloc.h
src/conn.c
src/conn_req.c
src/ep.c
src/info.c
src/mr.c
src/peer.c
src/private_data.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/171)

rpma: rename Malloc/Free/... to malloc/free

---

examples/02-read-to-volatile/client.c
examples/02-read-to-volatile/server.c
tests/integration/CMakeLists.txt
tests/integration/common/mocks.c
tests/integration/common/mocks.h
tests/integration/example-02-read-to-volatile/CMakeLists.txt
tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/164)

test: add example-02-read-to-volatile integration test

---

src/log.c

very small fix to remove a redundant temporary variable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/172)

rpma: minor log fixes

---

src/conn.c
src/include/librpma.h
tests/unit/conn-test/conn-test-next-completion.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/174)

rpma: add support for the write operation to rpma_conn_next_completion

---

examples/03-read-to-persistent/CMakeLists.txt
examples/03-read-to-persistent/README.md
examples/03-read-to-persistent/client.c
examples/03-read-to-persistent/server.c
examples/CMakeLists.txt
examples/common/common.h

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/160)

examples: read to persistent

---

src/mr.c
tests/unit/mr-test/mr-test-common.c
tests/unit/mr-test/mr-test-common.h
tests/unit/mr-test/mr-test-read.c
tests/unit/mr-test/mr-test-write.c
tests/unit/mr-test/mr-test.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/173)

rpma: implement rpma_mr_write() and its unit tests

---

examples/03-read-to-persistent/client.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/177)

examples: 03 fix allocated DRAM buffer size & content

---

src/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/180)

common: install librpma_log.h

---

examples/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/181)

common: examples cmake typo

---

examples/03-read-to-persistent/client.c
examples/03-read-to-persistent/server.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/183)

examples: 03 remove unnecessary persist; add handling completion

---

ROADMAP.md

This is the very first, published librpma roadmap. Please comment on how do you find it - format, presentation, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/175)

The librpma roadmap [23/07/2020]

---

examples/04-write-to-persistent/CMakeLists.txt
examples/04-write-to-persistent/README.md
examples/04-write-to-persistent/client.c
examples/04-write-to-persistent/server.c
examples/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/185)

examples: write to persistent

---

src/CMakeLists.txt
src/conn.c
src/flush.c
src/flush.h
src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/187)

common: a flushing module scaffolding

---

src/conn.c
src/ep.c
src/include/librpma.h
src/librpma.map

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/188)

rpma: fd scaffolding

---

src/conn.c
src/conn.h
src/conn_req.c
tests/unit/common/mocks-rpma-conn.c
tests/unit/common/test-common.h
tests/unit/conn-test/conn-test-common.c
tests/unit/conn-test/conn-test-common.h
tests/unit/conn-test/conn-test-new.c
tests/unit/conn-test/conn-test-next-completion.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/189)

common: bring a peer to connection creation point

---

tests/unit/ep-test/ep-test.c

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/191)

 test: rpma_ep_get_fd unit tests

---

tests/unit/conn-test/CMakeLists.txt
tests/unit/conn-test/conn-test-common.c
tests/unit/conn-test/conn-test-common.h
tests/unit/conn-test/conn-test-get_event_fd.c
tests/unit/conn-test/conn-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/193)

common: rpma_conn_get_event_fd() unit tests

---

tests/unit/common/mocks-ibverbs.c
tests/unit/common/mocks-rpma-conn.c
tests/unit/common/mocks-rpma-peer.c
tests/unit/common/test-common.h
tests/unit/conn-test/CMakeLists.txt
tests/unit/conn-test/conn-test-common.c
tests/unit/conn-test/conn-test-common.h
tests/unit/conn-test/conn-test-new.c
tests/unit/conn_req-test/conn_req-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/194)

common: harmonize conn module unit tests verbs mocks

---

src/conn.c
src/conn_req.c
tests/integration/common/mocks.c
tests/integration/common/mocks.h
tests/integration/example-01-connection/example-01-connection.c
tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c
tests/unit/common/mocks-ibverbs.c
tests/unit/common/test-common.h
tests/unit/conn-test/conn-test-common.c
tests/unit/conn-test/conn-test-new.c
tests/unit/conn_req-test/conn_req-test.c

Requires:
**Note**: This PR does not include new tests required to cover the new functionality. The only changes to tests are those required to leave tests still functioning. The new tests will be provided in a separate PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/195)

common: introduce ibv_comp_channel along with CQ

---

src/librpma.map

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/197)

common: add rpma_flush to the map file

---

tests/unit/mr-test/mr-test-reg.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/198)

test: set distinguishable names for mr tests

---

src/include/librpma.h
src/mr.c
tests/unit/mr-test/mr-test-reg.c

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/199)

common: add RPMA_MR_USAGE_FLUSHABLE

---

src/conn.c
tests/unit/conn-test/CMakeLists.txt
tests/unit/conn-test/conn-test-common.h
tests/unit/conn-test/conn-test-get_completion_fd.c
tests/unit/conn-test/conn-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/200)

common: rpma_conn_get_completion_fd + unit tests

---

examples/05-flush-to-persistent/CMakeLists.txt
examples/05-flush-to-persistent/README.md
examples/05-flush-to-persistent/client.c
examples/05-flush-to-persistent/server.c
examples/CMakeLists.txt

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/201)

examples: 05-flush-to-persistent

---

tests/unit/conn-test/conn-test-new.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/203)

test: conn add missing tests

---

src/conn_req.c
tests/unit/conn_req-test/conn_req-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/202)

common: conn_req small fix & add missing tests

---

tests/unit/conn_req-test/conn_req-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/207)

test: add missing cases for rpma_conn_req_delete()

---

src/conn.c
src/conn_req.c
src/include/librpma.h
src/librpma.map
tests/integration/common/mocks.c
tests/integration/common/mocks.h
tests/integration/example-01-connection/example-01-connection.c
tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c
tests/unit/common/mocks-ibverbs.c
tests/unit/common/mocks-ibverbs.h
tests/unit/conn-test/conn-test-next-completion.c
tests/unit/conn_req-test/conn_req-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/209)

common: use CQ event channel

---

src/conn.c
src/flush.c
src/flush.h
tests/integration/common/mocks.c
tests/integration/common/mocks.h
tests/integration/example-01-connection/CMakeLists.txt
tests/integration/example-01-connection/example-01-connection.c
tests/integration/example-02-read-to-volatile/CMakeLists.txt
tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c
tests/unit/common/mocks-rpma-flush.c
tests/unit/common/mocks-rpma-flush.h
tests/unit/conn-test/CMakeLists.txt
tests/unit/conn-test/conn-test-common.c
tests/unit/conn-test/conn-test-new.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/196)

rpma: add flush func

---

examples/06-multiple-connections/CMakeLists.txt
examples/06-multiple-connections/README.md
examples/06-multiple-connections/client.c
examples/06-multiple-connections/multiple-connections-common.h
examples/06-multiple-connections/server.c
examples/CMakeLists.txt
examples/common/common-epoll.c
examples/common/common-epoll.h
examples/common/common.h

Requires:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/208)

examples: 06-multiple-connections

---

tests/unit/common/mocks-ibverbs.c
tests/unit/common/mocks-ibverbs.h
tests/unit/common/mocks-rpma-conn.c
tests/unit/common/mocks-rpma-peer.c
tests/unit/common/test-common.h
tests/unit/conn-test/conn-test-common.c
tests/unit/conn-test/conn-test-get_completion_fd.c
tests/unit/conn-test/conn-test-new.c
tests/unit/conn-test/conn-test-next-completion.c
tests/unit/conn-test/conn-test-read.c
tests/unit/conn-test/conn-test-write.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/204)

test: separate mocks-ibverbs.h from test-common.h

---

tests/unit/common/mocks-ibverbs.c
tests/unit/common/mocks-ibverbs.h
tests/unit/mr-test/CMakeLists.txt
tests/unit/mr-test/mr-test-common.c
tests/unit/mr-test/mr-test-common.h
tests/unit/mr-test/mr-test-read.c
tests/unit/mr-test/mr-test-reg.c
tests/unit/mr-test/mr-test-write.c

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/205)

common: move ibverbs from mr to common

---

tests/unit/common/mocks-ibverbs.c
tests/unit/common/mocks-ibverbs.h
tests/unit/common/test-common.h
tests/unit/peer-test/CMakeLists.txt
tests/unit/peer-test/peer-test.c

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/206)

common: move peer's verbs mocks to common

---

tests/unit/common/mocks-rpma-flush.c
tests/unit/common/test-common.h
tests/unit/conn-test/conn-test-common.c
tests/unit/conn-test/conn-test-new.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/212)

test: add delete_test_flush_delete_E_PROVIDER test for rpma_conn_delete

---

tests/unit/conn_req-test/conn_req-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/213)

test: fix brief comment of group_setup_conn_req

---

tests/unit/conn_req-test/conn_req-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/216)

test: add the from_cm_event_test_req_notify_cq_fail test

---

tests/unit/conn-test/CMakeLists.txt
tests/unit/conn-test/conn-test-common.h
tests/unit/conn-test/conn-test-prepare-completions.c
tests/unit/conn-test/conn-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/215)

test: add tests for rpma_conn_prepare_completions()

---

examples/README

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/221)

examples: fix link to documentation in main README

---

utils/docker/run-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/227)

common: run run-doc-update.sh

---

utils/docker/images/Dockerfile.fedora-31

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/228)

common: add doc update dependencies to Fedora

---

src/conn.c
src/include/librpma.h
src/librpma.map

Requires:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/226)

common: add rpma_write_atomic scaffolding

---

tests/unit/common/mocks-rpma-info.c
tests/unit/utils-test/CMakeLists.txt
tests/unit/utils-test/utils-conn_event_2str.c
tests/unit/utils-test/utils-get_ibv_context.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/237)

common: split utils tests

---

src/conn.c
src/include/librpma.h
tests/unit/conn-test/CMakeLists.txt
tests/unit/conn-test/conn-test-common.h
tests/unit/conn-test/conn-test-write_atomic.c
tests/unit/conn-test/conn-test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/232)

rpma: add rpma_write_atomic() & unit tests

---

src/include/librpma.h
src/librpma.map
src/rpma.c
tests/integration/common/mocks.c
tests/integration/common/mocks.h
tests/integration/example-01-connection/example-01-connection.c
tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c
tests/unit/common/mocks-ibverbs.c
tests/unit/common/mocks-ibverbs.h
tests/unit/conn-test/conn-test-next-completion.c
tests/unit/conn-test/conn-test-prepare-completions.c
tests/unit/conn_req-test/conn_req-test.c
tests/unit/mr-test/mr-test-read.c
tests/unit/mr-test/mr-test-write.c
tests/unit/utils-test/CMakeLists.txt
tests/unit/utils-test/utils-ibv_context_is_odp_capable.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/240)

common: introduce rpma_utils_ibv_context_is_odp_capable()

---

tests/unit/common/mocks-rpma-utils.c
tests/unit/common/mocks-rpma-utils.h
tests/unit/peer-test/peer-test.c

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/235)

test: On-Demand Paging detection and registration unit tests

---

ROADMAP.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/225)

common: roadmap update 08/10/2020

---

INSTALL.md

Describe librpma dev environment.
Ref: #42
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/186)

rpma: add INSTALL.md file

---

examples/06-multiple-connections/README.md

Signed-off-by: Changcheng Liu <changcheng.liu@aliyun.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/252)

examples: 06-multiple-connections: refine example usage 

---

tests/unit/CMakeLists.txt
tests/unit/error/CMakeLists.txt
tests/unit/error/error.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/250)

test: reorganization of the 'error' unit test

---

utils/docker/images/Dockerfile.fedora-31
utils/docker/run-doc-update.sh
utils/mans_header.md
utils/src2mans.sh

You can view the final result simulation here: https://janekmi.github.io/rpma/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/268)

common: generate markdown doc and use it for gh-pages

---

utils/docker/run-doc-update.sh

Ref: #268
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/271)

common: generate markdown doc and use it for gh-pages (fix)

---

utils/docker/images/Dockerfile.fedora-31

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/272)

common: force Fedora image rebuild

---

CMakeLists.txt
examples/README
examples/config_softroce.sh

Add the 'utils/rxe_config.sh' script for configuring SoftRoCE
and the 'config_rxe' make target to run it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/265)

examples: add examples/config_softroce.sh script for configuring SoftRoCE

---

CMakeLists.txt
examples/README
examples/config_softroce.sh
examples/run-all-on-SoftRoCE.sh

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/266)

examples: add script for running examples on SoftRoCE

---

examples/02-read-to-volatile/CMakeLists.txt
examples/02-read-to-volatile/client.c
examples/02-read-to-volatile/server.c
examples/03-read-to-persistent/CMakeLists.txt
examples/03-read-to-persistent/client.c
examples/03-read-to-persistent/server.c
examples/04-write-to-persistent/CMakeLists.txt
examples/04-write-to-persistent/client.c
examples/04-write-to-persistent/server.c
examples/05-flush-to-persistent/CMakeLists.txt
examples/05-flush-to-persistent/client.c
examples/05-flush-to-persistent/server.c
examples/06-multiple-connections/CMakeLists.txt
examples/06-multiple-connections/client.c
examples/06-multiple-connections/server.c
examples/CMakeLists.txt
examples/common/common-conn.c
examples/common/common-conn.h
tests/integration/example-01-connection/CMakeLists.txt
tests/integration/example-02-read-to-volatile/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/277)

common: rename examples/common/common.[ch] to common-conn.[ch]

---

src/common.h
src/conn.c
src/conn_req.c
src/ep.c
src/flush.c
src/info.c
src/log_internal.h
src/mr.c
src/peer.c
src/rpma.c
tests/integration/common/mocks.c
tests/unit/common/mocks-ibverbs.c
tests/unit/common/mocks-rpma-log.c
tests/unit/common/mocks-rpma-utils.c
tests/unit/conn/CMakeLists.txt
tests/unit/conn_req/CMakeLists.txt
tests/unit/ep/CMakeLists.txt
tests/unit/ep/ep-common.c
tests/unit/flush/CMakeLists.txt
tests/unit/info/CMakeLists.txt
tests/unit/mr/CMakeLists.txt
tests/unit/peer/CMakeLists.txt
tests/unit/utils/CMakeLists.txt

Requires:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/278)

common: use logging module in the RPMA library

---

tests/unit/common/mocks-rpma-log.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/282)

test: trigger all logs

---

utils/src2mans.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/283)

common: terminate md generation on pandoc fail

---

examples/01-connection/client.c
examples/01-connection/server.c
examples/02-read-to-volatile/client.c
examples/02-read-to-volatile/server.c
examples/03-read-to-persistent/client.c
examples/03-read-to-persistent/server.c
examples/04-write-to-persistent/client.c
examples/04-write-to-persistent/server.c
examples/05-flush-to-persistent/client.c
examples/05-flush-to-persistent/server.c
examples/06-multiple-connections/client.c
examples/06-multiple-connections/server.c
examples/common/common-conn.c
examples/common/common-conn.h

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/279)

examples: use the RPMA logging

---

ROADMAP.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/293)

common: roadmap update 08/25/2020

---

ROADMAP.md

This way the ROADMAP looks a lot better: https://github.com/janekmi/rpma/blob/common-ROADMAP-checkboxes/ROADMAP.md
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/294)

common: give ROADMAP real checkboxes

---

src/conn.c
src/include/librpma.h
src/librpma.map
src/mr.c
src/mr.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/295)

rpma: send/recv scaffolding

---

_data/libs_map.yml
_data/releases_linux.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/296)

doc: add rpma_send/_recv to _data

---

CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/304)

test: add missing flags for ASAN and UBSAN

---

src/common.h
src/conn.c
src/conn_req.c
src/ep.c
src/flush.c
src/include/librpma.h
src/info.c
src/log_internal.h
src/mr.c
src/peer.c
src/rpma.c
tests/unit/info/info-new.c
tests/unit/mr/mr-read.c
tests/unit/mr/mr-write.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/290)

rpma: add more details to RPMA_LOG_ERROR_WITH_ERRNO() logs

---

src/mr.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/316)

rpma: fix one RPMA_LOG_ERROR_WITH_ERRNO() call

---

examples/04-write-to-persistent/client.c
tests/unit/log_default/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/315)

test: fix failing log_default-function tests in Release build

---

src/log_default.c
tests/unit/common/mocks-stdio.c
tests/unit/common/mocks-stdio.h
tests/unit/log_default/function.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/297)

test: do not test if snprintf() fails in rpma_log_default_function()

---

src/conn_req.c
src/include/librpma.h
src/librpma.map

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/317)

rpma: rpma_conn_req_recv scaffolding

---

src/conn.c
src/include/librpma.h
tests/unit/conn/conn-next-completion.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/311)

common: add byte_len to rpma_completion

---

tests/unit/conn/conn-disconnect.c
tests/unit/conn/conn-flush.c
tests/unit/conn/conn-get_completion_fd.c
tests/unit/conn/conn-get_event_fd.c
tests/unit/conn/conn-new.c
tests/unit/conn/conn-next-completion.c
tests/unit/conn/conn-next-event.c
tests/unit/conn/conn-prepare-completions.c
tests/unit/conn/conn-private-data.c
tests/unit/conn/conn-read.c
tests/unit/conn/conn-write.c
tests/unit/conn/conn-write_atomic.c
tests/unit/conn_req/conn_req-connect.c
tests/unit/conn_req/conn_req-delete.c
tests/unit/conn_req/conn_req-from_cm_event.c
tests/unit/conn_req/conn_req-new.c
tests/unit/ep/ep-common.c
tests/unit/log/threshold.c
tests/unit/mr/mr-descriptor.c
tests/unit/mr/mr-read.c
tests/unit/mr/mr-reg.c
tests/unit/mr/mr-write.c
tests/unit/private_data/private_data-copy.c
tests/unit/private_data/private_data-store.c

Fix various minor issues occurring while compiling with clang.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/302)

test: various minor fixes

---

tests/unit/conn/conn-disconnect.c
tests/unit/conn/conn-flush.c
tests/unit/conn/conn-get_completion_fd.c
tests/unit/conn/conn-get_event_fd.c
tests/unit/conn/conn-new.c
tests/unit/conn/conn-next-completion.c
tests/unit/conn/conn-next-event.c
tests/unit/conn/conn-prepare-completions.c
tests/unit/conn/conn-private-data.c
tests/unit/conn/conn-read.c
tests/unit/conn/conn-recv.c
tests/unit/conn/conn-send.c
tests/unit/conn/conn-write.c
tests/unit/conn/conn-write_atomic.c
tests/unit/conn_req/conn_req-connect.c
tests/unit/conn_req/conn_req-delete.c
tests/unit/conn_req/conn_req-from_cm_event.c
tests/unit/conn_req/conn_req-new.c
tests/unit/mr/mr-descriptor.c
tests/unit/mr/mr-read.c
tests/unit/mr/mr-reg.c
tests/unit/mr/mr-send.c
tests/unit/mr/mr-write.c
tests/unit/private_data/private_data-copy.c
tests/unit/private_data/private_data-store.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/320)

test: fix left 'no previous extern declaration for ...' errors

---

CONTRIBUTING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/321)

rpma: add CONTRIBUTING.md file

---

examples/01-connection/client.c
examples/01-connection/server.c
examples/06-multiple-connections/server.c
examples/common/common-conn.c
src/CMakeLists.txt
src/conn_cfg.c
src/conn_cfg.h
src/conn_req.c
src/conn_req.h
src/ep.c
src/include/librpma.h
src/librpma.map
tests/unit/conn_req/conn_req-common.c
tests/unit/conn_req/conn_req-from_cm_event.c
tests/unit/conn_req/conn_req-new.c
tests/unit/ep/ep-common.c
tests/unit/ep/ep-next_conn_req.c

Requires:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/324)

common: rpma_conn_cfg scaffolding

---

src/mr.c
tests/unit/common/mocks-ibverbs.c
tests/unit/common/mocks-ibverbs.h
tests/unit/mr/CMakeLists.txt
tests/unit/mr/mr-recv.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/328)

rpma: implement rpma_mr_recv() and its unit tests

---

CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/330)

common: do not install and package sources of examples

---

examples/07-atomic-write/CMakeLists.txt
examples/07-atomic-write/README.md
examples/07-atomic-write/client.c
examples/07-atomic-write/server.c
examples/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/318)

examples: add atomic_write example

---

examples/run-all-on-SoftRoCE.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/334)

exmaples: fix runnning 07-atomic-write example on SoftRoCE

---

src/conn.c
tests/unit/conn/conn-next-completion.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/335)

common: handle RECV/SEND in _next_completion

---

examples/08-messages-ping-pong/CMakeLists.txt
examples/08-messages-ping-pong/README.md
examples/08-messages-ping-pong/client.c
examples/08-messages-ping-pong/messages-ping-pong-common.h
examples/08-messages-ping-pong/server.c
examples/CMakeLists.txt
src/conn.c

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/312)

examples: 08 messages ping pong

---

src/conn_req.c
src/peer.c
src/peer.h
tests/unit/common/mocks-rpma-peer.c
tests/unit/peer/peer-create_qp.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/337)

common: add conn_cfg to rpma_peer_create_qp

---

examples/run-all-on-SoftRoCE.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/341)

examples: fix arguments of 08-messages-ping-pong example on SoftRoCE

---

src/conn_cfg.c
src/conn_cfg.h
src/include/librpma.h
tests/unit/CMakeLists.txt
tests/unit/common/test-common.h
tests/unit/conn_cfg/CMakeLists.txt
tests/unit/conn_cfg/conn_cfg-common.c
tests/unit/conn_cfg/conn_cfg-common.h
tests/unit/conn_cfg/conn_cfg-cq_size.c
tests/unit/conn_cfg/conn_cfg-cqe.c
tests/unit/conn_cfg/conn_cfg-delete.c
tests/unit/conn_cfg/conn_cfg-new.c
tests/unit/conn_cfg/conn_cfg-rq_size.c
tests/unit/conn_cfg/conn_cfg-sq_size.c
tests/unit/conn_cfg/conn_cfg-timeout.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/331)

common: conn_cfg module implementation and tests

---

src/ep.c
tests/integration/example-01-connection/CMakeLists.txt
tests/integration/example-02-read-to-volatile/CMakeLists.txt
tests/unit/common/mocks-rpma-conn_cfg.c
tests/unit/common/mocks-rpma-conn_cfg.h
tests/unit/common/test-common.h
tests/unit/ep/CMakeLists.txt
tests/unit/ep/ep-common.c
tests/unit/ep/ep-common.h
tests/unit/ep/ep-get_fd.c
tests/unit/ep/ep-listen.c
tests/unit/ep/ep-next_conn_req.c

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/338)

common: pass conn_cfg via ep_next_conn_req()

---

src/conn_req.c
tests/integration/common/mocks.c
tests/unit/common/mocks-ibverbs.c
tests/unit/common/mocks-rdma_cm.c
tests/unit/common/mocks-rpma-conn_cfg.c
tests/unit/common/mocks-rpma-conn_cfg.h
tests/unit/common/mocks-rpma-peer.c
tests/unit/conn_req/CMakeLists.txt
tests/unit/conn_req/conn_req-common.c
tests/unit/conn_req/conn_req-common.h
tests/unit/conn_req/conn_req-connect.c
tests/unit/conn_req/conn_req-delete.c
tests/unit/conn_req/conn_req-from_cm_event.c
tests/unit/conn_req/conn_req-new.c
tests/unit/conn_req/conn_req-recv.c

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/339)

 common: pass conn_cfg via conn_req_new/_from_cm_event()

---

src/conn_req.h
src/peer.c
tests/unit/common/mocks-rpma-conn_cfg.c
tests/unit/common/mocks-rpma-conn_cfg.h
tests/unit/peer/CMakeLists.txt
tests/unit/peer/peer-create_qp.c

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/340)

common: pass conn_cfg via peer_create_qp()

---

.github/workflows/gha.yml
.travis.yml
utils/docker/build.sh
utils/docker/images/Dockerfile.fedora-31
utils/docker/run-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/308)

common: add to CI Debug and Release builds with clang compiler

---

examples/08-messages-ping-pong/README.md

Signed-off-by: Changcheng Liu <changcheng.liu@aliyun.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/348)

examples:08-messages-ping-pong: refine example explanation

---

examples/03-read-to-persistent/client.c
examples/04-write-to-persistent/client.c
examples/05-flush-to-persistent/client.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/353)

examples: fix non null terminated string

---

examples/02-read-to-volatile/client.c
examples/03-read-to-persistent/server.c
examples/04-write-to-persistent/client.c
examples/05-flush-to-persistent/client.c
examples/08-messages-ping-pong/server.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/355)

examples: fix invalid order

---

src/mr.c

Signed-off-by: Changcheng Liu <changcheng.liu@aliyun.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/349)

rpma: register MR with IBV_ACCESS_LOCAL_WRITE for recv

---

src/flush.c
tests/unit/flush/flush-new.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/357)

rpma: check if memory is allocated (rpma_flush_apm)

---

tests/unit/mr/mr-reg.c

Ref: #349
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/367)

test: add the missing test case

---

doc/manuals_3.txt
src/CMakeLists.txt
src/conn.c
src/include/librpma.h
src/librpma.map
src/peer_cfg.c
src/peer_cfg.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/370)

rpma: peer_cfg scaffolding

---

examples/06-multiple-connections/server.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/354)

examples: fix numeric overflow

---

examples/run-all-on-SoftRoCE.sh

Start the client of the `08-messages-ping-pong` example only once.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/352)

examples: fix running the 08-messages-ping-pong example on SoftRoCE

---

src/include/librpma.h
src/peer_cfg.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/376)

rpma: fix signature of rpma_peer_cfg_get_persistent_flush_supported()

---

CMakeLists.txt
cmake/functions.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/363)

common: check if libibverbs has ODP support

---

src/mr.c
tests/unit/mr/mr-descriptor.c

... and a log message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/380)

rpma: fix return value of rpma_mr_remote_from_descriptor()

---

_data/libs_map.yml
_data/releases_linux.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/381)

doc: update and cleanup

---

examples/03-read-to-persistent/client.c
examples/03-read-to-persistent/server.c
examples/04-write-to-persistent/client.c
examples/04-write-to-persistent/server.c
examples/05-flush-to-persistent/client.c
examples/05-flush-to-persistent/server.c
examples/07-atomic-write/client.c
examples/07-atomic-write/server.c
examples/common/common-conn.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/382)

examples: add peer_desc to the common_data structure

---

src/mr.c

Fix the following errors:
```
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/ldorau/work/rpma/src/mr.c:264:2 in 
/home/ldorau/work/rpma/src/mr.c:266:2: runtime error: store to misaligned address 0x7ffe81e477e9 for type 'uint64_t' (aka 'unsigned long'), which requires 8 byte alignment
0x7ffe81e477e9: note: pointer points here
03 02 01  00 ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  ff ff ff ff ff
^ 
```
Ref: #303
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/386)

rpma: fix 'store to misaligned address' errors in serializing data

---

utils/docker/run-build.sh

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/309)

common: add a build with ASAN and UBSAN turned on

---

doc/CMakeLists.txt
utils/src2mans.sh

Fix checking if pandoc can be found and if Markdown documentation
will be generated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/379)

doc: fix checking if pandoc can be found

---

examples/05-flush-to-persistent/README.md
examples/05-flush-to-persistent/client.c
examples/05-flush-to-persistent/server.c
examples/07-atomic-write/README.md
examples/07-atomic-write/client.c

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/384)

examples: incorporate peer's configuration 

---

examples/07-atomic-write/client.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/396)

examples: fix error handling in examples/07-atomic-write/client.c

---

utils/docker/images/Dockerfile.fedora-31
utils/docker/images/Dockerfile.ubuntu-19.10

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/392)

common: add libprotobuf-c-dev(el) to docker images

---

utils/docker/run-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/397)

common: remove the launch of interactive bash added for debugging

---

cmake/packages.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/391)

common: check for package generators

---

tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c

The current code works by accident.
The private data has to contain a descriptor (a buffer with serialized data),
because it will be read by rpma_mr_remote_from_descriptor() in the client.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/388)

test: fix creating the descriptor in example-02-read-to-volatile

---

src/conn.c
src/include/librpma.h
tests/integration/example-01-connection/CMakeLists.txt
tests/integration/example-02-read-to-volatile/CMakeLists.txt
tests/unit/common/mocks-rpma-peer_cfg.c
tests/unit/common/test-common.h
tests/unit/conn/CMakeLists.txt
tests/unit/conn/conn-apply_remote_peer_cfg.c
tests/unit/conn/conn-common.h
tests/unit/conn/conn-flush.c
tests/unit/peer_cfg/peer_cfg-common.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/401)

rpma: implement rpma_conn_apply_remote_peer_cfg()

---

INSTALL.md
doc/CMakeLists.txt

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/390)

doc: check if src2man, find and diff are installed

---

ROADMAP.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/403)

common: roadmap updated after demo on 9/3/2020

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/414)

doc: improve the documentation to rpma_utils... functions

---

src/log_default.c
tests/unit/log_default/function.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/389)

Fixed log level names - to avoid problems with klockwork

---

ROADMAP.md

Roadmap before last sprint of release 0.9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/416)

common: roadmap updated after demo on 9/17/2020

---

examples/common/common-conn.c
examples/common/common-conn.h
src/conn.c
src/conn.h
src/conn_req.c
src/conn_req.h
src/ep.c
src/flush.c
src/flush.h
src/include/librpma.h
src/mr.c
src/peer.c
src/peer.h
tests/unit/common/mocks-rpma-conn.c
tests/unit/common/mocks-rpma-flush.c
tests/unit/common/mocks-rpma-mr.c
tests/unit/common/mocks-rpma-peer.c
tests/unit/ep/ep-common.c
tests/unit/peer/peer-create_qp.c
tests/unit/peer/peer-mr_reg.c

Add const to all public API calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/425)

common: add const to all peer related API calls

---

utils/src2mans.sh

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/438)

common: do not ignore errors of src2man

---

CMakeLists.txt
examples/01-connection/client.c
examples/01-connection/server.c
examples/02-read-to-volatile/client.c
examples/02-read-to-volatile/server.c
examples/common/common-conn.c
examples/common/common-conn.h
src/peer.c
src/private_data.c
src/rpma.c
tests/integration/common/mocks.c
tests/integration/common/mocks.h
tests/integration/example-01-connection/example-01-connection.c
tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c
tests/unit/common/mocks-ibverbs.c
tests/unit/common/mocks-ibverbs.h
tests/unit/common/test-common.h
tests/unit/conn/conn-common.c
tests/unit/conn/conn-next-completion.c
tests/unit/info/info-bind_addr.c
tests/unit/info/info-common.c
tests/unit/info/info-resolve_addr.c
tests/unit/peer/peer-mr_reg.c
tests/unit/private_data/private_data-common.h
tests/unit/utils/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/423)

common: disable On-Demand Paging (ODP) if it is not supported

---

utils/check-area.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/406)

common: print out the 'common' area in nothing else was printed

---

examples/09-flush-to-persistent-GPSPM/server.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/412)

examples: fix memory leak

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/420)

doc: improve the documentation to rpma_peer... functions

---

examples/03-read-to-persistent/client.c
examples/03-read-to-persistent/server.c
examples/04-write-to-persistent/client.c
examples/04-write-to-persistent/server.c
examples/05-flush-to-persistent/client.c

Fix errors: variable 'is_pmem' set but not used\
[-Werror=unused-but-set-variable]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/443)

examples: fix errors: variable 'is_pmem' set but not used

---

tests/unit/conn/conn-flush.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/444)

test: add missing unit tests for conn-flush

---

src/include/librpma.h
src/log.c
src/log_default.c
src/log_default.h
src/log_internal.h
tests/unit/common/mocks-rpma-log.c
tests/unit/common/mocks-rpma-log_default.c
tests/unit/log/macros.c
tests/unit/log/threshold.c
tests/unit/log_default/function.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/446)

rpma: replace enum typedefs with just enums

---

tests/unit/mr/CMakeLists.txt
tests/unit/mr/mr-common.h
tests/unit/mr/mr-get_flush_type.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/445)

test: add missing unit tests for rpma_mr_remote_get_flush_type()

---

src/conn.c
src/conn_cfg.c
src/conn_cfg.h
src/conn_req.c
src/conn_req.h
src/ep.c
src/flush.c
src/flush.h
src/include/librpma.h
src/mr.c
src/mr.h
src/peer.c
src/peer.h
src/peer_cfg.c
tests/unit/common/mocks-rpma-conn_cfg.c
tests/unit/common/mocks-rpma-flush.c
tests/unit/common/mocks-rpma-mr.c
tests/unit/common/mocks-rpma-peer.c
tests/unit/common/mocks-rpma-peer_cfg.c
tests/unit/ep/ep-common.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/439)

add const to all possible API calls

---

src/include/librpma.h

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/426)

doc: improve the documentation to rpma_mr... functions

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/428)

doc: improve the documentation to rpma_conn... functions

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/429)

doc: improve the documentation to rpma_ep... functions

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/431)

doc: improve the documentation to rpma...completion functions

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/430)

doc: improve the documentation to rpma... functions

---

utils/docker/run-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/455)

common: fix setting TEST_DIR in run-build.sh

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/432)

doc: improve the documentation to rpma_err... functions

---

utils/docker/run-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/459)

common: do not print the current directory in compile_example_standalone()

---

src/conn_req.c
src/ep.c
src/include/librpma.h
src/info.h
src/peer.c
src/peer.h
src/rpma.c
tests/unit/common/mocks-rpma-peer.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/456)

common: all pointers to a pointer should have _ptr suffix

---

examples/01-connection/README.md
examples/06-multiple-connections/server.c
src/conn.c
src/conn_req.c
src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/458)

common: fix 'initialize' with 'initiate' where needed

---

INSTALL.md

Required:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/366)

common: add info about supported OSes to INSTALL.md

---

utils/docker/run-build.sh

Fix handling PACKAGE_MANAGER in run-build.sh:
1) PACKAGE_MANAGER has to be set,
2) if PACKAGE_MANAGER is unsupported, install the library from sources
It fixes running run-build.sh locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/398)

common: fix handling PACKAGE_MANAGER in run-build.sh

---

doc/manuals_3.txt
src/include/librpma.h
src/librpma.map
src/rpma_err.c
src/rpma_err.h
tests/unit/conn/conn-disconnect.c
tests/unit/conn/conn-new.c
tests/unit/conn/conn-next-completion.c
tests/unit/conn/conn-next-event.c
tests/unit/conn/conn-prepare-completions.c
tests/unit/conn_req/conn_req-connect.c
tests/unit/conn_req/conn_req-delete.c
tests/unit/conn_req/conn_req-from_cm_event.c
tests/unit/conn_req/conn_req-new.c
tests/unit/ep/ep-listen.c
tests/unit/ep/ep-next_conn_req.c
tests/unit/error/error.c
tests/unit/flush/flush-new.c
tests/unit/info/info-bind_addr.c
tests/unit/info/info-new.c
tests/unit/info/info-resolve_addr.c
tests/unit/mr/mr-reg.c
tests/unit/peer/peer-create_qp.c
tests/unit/peer/peer-mr_reg.c
tests/unit/peer/peer-new.c
tests/unit/utils/utils-ibv_context_is_odp_capable.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/464)

remove and hide functions from the rpma_err module

---

examples/05-flush-to-persistent/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/466)

examples: fix syntax in README.md of the 05 example

---

examples/README.md
examples/template-example/README
examples/template-example/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/467)

examples: rename README to README.md and reword/reformat

---

utils/docker/run-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/469)

common: add uninstalling installed librpma development packages

---

examples/08-messages-ping-pong/client.c
src/conn_req.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/475)

rpma: remove the redundant comments

---

.github/workflows/gha.yml
.travis.yml
utils/docker/build.sh
utils/docker/images/download-scripts.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/472)

common: move coverage build from Travis to GHA 

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/474)

rpma: librpma 7 man page scaffolding

---

src/conn.c
tests/unit/common/mocks-rdma_cm.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/476)

rpma: improve error logging

---

src/info.c
tests/unit/info/info-resolve_addr.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/481)

rpma: remove conditions

---

src/peer.c
tests/unit/mr/mr-descriptor.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/483)

rpma: improve comments

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/478)

rpma: write 'DEBUGGING AND ERROR HANDLING' section of manual

---

src/include/librpma.h
src/log.c
src/log_internal.h
tests/unit/common/mocks-rpma-log.c

To add threads awareness to log implementation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/485)

common: threads awareness added to log

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/484)

rpma: librpma.7: Direct Write to PMem

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/486)

doc: add SEE ALSO section utils and peer

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/488)

doc: add SEE ALSO section mr

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/489)

doc: librpma.7: Client Operation

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/499)

rpma: fix formatting of 'Client operation'

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/490)

doc: add SEE ALSO section (conn)

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/495)

doc: add SEE ALSO section (ep, rpma)

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/496)

doc: add SEE ALSO section (completion, err, log)

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/504)

doc: improve librpma.7 formatting

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/491)

doc: librpma.7: Server Operation

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/497)

rpma: write 'MEMORY MANAGEMENT' section of manual

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/510)

doc: add parentheses

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/501)

doc: librpma.7: sync and async modes

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/500)

rpma: write the 'MESSAGING' section of the librpma.7 manual

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/507)

doc: add the missing documentation

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/508)

doc: librpma.7: queues, performance and resource use

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/522)

rpma: write the 'REMOTE MEMORY ACCESS' section of the librpma.7 manual

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/517)

doc: librpma.7: thread safety

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/518)

rpma: write the 'COMPLETIONS' section of the librpma.7 manual

---

tests/unit/conn/conn-common.c
tests/unit/conn/conn-common.h
tests/unit/conn/conn-disconnect.c
tests/unit/conn/conn-flush.c
tests/unit/conn/conn-get_completion_fd.c
tests/unit/conn/conn-get_event_fd.c
tests/unit/conn/conn-new.c
tests/unit/conn/conn-next_event.c
tests/unit/conn/conn-private_data.c
tests/unit/conn/conn-read.c
tests/unit/conn/conn-recv.c
tests/unit/conn/conn-send.c
tests/unit/conn/conn-write.c
tests/unit/conn/conn-write_atomic.c
tests/unit/ep/ep-common.c
tests/unit/mr/mr-common.c
tests/unit/mr/mr-read.c
tests/unit/mr/mr-recv.c
tests/unit/mr/mr-reg.c
tests/unit/mr/mr-send.c
tests/unit/mr/mr-write.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/520)

test: fix incorrect names of test files

---

_data/libs_map.yml
_data/releases_linux.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/527)

doc: update gh-pages

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/521)

rpma: write the 'PEER' section of the librpma.7 manual

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/524)

rpma: write the 'ON-DEMAND PAGING SUPPORT' section of librpma.7 manual

---

src/include/librpma.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/530)

doc: librpma.7: elaborate

---

src/include/librpma.h

** ... ** -> \f[B] ... \f[R]
\* ... * -> \f[I] ... \f[R]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/529)

doc: improve formatting

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/533)

common: 0.9.0 changelog update

---

utils/docker/run-doc-update.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/540)

common: remove setting the nonexisting BUILD_BENCHMARKS variable

---

utils/docker/run-doc-update.sh

This patch is the second part of the change in #536.
This PR has to be merged just after having merged #536.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/538)

common: generate documentation in the 'manpages' directory

---

ROADMAP.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/543)

common: roadmap update after release 0.9.0

---

CMakeLists.txt

don't hide info while looking for packages, it helps debugging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/545)

common: make CMake more verbose

---

INSTALL.md

Required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/548)

doc: add pkg-config to Build-Deps

---

src/mr.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/550)

rpma: ibv_post_send and ibv_post_recv return errno

---

.github/workflows/gha.yml
.travis.yml
utils/docker/images/Dockerfile.fedora-32
utils/docker/images/Dockerfile.ubuntu-20.04

Switch from Fedora 31 to 32 and from Ubuntu 19.10 to 20.04.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/557)

common: switch to newer versions of OSes

---

cmake/functions.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/559)

common: rdma_getaddrinfo clang detection fix

---

examples/06-multiple-connections/server.c
examples/log/log-example.c
src/include/librpma.h
src/peer.c
tests/unit/common/mocks-rpma-info.c
tests/unit/conn/conn-new.c
tests/unit/ep/ep-common.c
utils/docker/images/README.md
utils/docker/run-build.sh
utils/md2man/md2man.sh

These come from:
* codespell
* lintian
I did not fix anything extra (despite seeing copious errors) but that's something for the legendary less busy time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/563)

automated typo fixes

---

examples/common/common-conn.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/567)

examples: zero the memory allocated by malloc_aligned()

---

.github/workflows/nightly.yml
utils/docker/images/Dockerfile.archlinux-base-latest
utils/docker/images/Dockerfile.centos-6
utils/docker/images/Dockerfile.centos-7
utils/docker/images/Dockerfile.centos-7.6.1810
utils/docker/images/Dockerfile.centos-8
utils/docker/images/Dockerfile.debian-10
utils/docker/images/Dockerfile.debian-9
utils/docker/images/Dockerfile.debian-experimental
utils/docker/images/Dockerfile.debian-stable
utils/docker/images/Dockerfile.debian-testing
utils/docker/images/Dockerfile.fedora-26
utils/docker/images/Dockerfile.fedora-27
utils/docker/images/Dockerfile.fedora-28
utils/docker/images/Dockerfile.fedora-29
utils/docker/images/Dockerfile.fedora-30
utils/docker/images/Dockerfile.fedora-31
utils/docker/images/Dockerfile.fedora-33
utils/docker/images/Dockerfile.fedora-rawhide
utils/docker/images/Dockerfile.opensuse-leap-latest
utils/docker/images/Dockerfile.opensuse-tumbleweed-latest
utils/docker/images/Dockerfile.ubuntu-16.04
utils/docker/images/Dockerfile.ubuntu-18.04
utils/docker/images/Dockerfile.ubuntu-19.10
utils/docker/images/Dockerfile.ubuntu-20.10
utils/docker/images/Dockerfile.ubuntu-rolling
utils/docker/images/install-archlinux-aur.sh
utils/docker/images/install-libndctl.sh
utils/docker/images/install-pmdk.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/470)

common: add nightly build on other Linux distros on GHA

---

.github/workflows/gha.yml
.github/workflows/nightly.yml
.travis.yml
utils/docker/build.sh
utils/docker/images/build-image.sh
utils/docker/images/push-image.sh
utils/docker/pull-or-rebuild-image.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/547)

common: migrate from Docker Hub to GitHub Container Registry

---

utils/docker/build.sh
utils/docker/images/build-image.sh
utils/docker/images/push-image.sh
utils/docker/images/set-images-version.sh
utils/docker/pull-or-rebuild-image.sh
utils/docker/set-ci-vars.sh

Introduce the IMG_VER variable containing a version
of the Docker images and update the version from 0.1 to 0.9.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/553)

common: update version of Docker images to 0.9.0

---

tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c

Reorder configuring mocks in the 02 integration tests,
so that they match function calls in the 02 example.
This patch does not make any changes except of reordering
the existing code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/571)

test: reorder configuring mocks to match order of function calls

---

src/conn_req.c
tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c
tests/unit/common/mocks-rpma-private_data.c
tests/unit/conn_req/conn_req-common.c
tests/unit/conn_req/conn_req-connect.c
tests/unit/conn_req/conn_req-delete.c
tests/unit/conn_req/conn_req-from_cm_event.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/552)

rpma: discard private data on connection accept

---

cmake/functions.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/569)

common: correct checking signature of rdma_getaddrinfo() for clang

---

examples/common/common-conn.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/575)

examples: add one missing empty line

---

src/mr.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/587)

rpma: add missing comment to usage_to_access()

---

utils/docker/pull-or-rebuild-image.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/591)

common: rebuild and push docker images if pulling fails

---

utils/docker/pull-or-rebuild-image.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/593)

common: add missing comment about rebuilding docker image

---

documentation/perf-tuning-latency.md
index.md

Preview: https://janekmi.github.io/rpma/
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/594)

doc: perf-tuning-latency stub

---

documentation/perf-tuning-latency.md

Preview: https://janekmi.github.io/rpma/documentation/perf-tuning-latency.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/595)

doc: perf-tuning-latency BIOS & CPU

---

documentation/perf-tuning-latency.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/600)

doc: perf-tuning-latency headers

---

documentation/perf-tuning-latency.md

Preview: https://janekmi.github.io/rpma/documentation/perf-tuning-latency.html
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/596)

doc: perf-tuning-latency RDMA

---

documentation/perf-tuning-latency.md

Requires:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/599)

doc: perf-tuning-latency workloads

---

documentation/basic-direct-write-to-pmem.md
index.md

Preview: https://janekmi.github.io/rpma/
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/598)

doc: perf-tuning-latency DDIO

---

documentation/basic-direct-write-to-pmem.md

Preview: https://janekmi.github.io/rpma/documentation/basic-direct-write-to-pmem.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/601)

doc: basic-direct-write-to-pmem update ddio.sh URL

---

tools/fio-histogram.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/604)

common: tools: generate a FIO log histogram

---

tools/ib_read_lat.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/605)

common: tools: ib_read_lat.sh

---

tools/BENCHMARKING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/606)

common: tools: benchmarking step-by-step

---

tools/fio_jobs/README.md
tools/fio_jobs/librpma-client-read.fio
tools/fio_jobs/librpma-server.fio
tools/fio_json2csv.py
tools/rpma_read_lat.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/607)

common: tools: RPMA read latency automat

---

documentation/perf-tuning-latency.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/608)

doc: BIOS settings

---

tools/fio-histogram.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/609)

common: tools: add input description for fio-histogram

---

tools/rpma_read_lat.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/610)

common: tools: fix rpma_read_lat

---

tools/ib_read_lat.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/613)

common: tools: ib_read_lat.sh use common output file (fix)

---

tools/ib_read_lat.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/614)

common: tools: ib_read_lat echo log files

---

tools/BENCHMARKING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/611)

common: doc: BENCHMARKING.md

---

tools/rpma_read_lat.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/618)

common: tools: rpma_read_lat.sh print output files

---

tools/ib_read_lat.sh

Trimming allows aligning header and value rows
and get rid off preceding CSV column.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/619)

common: tools: ib_read_lat trim output

---

tools/ib_read.sh

Rename ib_read_lat.sh to ib_read.sh and make it
test ib_read_lat and ib_read_bw.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/617)

rpma: ib_read.sh tests ib_read_lat and ib_read_bw

---

tools/csv2standardized.py
tools/ib_read.sh
tools/rpma_read_lat.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/620)

common: tools: convert all CSVs to standardized-CSVs

---

tools/ib_read.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/622)

rpma: replace spaces with tabs in ib_read.sh

---

utils/check-area.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/623)

common: introduce 'tools' area name

---

utils/check-commit.sh

Ref: pmem/rpma#623
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/625)

common: introduce 'tools' area name (fix)

---

tools/ib_read.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/624)

tools: update ib_read.sh to measure bandwidth vs data size and threads

---

tools/ib_read.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/626)

tools: ib_read.sh indices start from 0 (fix)

---

tools/csv2standardized.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/628)

tools: use stdev instead of stddev (fix)

---

tools/csv2standardized.py
tools/ib_read.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/631)

tools: add support for ib_read_bw to csv2standardized.py

---

documentation/basic-direct-write-to-pmem.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/630)

doc: rectify typos

---

tools/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/627)

tools: compare all CSV columns at once

---

tools/csv2standardized.py
tools/ib_read.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/632)

tools: add threads to output of ib_read.sh

---

tools/ib_read.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/633)

tools: turn off TH=16 for ib_read_bw to avoid hang

---

tools/csv2standardized.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/634)

tools: round msg_rate to two decimal points

---

tools/csv2standardized.py

Requires:
- adding extraction of bw_* and numjobs to `fio_json2csv.py`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/635)

tools: add bw* and thread columns to FIO CSV processing

---

tools/fio_json2csv.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/636)

tools: add columns for: numjobs, bw

---

tools/csv2standardized.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/637)

tools: fix FIO input columns order

---

tools/csv2standardized.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/638)

tools: fix FIO output columns variable name

---

tools/csv2standardized.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/641)

tools: round bw_avg from ib

---

tools/ib_read.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/642)

tools: ib_read bw-bs add missing thread column

---

tools/csv2standardized.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/639)

tools: update standard CSV description

---

tools/csv2standardized.py

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/640)

tools: remove lat_mode and msg_rate ib*-specific output columns

---

tools/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/643)

tools: csv compare legend entries has to match the CSV files

---

tools/csv_compare.py

```sh
$ ./csv_compare.py --legend ib_read_bw --output_title "A show off of the new layout" \
ib_read_bw-ds-1th-20-12-08-221604.csv --output_layout bw_vs_bs
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/644)

tools: introduce a new csv compare layout (bw_vs_bs)

---

tools/ib_read.sh
tools/rpma_read_lat.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/645)

tools: replace DS (data size) with BS (block size)

---

tools/BENCHMARKING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/650)

tools: improving information on latency measurements

---

tools/BENCHMARKING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/651)

tools: improving information on bandwidth measurements

---

tools/csv_compare.py

```sh
$ ./csv_compare.py --output_layout lat ib_read_lat-20-12-09-144050.csv rpma_read_lat-20-12-09-162427.csv \
--output_with_tables --legend "ib_read" "rpma_read" --output_title "A show off of the output with tables"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/652)

tools: introduce --output_with_table for comparison

---

tools/ib_read.sh
tools/rpma_fio_read.sh

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/653)

rpma: replace spaces with tabs in tools/*.sh scripts

---

tools/ib_read.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/656)

tools: correct values of iterations after changing tx-depth

---

tools/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/657)

tools: skip only one DataFrame not all of them

---

tools/BENCHMARKING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/654)

tools: improve benchmarking.md file

---

tools/ib_read.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/648)

common: explicit message about EXPERIMENTAL nature of the script

---

tools/csv2standardized.py
tools/fio_jobs/librpma-client-read-bw.fio
tools/ib_read.sh
tools/rpma_fio_read.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/659)

tools: add new workload bw-dp for changing iodepth/tx-depth

---

tools/rpma_fio_read.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/660)

tools: display iodepth in rpma_fio_read.sh

---

tools/ib_read.sh
tools/rpma_fio_read.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/663)

tools: add bw-dp-lin mode, rename bw-dp to bw-dp-exp

---

tools/csv2standardized.py
tools/fio_json2csv.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/662)

tools: extract iodepth from FIO json output files

---

tools/csv_compare.py

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/666)

tools: allows bw(iodepth) plots

---

tools/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/670)

tools: fix syntax

---

tools/fio_jobs/librpma-client-bw.fio
tools/fio_jobs/librpma-client-lat.fio
tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/668)

tools: rpma_fio_bench.sh benchmarks reads and writes

---

tools/rpma_fio_bench.sh

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/671)

tools: set SUFFIX from MODE

---

tools/rpma_fio_bench.sh

Display a kind of operation (read or write) in rpma_fio_bench.sh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/673)

tools: display a kind of operation in rpma_fio_bench.sh

---

documentation/perf-tuning-latency.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/669)

doc: add settings for latency tuning

---

tools/BENCHMARKING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/667)

tools: complete the benchmarking.md file

---

tools/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/674)

tools: usec (fix)

---

tools/.gitignore
tools/create_report_figures.sh

Output:
```
report_CUSTOM_STAMP
├── 02_read_lat
│   ├── Appendix_B1_ib_read_lat.png
│   ├── Appendix_B2_rpma_read_lat_DRAM.png
│   ├── Appendix_B3_rpma_read_lat_PMEM.png
│   └── Figure_2_3_4_rpma_read_lat_vs_ib.png
├── 03_read_bw_bs
│   ├── Appendix_C1_ib_read_bw_bs.png
│   ├── Appendix_C2_rpma_read_bw_bs_dram.png
│   ├── Appendix_C3_rpma_read_bw_bs_pmem.png
│   └── Figure_5_rpma_read_bw_bs_vs_ib.png
└── 04_read_bw_th
├── Appendix_D1_ib_read_bw_th.png
├── Appendix_D2_rpma_read_bw_th_dram.png
├── Appendix_D3_rpma_read_bw_th_pmem.png
└── Figure_6_rpma_read_bw_th_vs_ib.png
```
Input:
```
data_path
└── READ
├── MACHINE_A
│   ├── DRAM
│   │   ├── BIOS_mem_BW
│   │   │   └── CSV
│   │   │       ├── ib_read_bw-bs-1th-20-12-10-151006.csv
│   │   │       ├── …
```

tools: introduce create_report_figures.sh

---

tools/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/676)

tools: print two decimal places

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/680)

tools: add job_mem to file name

---

tools/create_report_figures.sh

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/677)

tools: report figures for rpma_write() + rpma_flush()

---

tools/csv_compare.py

Add markers to the plotted lines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/684)

common: add markers to plotted lines

---

tools/ib_read.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/679)

tools: add 'all' options to ib_read.sh

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/678)

tools: add 'all' options to rpma_fio_bench.sh

---

tools/fio_jobs/librpma-client-bw.fio
tools/fio_jobs/librpma-client-lat.fio
tools/fio_jobs/librpma_gpspm-server.fio
tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/686)

tools: add fio job files for GPSPM mode

---

tools/rpma_fio_bench.sh

All of them have already been checked before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/687)

tools: remove redundant checks

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/688)

tools: add APM/GPSPM mode to rpma_fio_bench.sh

---

tools/csv_compare.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/689)

tools: crop bw charts

---

tools/create_report_figures.sh
tools/csv_compare.py

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/690)

tools: introduce lat_avg, lat_pctls* and lat_all layouts

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/692)

tools: add P_MODE to the NAME of the OUTPUT file

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/691)

tools: extend file name with meaningful information about workload

---

tools/BENCHMARKING.md

1) Rename rpma_fio_read.sh to rpma_fio_bench.sh
2) Rename REMOTE_JOB_MEM to REMOTE_JOB_MEM_PATH
3) Add two new options of rpma_fio_bench.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/696)

doc: Update BENCHMARKING.md

---

tools/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/701)

tools: standardize accessing dictionary entries

---

tools/.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/700)

tools: ignore *.png

---

tools/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/693)

tools: split lat_all layout in half

---

ROADMAP.md

Updated version to be seen here:
https://github.com/grom72/rpma/blob/roadmap/ROADMAP.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/702)

common: roadmap update (12/28/20)

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/707)

tools: save also server's errors in the log file

---

tools/create_report_figures.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/694)

tools: generate lat_avg and lat_pctls* separately

---

tools/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/705)

tools: wrap title

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/709)

tools: fix path to fio in script description

---

tools/create_report_figures.sh

Requires:
I see beautiful titles coming:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/704)

tools: include Figure and Appendix titles into generated report figures

---

tools/create_report_figures.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/710)

tools: create_report_figures.sh assumed directory structure

---

CONTRIBUTING.md
README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/706)

common: unify Note section formatting and remove bold from headers

---

tools/BENCHMARKING.md
tools/ib_read.sh
tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/716)

tools: make server_ip the first argument

---

tools/fio_jobs/librpma_gpspm-server.fio
tools/rpma_fio_bench.sh

... and remove sync=1 from the GPSPM server's job file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/718)

tools: set iodepth on the server's side

---

tools/fio_jobs/librpma_gpspm-server.fio

There is no such option in case of the GPSPM mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/719)

tools: remove num_conns from the GPSPM job file

---

tools/BENCHMARKING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/723)

tools: fix a mistake in BENCHMARKING.md

---

tools/ib_read.sh

Custom ib tool can be used by exporting $IB_PATH/$REMOTE_IB_PATH.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/715)

tools: Add custom path for ib tool

---

tools/BENCHMARKING.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/714)

tools: document how to gain ib tools and fio benchmark

---

tools/BENCHMARKING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/721)

tools: iterate over a plural number

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/711)

common: update the official library name

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/722)

tools: modify syntax of rpma_fio_bench.sh

---

tools/fio_jobs/librpma_gpspm-server.fio

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/728)

tools: fix blocksize in GPSPM server

---

tools/create_report_figures.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/724)

tools: create report figures without subdirectories

---

tools/create_report_figures.sh

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/725)

tools: drop MACHINE_ prefix for all X_Y_MACHINE variables

---

tools/create_report_figures.sh

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/726)

tools: provide figure no. by a separate param

---

tools/create_report_figures.sh

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/727)

tools: rename Figure_x_* to Figure_00x_*

---

tools/create_report.py
tools/templates/layout.html
tools/templates/report.md

e.g.:
```sh
$ ./create_report.py --report_dir ./report_trial/ --release 0.01
```
output:
```html
<html>
<head>
<title></title>
</head>
<body>
<h1>RPMA - Performance Report - Release 0.01</h1>
</body>
</html>
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/729)

tools: introduce create_report.py

---

tools/fio_jobs/librpma-client-bw.fio
tools/fio_jobs/librpma-client-lat.fio
tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/730)

tools: introduce SHORT_RUNTIME

---

tools/fio_jobs/librpma_gpspm-server.fio

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/731)

tools: GPSPM server MT job fix

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/732)

tools: introduce TRACER & REMOTE_TRACER

---

tools/BENCHMARKING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/735)

tools: doc: numactl, sshpass added to documentation

---

tools/rpma_fio_bench.sh

The custom part of the filename is taken from the environment variable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/733)

common: file comment from environment

---

tools/fio_jobs/librpma-client-bw.fio
tools/fio_jobs/librpma-client-lat.fio
tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/739)

tools: add support for mixed modes to rpma_fio_bench.sh

---

tools/rpma_fio_bench.sh

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/734)

An option to show all environment variables used by the tool

---

tools/fio_jobs/librpma-server.fio
tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/740)

tools: use the filename option instead of mem for APM

---

tools/fio_jobs/librpma-server.fio
tools/fio_jobs/librpma_gpspm-server.fio
tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/741)

tools: use numjobs instead of num_conns

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/744)

tools: change order of modes to more natural one

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/742)

tools: extend sleep interval between spawning server and client

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/745)

tools: JOB not JUB (fix typo)

---

src/include/librpma.h

C++ compilers compatibility
Ref: #738
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/743)

rpma: add extern C to the public header

---

examples/memcheck-libnl.supp
examples/memcheck-librdmacm.supp
examples/run-all-on-SoftRoCE.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/581)

test: valgrind test for all examples

---

tools/fio_jobs/librpma-client-bw.fio
tools/fio_jobs/librpma-client-lat.fio
tools/fio_jobs/librpma-server.fio
tools/fio_jobs/librpma_gpspm-server.fio
tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/750)

tools: replace hostname and bindname with serverip

---

tools/fio_jobs/librpma-server.fio
tools/fio_jobs/librpma_gpspm-server.fio
tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/753)

tools: add direct_write_to_pmem option

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/754)

tools: fix vales of the direct_write_to_pmem option

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/752)

tools: enable read for GPSPM

---

tools/fio_jobs/librpma-server.fio
tools/fio_jobs/librpma_gpspm-server.fio

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/757)

tools: turn on the straight units handling

---

examples/config_softroce.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/756)

examples: replace LINK with NET_IF

---

tools/fio_jobs/librpma-client-bw.fio
tools/fio_jobs/librpma-client-lat.fio
tools/fio_jobs/librpma-server.fio
tools/fio_jobs/librpma_gpspm-server.fio

- cleanup and fix comments
- drop blocksize, iomem_align and sync options for the server side
- reorganize accordin to the fio/examples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/759)

rpma: fix all job files

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/760)

tools: remove not supported mode

---

tools/rpma_fio_bench.sh

Rename the local OPS variable to RW_OPS
in order to not mix it with the global one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/761)

tools: rename the local OPS variable to RW_OPS

---

examples/config_softroce.sh

Requires: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/758)

examples: correct printing SoftRoCE-configured network interface

---

examples/config_softroce.sh

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/747)

exmaples: print out IP of SoftRoCE-configured network interface

---

tests/CMakeLists.txt
tests/cmake/ctest_helpers.cmake
tests/multithreaded/CMakeLists.txt
tests/multithreaded/utils/CMakeLists.txt
tests/multithreaded/utils/multithreaded-utils-rpma_utils_get_ibv_context_0.cmake
tests/multithreaded/utils/rpma_utils_get_ibv_context.c

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/672)

test: add librmpa API's multithreaded test

---

examples/06-multiple-connections/server.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/762)

examples: remove unused req argument for client_new()

---

tools/fio_jobs/librpma_apm-server.fio
tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/763)

tools: rename librpma to librpma_apm

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/766)

tools: add support for randread and randwrite

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/769)

tools: add StrictHostKeyChecking=no option to ssh

---

tools/create_report.py
tools/templates/.gitignore
tools/templates/header.md
tools/templates/layout.html
tools/templates/report.md

Requires:
Preview:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/765)

tools: use simple purecss layout for the report readability

---

tools/rpma_fio_bench.sh

file comment come from environment variable currently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/782)

tools: remove unused $5 argument

---

tools/ddio.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/774)

tools: do not fail ddio.sh when 'if' conditions are not met

---

tools/rpma_fio_bench.sh

**Note**: ib_read_bw hangs with 16 threads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/777)

tools: add 32 and 64 threads

---

tools/csv_compare.py

```sh
./csv_compare.py --output_layout bw --arg_axis iodepth --arg_xscale log *bw-dp-exp* --legend test
```
allows producing this: 
instead of this:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/778)

tools: introduce log_2 xscale layout

---

tools/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/779)

tools: introduce lat_pctls layout (99.9 and 99.999 pctls)

---

tools/templates/configuration_common.md.template

- PMem specific configuration
- RDMA-capable NIC (including MTU and protocol)
- storage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/776)

tools: add missing configuration elements (report)

---

tools/report_bench.sh

Ref: #781
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/784)

tools: report_bench.sh to all benchmarks required for the report (fix)

---

tools/report_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/785)

tools: report_bench.sh + READ BW

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/772)

tools: set up DDIO remotely via rpma_fio_bench.sh

---

tools/report_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/786)

tools: complete report_bench.sh scenarios

---

tools/rpma_fio_bench.sh

- following the FIO engines capabilities
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/780)

tools: allow malloc for GPSPM persist mode

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/787)

tools: fix alignment

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/789)

tools: fix case variable

---

tools/rpma_fio_bench.sh

Force setting REMOTE_DIRECT_WRITE_TO_PMEM
using FORCE_REMOTE_DIRECT_WRITE_TO_PMEM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/788)

tools: force setting REMOTE_DIRECT_WRITE_TO_PMEM

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/792)

tools: rpma_fio_bench.sh remove redundant assignments

---

tools/report_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/790)

tools: remove unnecesary exports report_bench.sh

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/794)

tools: REMOTE_DIRECT_WRITE_TO_PMEM not required when can be altered

---

tools/report_bench.sh
tools/rpma_fio_bench.sh

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/795)

tools: rename REMOTE_SUDO_NOPASSWD and build in its requirements

---

tools/report_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/791)

tools: use FORCE_REMOTE_DIRECT_WRITE_TO_PMEM for the baseline DRAM bench

---

tools/report_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/796)

tools: report_bench.sh stop on the first error

---

tools/ib_read.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/797)

tools: introduce SHORT_RUNTIME for ib_read.sh

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/798)

tools: running 64 threads on DRAM requires 15 sec delay

---

tools/ib_read.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/793)

tools: ib_read.sh adjust scales

---

documentation/perf-tuning-latency.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/799)

doc: add missing "CPU C State Control" and fix letter case

---

tools/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/804)

tools: layout lat_pctls add missing xscale (fix)

---

tools/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/806)

tools: add lat_pctls to the croppable layouts group

---

tools/templates/bios.md.template
tools/templates/configuration_common.md.template
tools/templates/configuration_target.md.template
tools/templates/layout.html
tools/templates/security.md.template

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/807)

tools: adjust the report menu and link to the headers

---

tools/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/805)

tools: name files output_1 and output_2 after the split

---

tools/rpma_fio_bench.sh

The retry procedure is supported by fio.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/809)

tools: remove waiting for server

---

tools/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/815)

tools: add a margin at the bottom of the chart (100px)

---

tools/csv_compare.py

+ move title a little bit closer to the content
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/816)

tools: scale the chart title size according to width of the chart

---

tools/BENCHMARKING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/801)

tools: update BENCHMARKING.md file

---

examples/01-connection/client.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/813)

examples: do not mix two styles of error handling

---

tools/ib_read.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/817)

tools: do not append to global AUX_PARAMS

---

tools/create_report_figures.sh

**Tip**: This script was almost completely rewritten. I recommend reading just the final shape since comparing it to what was here previously may be confusing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/803)

tools: create_report_figures.sh big revamp

---

tools/ib_read.sh
tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/821)

tools: introduce LOG_CMDS

---

tools/create_report.py
tools/templates/introduction.md.template
tools/templates/layout.html
tools/templates/report.md

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/808)

tools: add introduction to the report

---

tools/create_report.py
tools/templates/.gitignore
tools/templates/layout.html
tools/templates/report.md
tools/templates/tc1_read.md
tools/templates/tc2_write.md
tools/templates/tc3_mix.md
tools/templates/tc_config_dummy.md

- XXX workload configs are still missing (dummy)
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/814)

tools: add all report parts

---

tools/fio_jobs/librpma-client-bw.fio
tools/fio_jobs/librpma-client-lat.fio
tools/fio_jobs/librpma_gpspm-server.fio

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/825)

tools: remove iomem_align from the FIO job files

---

tools/create_report.py
tools/templates/tc2_write.md
tools/templates/tc3_mix.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/826)

tools: add proper write/mix config

---

tools/templates/layout.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/827)

tools: remove the introduction menu entry duplicate

---

tools/templates/introduction.md.template

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/830)

tools: introduction: fix the Figure 0 reference

---

tools/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/834)

tools: choose the chart title location conditionally

---

tools/create_report.py
tools/templates/introduction.md.template

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/828)

tools: rename Figure_0 to Figure_000

---

tools/create_report.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/832)

tools: introduce two separate execution paths: report and appendices

---

tools/templates/tc1_read.md
tools/templates/tc2_write.md
tools/templates/tc3_mix.md

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/831)

 tools: add test case descriptions

---

documentation/perf-tuning-latency.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/837)

doc: describe paragraph running workloads

---

tools/create_report.py
tools/templates/layout.html

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/833)

tools: take out the menu from the layout to a dedicated file

---

_layouts/pmdk.html

Preview: https://janekmi.github.io/rpma/documentation/basic-direct-write-to-pmem.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/839)

doc: make the main layout h3 RPMA-specific

---

tools/rpma_fio_bench.sh

Avoid the following error:
```
serverip=192.168.122.220: command not found
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/836)

tools: run local command by bash -c

---

tools/rpma_fio_bench.sh

It is unnecessary to set up DDIO in a loop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/823)

tools: move DDIO's steps out of the loop

---

documentation/basic-direct-write-to-pmem.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/841)

doc: replace 'tree like' with 'tree-like'

---

tools/BENCHMARKING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/840)

tools: improve BENCHMARKING.md

---

documentation/basic-hw_sw_setup_starting_point.md
index.md

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/824)

doc: HW & SW setup starting point description

---

documentation/perf-tuning.md
index.md

Preview: https://janekmi.github.io/rpma/documentation/perf-tuning.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/844)

doc: performance tuning - cleanup

---

tools/templates/.gitignore
tools/templates/report_menu.html

Ref: #833
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/843)

tools: take out the menu from the layout to a dedicated file (fix)

---

documentation/basic-direct-write-to-pmem.md
index.md

Preview: https://janekmi.github.io/rpma/documentation/basic-direct-write-to-pmem.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/842)

doc: Direct Write to PMem - cleanup

---

tools/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/846)

tools: unify the 'filename' option

---

tests/multithreaded/utils/rpma_utils_get_ibv_context.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/849)

test: fix memory leaks during error handling

---

tools/create_report_figures.sh
tools/csv_compare.py
tools/ib_read.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/855)

tools: fix typos found by codespell

---

tests/multithreaded/utils/rpma_utils_get_ibv_context.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/847)

test: use strncpy() instead of strcpy()

---

tests/multithreaded/utils/rpma_utils_get_ibv_context.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/857)

test: fix error handling in the rpma_utils-get_ibv_context.c test

---

examples/10-send-with-imm/client.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/862)

examples: goto err_conn_disconnect when cmpl.op_status != IBV_WC_SUCCESS

---

tests/cmake/ctest_helpers.cmake

Add the GROUP_SCRIPT option to add_test_generic()
and refactor it to make it more clear.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/865)

test: add GROUP_SCRIPT option to add_test_generic()

---

documentation/perf-tuning.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/864)

doc: fix link to BENCHMARKING.md after moving it to perf

---

utils/mans_header.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/876)

common: fix rpma API version (from 0.0 to 0.9.0)

---

examples/10-send-with-imm/client.c
examples/10-send-with-imm/server.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/874)

examples: add void for functions ignoring the return value

---

documentation/basic-direct-write-to-pmem.md
documentation/basic-hw_sw_setup_starting_point.md
documentation/perf-tuning.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/878)

doc: disclaimer moved to the end of file

---

tools/perf/BENCHMARKING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/872)

tools: add dependencies to reporting tools

---

examples/10-send-with-imm/client.c
examples/10-send-with-imm/server.c
examples/run-all-on-SoftRoCE.sh
src/conn.c
src/include/librpma.h
src/mr.c
src/mr.h
tests/unit/common/mocks-rpma-mr.c
tests/unit/conn/conn-send.c
tests/unit/conn/conn-send_with_imm.c
tests/unit/mr/mr-send.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/869)

rpma: send 0B massage

---

tests/unit/conn/conn-send.c
tests/unit/conn/conn-send_with_imm.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/883)

test: add missing rpma_conn_send tests

---

tools/perf/create_report.py
tools/perf/templates/disclaimer.md
tools/perf/templates/report.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/880)

tools: add a disclaimer to the report

---

examples/01-connection/server.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/886)

examples: do not abort on wrong arguments

---

examples/10-send-with-imm/client.c
examples/10-send-with-imm/server.c
examples/11-write-with-imm/client.c
examples/11-write-with-imm/server.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/887)

examples: change style of some messages

---

src/conn.c
src/include/librpma.h
src/mr.c
src/mr.h
tests/unit/common/mocks-rpma-mr.c
tests/unit/conn/conn-read.c
tests/unit/conn/conn-write.c
tests/unit/conn/conn-write_with_imm.c
tests/unit/mr/mr-read.c
tests/unit/mr/mr-write.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/882)

rpma: rpma_write/read 0B message

---

.github/workflows/nightly.yml
.github/workflows/nightly_rebuild.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/895)

common: move jobs with rebuild to a separate workflow

---

tests/unit/common/mocks-ibverbs.c
tests/unit/common/mocks-ibverbs.h
tests/unit/mr/mr-common.h
tests/unit/mr/mr-read.c
tests/unit/mr/mr-write.c

Requires:
Ref: #889 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/893)

test: verify remote_addr and rkey values in the ibv_post_send_mock()

---

src/conn.c
src/include/librpma.h
src/mr.c
src/mr.h
tests/unit/common/mocks-rpma-mr.c
tests/unit/conn/conn-recv.c
tests/unit/mr/mr-recv.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/892)

rpma: rpma_recv 0B message

---

src/include/librpma.h
src/mr.h
tests/unit/common/mocks-rpma-mr.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/896)

add missing asserts in mock-rpma-mr and standardize the documentation

---

tests/unit/common/mocks-ibverbs.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/899)

test: verify imm_data for IBV_WR_RDMA_WRITE_WITH_IMM

---

tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/900)

test: correct some messages in rpma_utils_ibv_context_is_odp_capable.c

---

examples/04-write-to-persistent/client.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/903)

examples: fix expected completion's op in the 04 example

---

examples/08-messages-ping-pong/server.c
examples/09-flush-to-persistent-GPSPM/server.c
examples/10-send-with-imm/server.c
examples/11-write-with-imm/server.c
examples/common/common-conn.c
tests/unit/conn/conn-completion_get.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/906)

common: fix typo in "unexpected"

---

examples/01-connection/client.c
examples/01-connection/server.c
examples/08-messages-ping-pong/server.c
examples/09-flush-to-persistent-GPSPM/server.c
examples/10-send-with-imm/server.c
examples/11-write-with-imm/server.c
examples/common/common-conn.c
tests/unit/conn/conn-completion_get.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/907)

examples: print out the unexpected event

---

tools/perf/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/915)

tools: add not supported mode for gpspm

---

tools/perf/fio_jobs/librpma_aof_hw-client.fio
tools/perf/fio_jobs/librpma_aof_hw-server.fio
tools/perf/fio_jobs/librpma_aof_sw-client.fio
tools/perf/fio_jobs/librpma_aof_sw-server.fio
tools/perf/fio_jobs/librpma_apm-client.fio
tools/perf/fio_jobs/librpma_gpspm-client.fio
tools/perf/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/914)

tools: add aof option for rpma_fio_bench tool

---

tools/perf/fio_jobs/librpma_aof_hw-server.fio

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/917)

tools: remove time_based from librpma_aof_hw-server.fio

---

examples/10-send-with-imm/README.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/918)

examples: update 10-send-with-imm's README.md

---

doc/manuals_3.txt
src/conn_req.c
src/include/librpma.h
src/librpma.map
tests/unit/conn_req/CMakeLists.txt
tests/unit/conn_req/conn_req-private_data.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/911)

rpma: add rpma_conn_req_get_private_data()

---

examples/06-multiple-connections/server.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/916)

examples: add missing rpma_conn_delete() to 06 example

---

examples/common/common-epoll.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/920)

examples: call perror() if fcntl() fails

---

tools/perf/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/922)

tools: start y-axis from 0

---

tools/perf/BENCHMARKING.md
tools/perf/create_report_figures.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/928)

tools: introduce a REPORT_MACHINE variable

---

tools/perf/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/927)

tools: y-axis max

---

tools/perf/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/926)

tools: add pctl_99999 layout

---

tools/perf/csv_compare.py

Ref: #927
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/932)

tools: y-axis max (fix)

---

tools/perf/create_report_figures.sh
tools/perf/csv_compare.py

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/929)

tools: introduce 'cmp' figures generator mode

---

tools/perf/report_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/930)

tools: adapt script report_bench.sh to run on ICX

---

tools/perf/report_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/931)

tools: add option to run aof workloads in report_bench.sh

---

tools/perf/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/933)

tools: introduce REMOTE_CMD_PRE/_POST

---

tools/perf/fio_jobs/librpma_apm-server.fio
tools/perf/fio_jobs/librpma_gpspm-server.fio
tools/perf/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/937)

tools: add cpuload option to server

---

tools/perf/fio_json2csv.py
tools/perf/rpma_fio_bench.sh

- add `--extra` to fio_json2csv.py
- pass the cpuload to the output
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/938)

tools: pass cpuload to the output fio csv file

---

tools/perf/report_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/941)

tools: add f(cpuload) to report_bench.sh

---

tools/perf/fio_jobs/librpma_apm-server.fio
tools/perf/fio_jobs/librpma_gpspm-server.fio
tools/perf/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/940)

tools: set the actual number of cores

---

tools/perf/rpma_fio_bench.sh

Ref: #938
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/943)

tools: pass cpuload to the output fio csv file (fix)

---

tools/perf/report_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/946)

tools: test both BUSY_WAIT_POLLING variants in the WRITE LAT/BW benchmark

---

tools/perf/csv_compare.py

Useful for performing dry-runs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/949)

tools: allow csv_compare.py reading empty files

---

tools/perf/ib_read.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/948)

tools: separate ibv_read.sh output name sections with `_`

---

tools/perf/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/934)

tools: save results of sar in a separate file for each run

---

tools/perf/ib_read.sh
tools/perf/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/947)

tools: introduce DO_NOTHING for ib_read.sh and rpma_fio_bench.sh

---

tools/perf/create_report_figures.sh
tools/perf/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/951)

tools: introduce lat_avg(cpuload) and lat_pctls(cpuload)

---

tools/perf/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/952)

tools: rename the output file

---

tools/perf/create_report_figures.sh

Ref: #952
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/953)

tools: adapt to modified naming convention

---

tools/perf/csv_compare.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/954)

tools: decrease legend fontsize to 6px

---

tools/perf/create_report_figures.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/955)

tools: rename GPSPM busy-wait to GPSPM-rt

---

tests/multithreaded/CMakeLists.txt
tests/multithreaded/peer/CMakeLists.txt
tests/multithreaded/peer/rpma_peer_cfg_new.c
tests/multithreaded/utils/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/902)

test: add rpma_peer_cfg_new multithreaded test

---

tools/perf/rpma_fio_bench.sh

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/935)

tools: add REMOTE_SAR_RESULTS_DIR to REMOTE_CMD_PRE/POST

---

tests/unit/mr/mr-descriptor.c

test function and setup/teardown function should have the same argument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/924)

test: pass the correct argument into test function

---

tools/perf/fio_jobs/librpma_aof_hw-server.fio
tools/perf/fio_jobs/librpma_aof_sw-server.fio

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/956)

tools: add cpuio and busy_wait_polling to AOF server fio job files

---

tools/perf/report_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/944)

tools: add f(cpuload) to the AOF mode in report_bench.sh

---

tools/perf/rpma_fio_bench.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/960)

tools: add EMON commands to REMOTE_CMD_PRE/POST + fixes

---

tools/perf/templates/tc_mix_bw_config.md.copyme
tools/perf/templates/tc_mix_lat_config.md.copyme
tools/perf/templates/tc_read_bw_config.md.copyme
tools/perf/templates/tc_read_lat_config.md.copyme
tools/perf/templates/tc_write_bw_config.md.copyme

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/962)

tools: add default configurations to copyme files

---

tools/perf/templates/tc_mix_bw_config.md.copyme
tools/perf/templates/tc_mix_lat_config.md.copyme
tools/perf/templates/tc_read_bw_config.md.copyme
tools/perf/templates/tc_read_lat_config.md.copyme
tools/perf/templates/tc_write_bw_config.md.copyme
tools/perf/templates/tc_write_lat_config.md.copyme

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/963)

 tools: add a GPSPM(-RT) configuration differentiation

---

tools/perf/create_report_figures.sh

- fix file name wildcards
- add GPSPM(-RT) differentiation to appendices
- rename GPSPM-rt to GPSPM-RT
- change "GPSPM" to "GPSPM-RT" in Figure titles
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/964)

tools: adjust create_report_figures.sh

---

tools/perf/templates/introduction.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/967)

tools: report: do not mix multiple NUMAs for RPMA use (soft)

---

tools/perf/templates/tc2_write.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/968)

tools: report: "sequence of"

---

tools/perf/templates/tc2_write.md

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/969)

tools: report: introduce GPSPM(-RT) differentiation
