tools/perf/ib_read.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/971)
=> tools: add emon to ib_read.sh

doc/manuals_3.txt, src/include/librpma.h, src/librpma.map, src/mr.c, tests/unit/mr/CMakeLists.txt, tests/unit/mr/mr-local.c
Ref #870
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/925)
=> rpma: add rpma_mr_get_ptr() and rpma_mr_get_size()

tests/multithreaded/peer/CMakeLists.txt, tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/961)
=> test: add rpma_peer_cfg_from_descriptor multithreaded test

examples/08-messages-ping-pong/client.c, examples/08-messages-ping-pong/server.c
A completion can arrive prior to `rpma_conn_completion_wait()`
is called and then the example hangs on `rpma_conn_completion_wait()`.
`rpma_conn_completion_get()` has to be called before
`rpma_conn_completion_wait()` in order to get previously received
completions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/982)
=> examples: fix the 08-messages-ping-pong example

.circleci/config.yml, .circleci/install-pkgs-ubuntu.sh, CMakeLists.txt, examples/README.md, tools/config_softroce.sh, utils/docker/images/install-cmocka.sh
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/980)
=> common: add CircleCI build with SoftRoCE support

.circleci/install-pkgs-ubuntu.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/988)
=> common: CircleCI: install packages with debug symbols

ROADMAP.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/983)
=> rpma: cleanup the ROADMAP.md

tests/cmake/ctest_helpers.cmake, tests/multithreaded/common/mtt.c, tests/multithreaded/common/mtt.h, tests/multithreaded/utils/rpma_utils_get_ibv_context.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/981)
=> tests: introduce "framework" for MT tests

examples/07-atomic-write/client.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/993)
=> examples: verify FLUSH_ID in 07-atomic-write

.circleci/config.yml, tests/cmake/ctest_helpers.cmake, tests/cmake/helpers.cmake, tests/drd.supp, tests/helgrind.supp
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/984)
=> test: add MT helgrind and drd tests to CircleCI

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1001)
=> common: add the CircleCI build status badge and remove the Travis CI one

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1002)
=> common: use the shield style of the CircleCI badge, not the svg one

examples/07-atomic-write/client.c
based on #982
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/998)
=> examples: fix the 07-atomic-write example

tests/multithreaded/CMakeLists.txt, tests/multithreaded/example/CMakeLists.txt, tests/multithreaded/example/example.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1000)
=> test: mt: introduce an example test

.github/workflows/nightly_experimental.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1013)
=> common: rename one build in Nightly_Experimental

tests/drd.supp, tests/helgrind.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1006)
=> test: librdmacm / ucma_init() / cma_dev_cnt race assesment

tools/perf/csv_compare.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1015)
=> tools: perf: adjust figure title width

tools/perf/create_report_figures.sh, tools/perf/csv_compare.py
When 99.999 will be stabilized this change can be reverted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1014)
=> tools: perf: change 99.999 to 99.99 in the Perf Report

tools/perf/create_report.py, tools/perf/templates/appendices.md, tools/perf/templates/report.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1016)
=> tools: perf: add a reference number for both the report and appendices

tests/multithreaded/common/mtt.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1012)
=> test: mt: the function pointers documentation

tests/multithreaded/peer/CMakeLists.txt, tests/multithreaded/peer/rpma_peer_new.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1008)
=> test: add rpma_peer_new multithreaded test

tests/multithreaded/common/mtt.c, tests/multithreaded/common/mtt.h
Take the mtt_base_file_name defintion to mtt.c.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1018)
=> test: mt: simplify the mtt.h header

tests/multithreaded/common/mtt.c, tests/multithreaded/common/mtt.h, tests/multithreaded/example/example.c, tests/multithreaded/peer/rpma_peer_new.c, tests/multithreaded/utils/rpma_utils_get_ibv_context.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1019)
=> test: mt: introduce init/fini for prestate

tests/helgrind.supp
Ref: #1006
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1020)
=> test: librdmacm / ucma_init() / cma_dev_cnt race assesment (fix)

tools/perf/bench_common.sh, tools/perf/ib_read.sh, tools/perf/report_bench.sh, tools/perf/rpma_fio_bench.sh
+ set ddio in ib_read.sh 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/974)
=>  tools: separate the common part of the scripts for benchmarking

tests/multithreaded/peer/rpma_peer_new.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1021)
=> test: remove unneeded headers

tools/perf/create_report_figures.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1027)
=> tools: perf: allow relative DATA_PATH

tools/perf/csv_compare.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1028)
=> tools: perf: add missing "CPU load [%]" label

tests/multithreaded/CMakeLists.txt, tests/multithreaded/common/mtt.c, tests/multithreaded/common/mtt.h, tests/multithreaded/ep/CMakeLists.txt, tests/multithreaded/ep/rpma_ep_listen.c, tests/multithreaded/run_group.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1017)
=> test: add rpma_ep_listen multithreaded test

tools/perf/report_bench.sh
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1034)
=> tools: perf: split report bench into apm_gpsm, apm_gpspm_cpu and aof

tools/perf/create_report.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1031)
=> tools: perf: allow variables for html contents

tools/perf/create_report.py, tools/perf/templates/report.md, tools/perf/templates/report_menu.html, tools/perf/templates/tc4_cpu.md, tools/perf/templates/tc_cpu_bw_config.md.copyme, tools/perf/templates/tc_cpu_lat_config.md.copyme
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1032)
=> tools: perf: introduce a "CPU load impact" part to the report

tests/multithreaded/ep/CMakeLists.txt, tests/multithreaded/ep/rpma_ep_get_fd.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1022)
=>  test: add rpma_ep_get_fd multithreaded test

tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1025)
=> test: rpma_utils_ibv_context_is_odp_capable multithreaded test

tests/drd.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1039)
=> test: add missing suppression for drd

tests/multithreaded/common/mtt.c, tests/multithreaded/common/mtt.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1036)
=> test: add possibility to start a server in the MT test framework

tests/drd.supp, tests/helgrind.supp, tests/multithreaded/CMakeLists.txt, tests/multithreaded/common/mtt.c, tests/multithreaded/common/mtt.h, tests/multithreaded/mr/CMakeLists.txt, tests/multithreaded/mr/rpma_mr_reg.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1033)
=>  test: add rpma_mr_reg multithreaded test

tests/drd.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1041)
=> test: fix drd suppressions

tests/cmake/ctest_helpers.cmake, tests/multithreaded/CMakeLists.txt, tests/multithreaded/common/mtt.h, tests/multithreaded/conn/CMakeLists.txt, tests/multithreaded/conn/rpma_conn_get_private_data.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1037)
=> test: add the rpma_conn_get_private_data MT test

tools/perf/create_report_figures.sh, tools/perf/csv_compare.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1042)
=> tools: perf: introduce cpuload appendices

.github/workflows/nightly.yml, .github/workflows/nightly_rebuild.yml, utils/docker/images/Dockerfile.archlinux-latest
The 'archlinux-base' image was renamed to 'archlinux' on Docker Hub.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1043)
=> common: fix Arch Linux job in GHA CI

tests/helgrind.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1045)
=> test: fix helgrind suppressions

tools/perf/create_report_figures.sh, tools/perf/templates/tc4_cpu.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1046)
=> tools: perf: generate CPU-related report figures

tools/perf/bench_common.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1047)
=> tools: add emon -stop command in blocking mode

tools/perf/create_report_figures.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1051)
=> tools: perf: introduce LAT_YAXIS_MAX to the report figures generator

tools/perf/bench_common.sh, tools/perf/create_report_figures.sh, tools/perf/report_bench.sh, tools/perf/rpma_fio_bench.sh, tools/perf/templates/appendices.md, tools/perf/templates/tc4_cpu.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1053)
=> tools: cpu load up to 99% only

tools/perf/create_report_figures.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1055)
=> tools: perf: introduce AoF report & appendices figures

tools/perf/report_bench.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1056)
=> tools: add cpu_load to AOF runs

tests/multithreaded/common/mtt.h, tests/multithreaded/mr/CMakeLists.txt, tests/multithreaded/mr/rpma_mr_get_descriptor.c, tests/multithreaded/mr/rpma_mr_reg.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1038)
=> test: add rpma_mr_get_descriptor multithreaded test

tests/multithreaded/mr/CMakeLists.txt, tests/multithreaded/mr/rpma_mr_get_ptr.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1060)
=> test: add rpma_mr_get_ptr multithreaded test

tools/perf/figures/read.json, tools/perf/lib/Figure.py, tools/perf/lib/flat.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1068)
=> tools: perf: allow not flat figures descriptions

tools/perf/config.json.example, tools/perf/lib/Bench.py, tools/perf/lib/Benchmark.py, tools/perf/lib/Requirement.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1073)
=>  tools: perf: Benchmark args and env implementation

tools/perf/config.json.example, tools/perf/lib/Bench.py, tools/perf/lib/Requirement.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1071)
=>  tools: perf: implement Requirement.is_met()

tools/perf/lib/Figure.py
Ref: #1065
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1076)
=> tools: perf: Figure.py (small fix)

tools/perf/config.json.example, tools/perf/figures/read.json, tools/perf/lib/Bench.py, tools/perf/lib/Figure.py, tools/perf/lib/Part.py, tools/perf/lib/Report.py, tools/perf/lib/kvtable.py, tools/perf/report_create.py, tools/perf/report_figures.py, tools/perf/templates/part_read.json, tools/perf/templates/part_read.md
Requires:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1075)
=> tools: perf: report_create.py scaffolding

tests/multithreaded/mr/CMakeLists.txt, tests/multithreaded/mr/rpma_mr_get_size.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1062)
=> test: add rpma_mr_get_size multithreaded test

tests/multithreaded/conn/CMakeLists.txt, tests/multithreaded/conn/rpma_conn_cfg_new.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1063)
=> test: add rpma_conn_cfg_new multithreaded test

tests/multithreaded/conn/CMakeLists.txt, tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1064)
=> test: add rpma_conn_cfg_set_timeout multithreaded test

tests/drd.supp, tests/helgrind.supp, tests/multithreaded/conn/CMakeLists.txt, tests/multithreaded/conn/rpma_conn_req_new.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1058)
=> test: add rpma_conn_req_new multithreaded test

tools/perf/lib/Bench.py, tools/perf/lib/Benchmark.py, tools/perf/lib/Requirement.py, tools/perf/report_bench.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1083)
=> tools: perf: introduce report_bench.py --dump mode

tools/perf/lib/Figure.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1082)
=> tools: convert x/y args into labels

.github/workflows/gha.yml, .github/workflows/nightly.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1091)
=> common: move Debian9 from Nightly to the per-PR builds

tests/cmake/ctest_helpers.cmake, tests/multithreaded/common/mtt.h, tests/multithreaded/conn/CMakeLists.txt, tests/multithreaded/conn/rpma_conn_get_private_data.c, tests/multithreaded/conn/server_rpma_conn_get_private_data.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1048)
=> test: add own server for the rpma_conn_get_private_data MT test

tools/perf/BENCHMARKING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1105)
=> tools: fix a typo

tools/perf/create_report_figures.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1095)
=> tools: perf: fix figs no. 5 & 6 (ib_read_bw instead of _lat)

tests/unit/conn/conn-disconnect.c, tests/unit/conn/conn-new.c, tests/unit/conn/conn-next_event.c, tests/unit/conn_cfg/conn_cfg-new.c, tests/unit/conn_req/conn_req-connect.c, tests/unit/conn_req/conn_req-delete.c, tests/unit/conn_req/conn_req-from_cm_event.c, tests/unit/conn_req/conn_req-new.c, tests/unit/cq/cq-new_delete.c, tests/unit/flush/flush-new.c, tests/unit/info/info-bind_addr.c, tests/unit/info/info-common.h, tests/unit/info/info-new.c, tests/unit/info/info-resolve_addr.c, tests/unit/mr/mr-descriptor.c, tests/unit/mr/mr-reg.c, tests/unit/peer/peer-create_qp.c, tests/unit/peer/peer-mr_reg.c, tests/unit/peer/peer-new.c, tests/unit/peer_cfg/peer_cfg-descriptor.c, tests/unit/peer_cfg/peer_cfg-new.c, tests/unit/private_data/private_data-store.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1093)
=> test: use simulated errno on all unit tests

INSTALL.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1096)
=> doc: add pylint to INSTALL.md

tools/perf/figures/write.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1090)
=> tools: add write.json

tests/multithreaded/conn/CMakeLists.txt, tests/multithreaded/conn/rpma_conn_cfg_common.c, tests/multithreaded/conn/rpma_conn_cfg_common.h, tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1097)
=> test: add rpma_conn_cfg_set_cq_size multithreaded test

cmake/functions.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1110)
=> common: add missing dependencies for add_cstyle_pep8()

tests/multithreaded/conn/CMakeLists.txt, tests/multithreaded/conn/rpma_conn_cfg_set_rq_size.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1099)
=> test: add rpma_conn_cfg_set_rq_size multithreaded test

tools/perf/ib_read.sh
Ref: #964
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1107)
=> tools: perf: adjust output csv file names according to #964

tools/perf/csv2standardized.py, tools/perf/fio_json2csv.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1111)
=> tools: push IOPS to fio-csv output

tests/multithreaded/conn/CMakeLists.txt, tests/multithreaded/conn/rpma_conn_cfg_set_sq_size.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1098)
=> test: add rpma_conn_cfg_set_sq_size multithreaded test

tests/multithreaded/conn/CMakeLists.txt, tests/multithreaded/conn/rpma_conn_cfg_common.c, tests/multithreaded/conn/rpma_conn_cfg_common.h, tests/multithreaded/conn/rpma_conn_cfg_get_cq_size.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1100)
=> test: add rpma_conn_cfg_get_cq_size multithreaded test

tests/helgrind.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1026)
=> test: add missing suppression for Helgrind

tools/perf/lib/Bench.py, tools/perf/lib/Figure.py, tools/perf/lib/common.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1106)
=> tools: add path of the input file to the json_from_file() output

tools/perf/lib/Bench.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1108)
=> tools: store figure/part name using data['input_file']

tools/perf/lib/Figure.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1113)
=> tools: implement Figure.html_data_table()

tools/perf/lib/Figure.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1114)
=> tools: implement Figure.to_html()

tests/multithreaded/conn/CMakeLists.txt, tests/multithreaded/conn/rpma_conn_cfg_get_sq_size.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1101)
=> test: add rpma_conn_cfg_get_sq_size multithreaded test

tests/multithreaded/conn/CMakeLists.txt, tests/multithreaded/conn/rpma_conn_cfg_get_rq_size.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1102)
=> test: add rpma_conn_cfg_get_rq_size multithreaded test

tests/multithreaded/conn/CMakeLists.txt, tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1103)
=> test: add rpma_conn_cfg_get_timeout multithreaded test

tools/perf/.gitignore, tools/perf/CMakeLists.txt, tools/perf/tests/__init__.py, tools/perf/tests/lib/__init__.py, tools/perf/tests/lib/kvtable/__init__.py, tools/perf/tests/lib/kvtable/test_lines2str.py, tools/perf/tests/test_report_bench.py, tools/perf/tests/test_report_create.py, tools/perf/tests/test_report_figures.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1121)
=> tools: introduce Python tools tests structure

tools/perf/lib/kvtable.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1119)
=> tools: kvtable.lines2str(): check if 'lines' is iterable

tools/perf/CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1122)
=> tools: CONTRIBUTING.md

tools/perf/lib/kvtable.py, tools/perf/tests/lib/kvtable/test_lines2str.py
Requires:
Ref:
- a lot easier to review in the context of #1122
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1123)
=> tools: docstring and unittests for kvtable.lines2str()

tools/perf/rpma_fio_bench.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1127)
=> tools: verify the path of fio

tools/perf/bench_common.sh, tools/perf/ib_read.sh, tools/perf/rpma_fio_bench.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1126)
=> tools: set DIR for the ddio.sh script

tools/perf/ib_read.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1128)
=> tools: verify path to the IB tool

tools/perf/tests/lib/bench/__init__.py, tools/perf/tests/lib/benchmark/__init__.py, tools/perf/tests/lib/common/__init__.py, tools/perf/tests/lib/figure/__init__.py, tools/perf/tests/lib/flat/__init__.py, tools/perf/tests/lib/part/__init__.py, tools/perf/tests/lib/report/__init__.py, tools/perf/tests/lib/requirement/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1130)
=> tools: add all lib.* unittests directories

tools/perf/lib/Bench.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1125)
=> tools: make high_level_setup_figure path absolute

tools/perf/lib/Benchmark.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1132)
=> tools: add checks to Benchmark.run()

tools/perf/lib/Figure.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1133)
=> tools: control xscale

tools/perf/lib/Benchmark.py, tools/perf/tests/lib/benchmark/test_run.py, utils/pylint.rc
Requires:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1129)
=> tools: Benchmark.run() unittests and docstring

tools/perf/lib/Part.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1116)
=> tools: implement Part._load_variables()

tools/perf/lib/Part.py, tools/perf/tests/lib/part/test_init.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1134)
=> tools: Part.__init__() unittests and docstring

tools/perf/lib/Benchmark.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1135)
=> tools: add error messages to Benchmark.run()

tools/perf/figures/read.json, tools/perf/figures/write.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1117)
=> tools: improve read/write.json

tests/unit/conn/conn-new.c, tests/unit/conn/conn-next_event.c, tests/unit/conn_req/conn_req-from_cm_event.c, tests/unit/conn_req/conn_req-new.c, tests/unit/mr/mr-common.c, tests/unit/mr/mr-descriptor.c, tests/unit/mr/mr-reg.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1109)
=> test: fix the usage of will_return_maybe() in unit tests 

tools/perf/lib/Report.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1147)
=> tools: perf: lib/Report.py add missing os import

tools/perf/figures/read.json, tools/perf/templates/part_read.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1146)
=> tools: perf: harmonize names and keys for the read part

tools/perf/fio_jobs/librpma_aof_hw-server.fio, tools/perf/fio_jobs/librpma_aof_sw-server.fio, tools/perf/fio_jobs/librpma_apm-server.fio, tools/perf/fio_jobs/librpma_gpspm-server.fio, tools/perf/rpma_fio_bench.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1144)
=> tools: perf: adapt to fs-dax mode

tools/perf/lib/Figure.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1137)
=> tools: print a message if the series does not have the required keys

tools/perf/lib/Benchmark.py, tools/perf/report_bench.py, tools/perf/tests/lib/benchmark/test_run.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1153)
=> tools: perf: allow generating random results --dummy_results

tests/unit/ep/CMakeLists.txt, tests/unit/ep/ep-common.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1152)
=> test: remove duplicate __wrap__test_malloc()

tools/perf/lib/Figure.py, tools/perf/tests/lib/figure/test_oneseries_derivatives.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1161)
=> tools: fix setting rw_order

tools/perf/lib/Part.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1163)
=> tools: fix fstring in _load_template

tools/perf/lib/Figure.py, tools/perf/tests/lib/figure/test_html_data_table.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1162)
=> tools: perf: Figure.series[] is a dictionary (fix)

utils/docker/images/Dockerfile.debian-9, utils/docker/images/Dockerfile.fedora-32, utils/docker/images/Dockerfile.ubuntu-20.04, utils/docker/run-build.sh
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1164)
=>  common: run pytest in CI builds

tools/perf/lib/Figure.py, tools/perf/tests/lib/figure/test_html_data_table.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1168)
=> tools: fix formatting in html_data_table()

tests/tools/perf/kvtable/test_dict2kvtable.py, tools/perf/lib/kvtable.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1169)
=> tools: fix formatting in dict2kvtable()

tests/tools/perf/kvtable/test_dict2kvtable.py, tools/perf/lib/kvtable.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1171)
=> tools: add pre to the right column of configuration tables

tools/perf/figures/read.json, tools/perf/figures/write.json, tools/perf/lib/Figure.py, tools/perf/lib/common.py, tools/perf/tests/lib/common/test_str2key.py, tools/perf/tests/lib/figure/test_oneseries_derivatives.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1173)
=> tools: perf: introduce x_key and y_key derivatives

tools/perf/lib/Report.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1174)
=> tools: perf: include config['report'] into the header

tools/perf/lib/Figure.py, tools/perf/lib/Report.py, tools/perf/tests/lib/figure/test_png_path.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1177)
=> perf: use relative image paths instead of absolute

tools/perf/config.json.example, tools/perf/lib/Report.py, tools/perf/templates/part_preamble.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1178)
=> tools: add authors to the preamble

tools/perf/lib/Figure.py, tools/perf/report_figures.py
See the commit: c420a64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1182)
=> tools: remove redundant arguments (fix)

tools/perf/config.json.example, tools/perf/lib/Part.py, tools/perf/lib/Report.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1179)
=> tools: add configuration.bios.settings to the preamble

tools/perf/config.json.example, tools/perf/lib/Report.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1180)
=> tools: add configuration common, target and bios.excerpt to the preamble

tools/perf/lib/Figure.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1188)
=> tools: change working directory before generating figures

tools/perf/bench_common.sh, tools/perf/ib_read.sh, tools/perf/rpma_fio_bench.sh
don't mess up the unique outputs of rpma_fio_bench.sh and ib_read.sh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1131)
=> tools: separate the unique outputs of rpma_fio_bench.sh and ib_read.sh

examples/03-read-to-persistent/client.c, examples/03-read-to-persistent/server.c, examples/04-write-to-persistent/client.c, examples/04-write-to-persistent/server.c, examples/05-flush-to-persistent/client.c, examples/05-flush-to-persistent/server.c, examples/07-atomic-write/server.c, examples/09-flush-to-persistent-GPSPM/client.c, examples/09-flush-to-persistent-GPSPM/server.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1167)
=> example: printf the error reason

tools/perf/figures/cpuload.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1187)
=> tools: add cpuload.json figure

examples/03-read-to-persistent/server.c, examples/04-write-to-persistent/client.c, examples/04-write-to-persistent/server.c, examples/05-flush-to-persistent/client.c, examples/05-flush-to-persistent/server.c, examples/07-atomic-write/server.c, examples/09-flush-to-persistent-GPSPM/client.c, examples/09-flush-to-persistent-GPSPM/server.c
Ref: #1089
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1191)
=> examples: print a message in case no pmem provided or able to be used

tools/perf/CONFIG.JSON.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1192)
=> tools: add CONFIG.md file

tools/perf/lib/Figure.py
Ref: #1117
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1193)
=> tools: perf: fix the bw_avg-label mapping

tools/perf/lib/Figure.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1195)
=> tools: perf: introduce the 'better' hint

examples/02-read-to-volatile/CMakeLists.txt, examples/02-read-to-volatile/client.c, examples/03-read-to-persistent/CMakeLists.txt, examples/03-read-to-persistent/server.c, examples/04-write-to-persistent/CMakeLists.txt, examples/04-write-to-persistent/client.c, examples/05-flush-to-persistent/CMakeLists.txt, examples/05-flush-to-persistent/client.c, examples/06-multiple-connections/CMakeLists.txt, examples/06-multiple-connections/server.c, examples/07-atomic-write/CMakeLists.txt, examples/07-atomic-write/client.c, examples/08-messages-ping-pong/client.c, examples/08-messages-ping-pong/server.c, examples/09-flush-to-persistent-GPSPM/CMakeLists.txt, examples/09-flush-to-persistent-GPSPM/client.c, examples/09-flush-to-persistent-GPSPM/server.c, examples/CMakeLists.txt, src/cq.c, src/include/librpma.h, tests/unit/cq/cq-common.h, tests/unit/cq/cq-get_completion.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1170)
=> common: only process valid wc attributes when wc.status is not IBV_WC_SUCCESS

tools/perf/report.json.example
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1207)
=> tools: add report['security', 'description'] fields

tools/perf/lib/Report.py, tools/perf/report.json.example, tools/perf/tests/lib/report/test_init.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1210)
=> tools: rename high_level_setup_figure and copy it to the output directory

tools/perf/lib/Bench.py, tools/perf/report_bench.py, tools/perf/tests/lib/bench/test_new.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1202)
=> tools: perf: allow processing multiple figure files

tools/perf/lib/Benchmark.py, tools/perf/lib/Figure.py
TODO:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1215)
=> tools: perf: allow mixed workloads (part 1)

tools/perf/lib/Figure.py, tools/perf/lib/Report.py, tools/perf/templates/part_cpuload.md, tools/perf/templates/part_mix.md, tools/perf/templates/part_read.md, tools/perf/templates/part_write.md, tools/perf/tests/lib/report/test_init.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1225)
=> tools: perf: numbering figures within a report

tools/perf/BENCHMARKING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1217)
=> tools: update BENCHMARKING.md

tools/perf/CMakeLists.txt, tools/perf/lib/bench.py, tools/perf/lib/figure.py, tools/perf/tests/lib/bench/test_new.py, tools/perf/tests/lib/figure/test_html_data_table.py, tools/perf/tests/lib/figure/test_oneseries_derivatives.py, tools/perf/tests/lib/figure/test_png_path.py, tools/perf/tests/lib/report/test_init.py, utils/pylint.rc
Requires:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1223)
=> tools: perf: add lib.figure to pylint

tools/perf/figures/cpuload.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1227)
=> tools: add xscale to figures/cpuload.json

tools/perf/templates/part_write.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1232)
=> tools: write: GPSPM: add backticks to busy_wait_polling=X

tools/perf/lib/figure.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1229)
=> tools: escape '_' in figure titles

tools/perf/lib/Report.py, tools/perf/report.json.example, tools/perf/templates/part_preamble.md, tools/perf/tests/lib/report/test_init.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1233)
=> tools: add target description

tools/perf/lib/figure.py, tools/perf/tests/lib/figure/test_html_data_table.py
- collect a common subset of x-values
- replace missing y-values with '-'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1234)
=> tools: perf: improve data tables

tools/perf/lib/Benchmark.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1235)
=> tools: set cpu_load_range

tools/perf/lib/figure.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1238)
=> tools: decrease figures' padding

tools/perf/lib/Report.py, tools/perf/lib/common.py, tools/perf/lib/figure.py, tools/perf/templates/part_footer.md, tools/perf/tests/lib/report/test_init.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1236)
=> tools: add footer with ref

tools/perf/report_create.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1237)
=> tools: copy the provided report.json to the result_dir

tools/perf/lib/figure.py, tools/perf/templates/layout.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1239)
=> tools: add spacing before the figures' titles

tools/perf/templates/part_footer.md
Do not print this part in the menu.
Ref: #1236
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1241)
=> tools: perf: add footer with ref (fix)

tools/perf/templates/layout.html, tools/perf/templates/part_cpuload.md, tools/perf/templates/part_mix.md, tools/perf/templates/part_read.md, tools/perf/templates/part_write.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1242)
=> tools: perf: introduce page-breaks for more reasonable printing

tools/perf/lib/figure.py, tools/perf/templates/layout.html, tools/perf/tests/lib/figure/test_html_data_table.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1243)
=> tools: perf: align data tables to the right

tests/drd.supp, tests/helgrind.supp, tools/perf/tests/lib/benchmark/test_run.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1245)
=> common: fix spelling errors

tools/perf/lib/Benchmark.py, tools/perf/lib/figure.py, tools/perf/tests/lib/figure/test_html_data_table.py
Having two different structures provided under the same field on various stages of processing is confusing.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1246)
=> tools: perf: separate figure.series_in from figure.series

tools/perf/lib/Report.py, tools/perf/lib/common.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1247)
=> tools: escape markdown special characters in configuration

tools/perf/lib/figure.py, tools/perf/report.json.example, tools/perf/report_figures.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1244)
=> tools: fix y-axis to 110% of max

tools/perf/rpma_fio_bench.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1151)
=> tools: add more information to dump files

tools/perf/lib/Report.py, tools/perf/tests/lib/report/test_init.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1252)
=> tools: perf: append 'Testing date' to each config table

.github/workflows/nightly.yml, utils/docker/images/Dockerfile.debian-11, utils/docker/images/Dockerfile.fedora-34, utils/docker/images/Dockerfile.ubuntu-21.04
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1257)
=> common: add new versions of OSes to nightly CI builds

.github/workflows/gha.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1259)
=> common: upgrade Fedora and Ubuntu OSes in per-PR CI builds

tools/perf/lib/figure.py, tools/perf/tests/lib/figure/test_html_data_table.py
Requires:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1249)
=> tools: perf: introduce common series params

utils/docker/images/Dockerfile.debian-9, utils/docker/images/Dockerfile.ubuntu-20.04, utils/docker/run-build.sh
Requires to be merged first:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1258)
=>  common: run pytest always in all CI builds

tools/perf/lib/figure.py, tools/perf/report_figures.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1250)
=> tools: perf: introduce a way to regenerate file.json files

tools/perf/templates/layout.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1264)
=> tools: perf: made all data tables take 100% of the width

tools/perf/templates/part_preamble.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1265)
=> tools: add reference to the BENCHMARKING.md

src/librpma.map
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1263)
=> doc: sort names in src/librpma.map alphabetically

tools/perf/BENCHMARKING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1268)
=> tools: document the 'continue' option of report_bench.py

.github/workflows/nightly.yml
See: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1269)
=> common: enable manually running the Nightly workflow

utils/docker/images/build-image.sh
Trigger rebuilding all docker images
in order to rebuild all docker images used in Nightly CI builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1270)
=> common: trigger rebuilding all docker images

tests/unit/mr/mr-common.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1272)
=> test: fix one indentation

tools/perf/ib_read.sh, tools/perf/rpma_fio_bench.sh
Save intermediate files in case of an error
for the post mortem analysis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1273)
=> tools: save intermediate files in case of an error

tools/perf/tests/lib/benchmark/test_run.py, utils/docker/images/Dockerfile.centos-7
Fixes: #1262
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1276)
=> tools: remove the name argument of pytest.fixture()

tools/perf/templates/layout.html, tools/perf/templates/part_preamble.md
e.g.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1280)
=> tools: perf: add a handy release link to the menu

.github/workflows/nightly_experimental.yml, .github/workflows/nightly_rebuild.yml
See: #1269
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1282)
=> common: enable manually running all nightly workflows

src/librpma.map
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1285)
=> rpma: add rpma_mr_advise() to src/librpma.map file

CMakeLists.txt, cmake/FindLIBPMEM.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1284)
=> common: add missing CMake file

src/include/librpma.h
Ref: #1080
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1289)
=> rpma: implement separate receive CQ (fix)

tools/perf/BENCHMARKING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1293)
=> tools: perf: watermarking DYI

src/include/librpma.h, src/mr.c, tests/unit/mr/mr-advise.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1294)
=> rpma: enhance rpma_mr_advise() implementation

tools/perf/lib/figure.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1297)
=> tools: perf: skip benchmark when it turns out empty

examples/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1300)
=> examples: turn on -Wunused-macros and -Wsign-conversion

src/include/librpma.h
Ref #1212
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1267)
=> Update doc for the deprecated APIs

.github/workflows/nightly.yml, .github/workflows/nightly_experimental.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1311)
=> common: move failing clang Ubuntu_Rolling build to Nightly_Experimental

examples/01-connection/README.md, examples/02-read-to-volatile/README.md, examples/03-read-to-persistent/README.md, src/include/librpma.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1317)
=> common: fix minor misspells

src/include/librpma.h
Ref: #1112
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1316)
=> doc: Improve the manual of rpma_cq_get_fd()

tools/perf/BENCHMARKING.md, utils/docker/images/Dockerfile.archlinux-latest, utils/docker/images/Dockerfile.centos-7, utils/docker/images/Dockerfile.centos-8, utils/docker/images/Dockerfile.centos-stream, utils/docker/images/Dockerfile.debian-10, utils/docker/images/Dockerfile.debian-11, utils/docker/images/Dockerfile.debian-9, utils/docker/images/Dockerfile.debian-experimental, utils/docker/images/Dockerfile.debian-stable, utils/docker/images/Dockerfile.debian-testing, utils/docker/images/Dockerfile.fedora-26, utils/docker/images/Dockerfile.fedora-27, utils/docker/images/Dockerfile.fedora-28, utils/docker/images/Dockerfile.fedora-29, utils/docker/images/Dockerfile.fedora-30, utils/docker/images/Dockerfile.fedora-31, utils/docker/images/Dockerfile.fedora-32, utils/docker/images/Dockerfile.fedora-33, utils/docker/images/Dockerfile.fedora-34, utils/docker/images/Dockerfile.fedora-rawhide, utils/docker/images/Dockerfile.opensuse-leap-latest, utils/docker/images/Dockerfile.opensuse-tumbleweed-latest, utils/docker/images/Dockerfile.rockylinux-8.4, utils/docker/images/Dockerfile.ubuntu-18.04, utils/docker/images/Dockerfile.ubuntu-20.04, utils/docker/images/Dockerfile.ubuntu-21.04, utils/docker/images/Dockerfile.ubuntu-rolling, utils/docker/images/Dockerfile.vzlinux-latest
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1321)
=>  Add deepdiff to PYTHON_DEPS

doc/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1326)
=> doc: gawk is required by src2man

tools/perf/lib/benchmark/base.py, tools/perf/lib/benchmark/runner/__init__.py, tools/perf/lib/benchmark/runner/base.py, tools/perf/lib/benchmark/runner/common.py, tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py, tools/perf/tests/lib/benchmark/runner/common/__init__.py, tools/perf/tests/lib/benchmark/runner/fio/__init__.py, tools/perf/tests/lib/benchmark/runner/ib_read/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1328)
=> tools: perf: BaseRunner and IbReadRunner (scaffolding)

tools/perf/lib/benchmark/runner/fio.py, utils/pylint.rc
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1330)
=> tools: perf: FioRunner (scaffolding)

tools/perf/lib/Requirement.py, tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py, tools/perf/lib/remote_cmd.py
Requirements:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1331)
=> tools: perf: introduce controling DDIO from the Python-level

tools/perf/csv2standardized.py, tools/perf/lib/format/__init__.py, tools/perf/lib/format/fio.py, tools/perf/lib/format/ib_read_bw.py, tools/perf/lib/format/ib_read_lat.py, tools/perf/tests/lib/format/__init__.py, tools/perf/tests/lib/format/test_fio.py, tools/perf/tests/lib/format/test_ib_read_bw.py, tools/perf/tests/lib/format/test_ib_read_lat.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1332)
=> tools: perf: introduce lib.format

tools/perf/lib/benchmark/runner/common.py, tools/perf/lib/remote_cmd.py
Ref: #1331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1334)
=> tools: perf: DDIO from the Python-level (fix)

tools/perf/lib/Requirement.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1336)
=> tools: add missing cls argument (fix)

utils/docker/images/Dockerfile.archlinux-latest, utils/docker/images/Dockerfile.centos-7, utils/docker/images/Dockerfile.centos-8, utils/docker/images/Dockerfile.centos-stream, utils/docker/images/Dockerfile.debian-10, utils/docker/images/Dockerfile.debian-11, utils/docker/images/Dockerfile.debian-9, utils/docker/images/Dockerfile.debian-experimental, utils/docker/images/Dockerfile.debian-stable, utils/docker/images/Dockerfile.debian-testing, utils/docker/images/Dockerfile.fedora-26, utils/docker/images/Dockerfile.fedora-27, utils/docker/images/Dockerfile.fedora-28, utils/docker/images/Dockerfile.fedora-29, utils/docker/images/Dockerfile.fedora-30, utils/docker/images/Dockerfile.fedora-31, utils/docker/images/Dockerfile.fedora-32, utils/docker/images/Dockerfile.fedora-33, utils/docker/images/Dockerfile.fedora-34, utils/docker/images/Dockerfile.fedora-rawhide, utils/docker/images/Dockerfile.opensuse-leap-latest, utils/docker/images/Dockerfile.opensuse-tumbleweed-latest, utils/docker/images/Dockerfile.rockylinux-8.4, utils/docker/images/Dockerfile.ubuntu-18.04, utils/docker/images/Dockerfile.ubuntu-20.04, utils/docker/images/Dockerfile.ubuntu-21.04, utils/docker/images/Dockerfile.ubuntu-rolling, utils/docker/images/Dockerfile.vzlinux-latest
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1340)
=> common: add paramiko to $PYTHON_DEPS

tools/perf/ib_read.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1341)
=> tools: fix IB_PATH in ib_read.sh

tools/perf/lib/Requirement.py
Do not introduce the new temporary variable THE_NEW_DDIO_IMPL,
since it will be removed soon anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1343)
=> tools: do not introduce a new temporary variable

tools/perf/lib/benchmark/runner/fio.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1338)
=> tools: check if fio is present locally

tools/perf/BENCHMARKING.md, tools/perf/CMakeLists.txt, tools/perf/lib/remote_cmd.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1339)
=> tools: running commands on remote node over SSH

tools/perf/BENCHMARKING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1344)
=> tools: make old bash test framework the second option

utils/docker/images/Dockerfile.archlinux-latest, utils/docker/images/Dockerfile.centos-7, utils/docker/images/Dockerfile.centos-8, utils/docker/images/Dockerfile.centos-stream, utils/docker/images/Dockerfile.debian-10, utils/docker/images/Dockerfile.debian-11, utils/docker/images/Dockerfile.debian-9, utils/docker/images/Dockerfile.debian-experimental, utils/docker/images/Dockerfile.debian-stable, utils/docker/images/Dockerfile.debian-testing, utils/docker/images/Dockerfile.fedora-26, utils/docker/images/Dockerfile.fedora-27, utils/docker/images/Dockerfile.fedora-28, utils/docker/images/Dockerfile.fedora-29, utils/docker/images/Dockerfile.fedora-30, utils/docker/images/Dockerfile.fedora-31, utils/docker/images/Dockerfile.fedora-32, utils/docker/images/Dockerfile.fedora-33, utils/docker/images/Dockerfile.fedora-34, utils/docker/images/Dockerfile.fedora-rawhide, utils/docker/images/Dockerfile.opensuse-leap-latest, utils/docker/images/Dockerfile.opensuse-tumbleweed-latest, utils/docker/images/Dockerfile.rockylinux-8.4, utils/docker/images/Dockerfile.ubuntu-18.04, utils/docker/images/Dockerfile.ubuntu-20.04, utils/docker/images/Dockerfile.ubuntu-21.04, utils/docker/images/Dockerfile.ubuntu-rolling, utils/docker/images/Dockerfile.vzlinux-latest
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1348)
=> common: add scp to $PYTHON_DEPS

tools/perf/lib/figure.py, tools/perf/report_bench.py, utils/pylint.rc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1349)
=> tools: perf: allow long triple-quoted strings

tools/perf/lib/benchmark/runner/ib_read.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1345)
=> tools: check if ib_tool is present remotely

tools/perf/BENCHMARKING.md, tools/perf/lib/remote_cmd.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1350)
=> tools: copy file to a remote node

tools/perf/lib/benchmark/runner/fio.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1354)
=> tools: check if fio is present remotely

tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py, tools/perf/lib/remote_cmd.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1355)
=> tools: replace the cmd argument with a list

tools/perf/.gitignore, tools/perf/CONTRIBUTING.md
- add pylint and pdoc3
- add a section about the Python documentation
- pytest and pylint are already in the CI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1356)
=> tools: perf: update CONTRIBUTING.md

INSTALL.md, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1347)
=> common: fix README.md and INSTALL.md

tools/perf/lib/benchmark/runner/ib_read.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1351)
=> tools: ib_read.py: add __append_common_args

tools/perf/lib/Requirement.py, tools/perf/lib/bench.py, tools/perf/tests/lib/bench/test_new.py
- transform 'raw' members into properties
- copy objects to guard the inner state immutability
- introduce working on copies so the logic stay intact
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1358)
=> tools: perf: seal lib.bench

tools/perf/report_bench.py, tools/perf/report_create.py, tools/perf/report_figures.py, utils/pylint.rc
Including:
- docstrings
- argparse --help
Taking into account the pdoc3 output readability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1357)
=> tools: perf: improve scripts documentation

tools/perf/lib/Requirement.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1362)
=> tools: perf: fix the benchmarking dump

tools/perf/report_bench.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1363)
=> tools: perf: complete and incomplete end

tools/perf/lib/benchmark/runner/ib_read.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1360)
=> tools: ib_read.py, SETTINGS_BY_MODE filled up

tools/perf/lib/__init__.py, tools/perf/lib/figure/__init__.py, tools/perf/lib/figure/flat.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1366)
=> tools: perf: document lib.figure.flat module

tools/perf/CMakeLists.txt, tools/perf/lib/compare.py, tools/perf/lib/figure/__init__.py, tools/perf/lib/figure/base.py, tools/perf/lib/figure/html.py, tools/perf/lib/figure/image.py, tools/perf/tests/lib/figure/test_html_data_table.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1367)
=> tools: perf: split lib.figure.base.Figure

tools/perf/lib/remote_cmd.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1372)
=> tools: verify that the cmd argument is a list

tools/perf/lib/benchmark/base.py, tools/perf/lib/common.py, tools/perf/lib/figure/base.py, tools/perf/lib/figure/flat.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1368)
=> tools: perf: separate Figure and Benchmark oneseries

tools/perf/lib/bench.py, tools/perf/lib/figure/__init__.py, tools/perf/lib/figure/base.py, tools/perf/lib/figure/flat.py, tools/perf/lib/figure/html.py, tools/perf/lib/figure/image.py, tools/perf/tests/lib/bench/test_new.py, tools/perf/tests/lib/figure/test_html_data_table.py, tools/perf/tests/lib/figure/test_png_path.py, tools/perf/tests/lib/report/test_init.py
Additionally, the commit contains:
- forcing each Figure instance to have a result_dir set from the conception.
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1371)
=> tools: perf: document lib.figure.{base,html,image}

tools/perf/lib/benchmark/runner/ib_read.py
Reorder modes in SETTINGS_BY_MODE so that
they match the ones from ib_read.sh.
It will simplify implementing other things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1373)
=> tools: reorder modes in SETTINGS_BY_MODE

tools/perf/lib/compare.py
Ref: #1369
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1377)
=> tools: perf: prepare lib.benchmark and lib.figure... (fix)

tools/perf/lib/Requirement.py, tools/perf/lib/bench.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1375)
=> tools: perf: document lib.Requirement

tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py, tools/perf/lib/remote_cmd.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1387)
=> tools: add error raising in run_sync function

tools/perf/lib/bench.py, tools/perf/lib/benchmark/runner/fio.py, tools/perf/tests/lib/bench/test_new.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1370)
=> tools: read CPULIST and CORES_PER_SOCKET from the remote node

tools/perf/CMakeLists.txt, tools/perf/lib/common.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1383)
=> tools: perf: document lib.common

tools/perf/lib/benchmark/runner/ib_read.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1378)
=> tools: set names of log files

tools/perf/CMakeLists.txt, tools/perf/lib/compare.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1384)
=> tools: perf: document lib.compare

tools/perf/lib/remote_cmd.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1386)
=> tools: perf: document lib.remote_cmd

tools/perf/lib/report/__init__.py, tools/perf/lib/report/base.py, tools/perf/lib/report/part.py, tools/perf/lib/report/utils.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1381)
=> tools: perf: document lib.report

tools/perf/CMakeLists.txt, tools/perf/lib/format/__init__.py, tools/perf/lib/format/fio.py, tools/perf/lib/format/ib_read_bw.py, tools/perf/lib/format/ib_read_lat.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1385)
=> tools: perf: document lib.format

tools/perf/lib/benchmark/base.py, tools/perf/lib/benchmark/runner/__init__.py, tools/perf/lib/benchmark/runner/base.py, tools/perf/lib/benchmark/runner/bash.py, tools/perf/lib/benchmark/runner/common.py, tools/perf/lib/benchmark/runner/dummy.py, tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1382)
=> tools: perf: document lib.benchmark.runner

tools/perf/lib/benchmark/runner/ib_read.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1352)
=> tools: ib_read.py: implement __server_start and __server_stop

tools/perf/lib/report/base.py, tools/perf/lib/report/part.py
lib.report.utils instead of lib.report.variable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1390)
=> tools: perf: document lib.report (fix)

tools/perf/lib/benchmark/runner/fio.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1392)
=> tools: cpuload is an x-axis in case of the lat-cpu mode (fix)

tools/perf/lib/benchmark/runner/base.py, tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py
Commands will be dumped inside the runners, so in the following files:
- ib_read.py and
- fio.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1394)
=> tools: clean up base.py

tools/perf/lib/benchmark/runner/common.py, tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1395)
=> tools: implement __result_append and __result_is_done

tools/perf/lib/benchmark/runner/ib_read.py, tools/perf/lib/format/ib_read_bw.py, tools/perf/lib/format/ib_read_lat.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1346)
=> tools: ib_read.py: implement __client_run

tools/perf/lib/benchmark/runner/ib_read.py
`IB_PATH` and `REMOTE_IB_PATH` are not required in `config.json`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1402)
=> tools: fix setting paths of ib tools

tools/perf/lib/Requirement.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1401)
=> tools: implement __set_DDIO

tools/perf/lib/benchmark/runner/common.py, tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1399)
=> tools: print message at the beginning of the benchmark

tools/perf/lib/benchmark/runner/ib_read.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1406)
=> tools: retry to connect the client of ib tool

.github/workflows/nightly.yml, utils/docker/images/Dockerfile.ubuntu-21.10
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1309)
=> common: add Ubuntu 21.10 to Nightly workflow

tools/perf/lib/benchmark/runner/fio.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1391)
=> tools: fio.py SETTINGS_BY_MODE filled up

tools/perf/lib/benchmark/runner/common.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1420)
=> tools: check also a list in result_is_done() (fix)

tools/perf/lib/figure/base.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1419)
=> tools: fix collect_results() in base.py

tools/perf/lib/benchmark/runner/fio.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1412)
=> tools: fio.py: implement __server_start and __server_stop

tools/perf/lib/benchmark/runner/fio.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1417)
=> tools: fio.py: implement __client_run()

tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1424)
=> tools: move all constants to the end of file

tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1421)
=> tools: print out names of log files

tools/perf/lib/format/fio.py, tools/perf/lib/format/ib_read_bw.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1430)
=> tools: make sure all results are numbers

tools/perf/lib/remote_cmd.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1435)
=> tools: decode the error message in run_sync() (fix)

tools/perf/BENCHMARKING.md, tools/perf/lib/benchmark/base.py, tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/common.py, tools/perf/lib/format/fio.py, tools/perf/lib/report/__init__.py, tools/perf/report_create.py, tools/perf/report_figures.py
Fix errors found by codespell.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1437)
=> tools: codespell fixes

tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1418)
=> tools: ib_read.py, fio.py - add DUMP_CMDS for a client and a server

tools/perf/lib/benchmark/runner/common.py, tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1427)
=> tools: add remote_command_pre/post

tools/perf/lib/benchmark/runner/fio.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1438)
=> tools: fix dumping command of the fio server

tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py
Later __set_log_file_names can be moved to superclass
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1439)
=> tools: create log file name based on oneseries[tool]

tools/perf/lib/benchmark/runner/common.py
Fix bad-whitespace errors:
```
C0326: No space allowed around keyword argument assignment
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1442)
=> tools: fix bad-whitespace errors

tools/perf/lib/remote_cmd.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1441)
=> tools: fix RemoteCmd

tools/perf/figures/cpuload.json, tools/perf/figures/mix.json, tools/perf/figures/read.json, tools/perf/figures/write.json
This PR will be merged to the new `devel-new-python` branch:
https://github.com/pmem/rpma/tree/devel-new-python
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1393)
=> tools: adjust existing figures to the new python framework

tools/perf/tests/lib/benchmark/conftest.py, tools/perf/tests/lib/benchmark/test_run.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1440)
=> test: add simple test for the base runner

tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py
Change way of importing shutil.which() so that
it could be mocked in pytest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1445)
=> tools: change way of importing shutil.which()

tools/perf/lib/benchmark/runner/common.py, tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py
Depends on:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1447)
=> tools: unify error messages and exceptions

tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py
Depends on:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1449)
=> tools: improve setting dumping commands

tools/perf/lib/benchmark/runner/fio.py
Depends on:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1450)
=> tools: fio: verify if tool_mode has a correct value

tools/perf/lib/benchmark/base.py, tools/perf/lib/benchmark/runner/__init__.py, tools/perf/lib/benchmark/runner/executor.py, tools/perf/tests/lib/benchmark/test_run.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1433)
=> tools: follow Abstract Factory design patter to call proper runner

tools/perf/lib/benchmark/runner/ib_read.py
Enable short runtime (10 iterations) for ib_read runner
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1453)
=> tools: ib_read short runtime

tools/perf/lib/benchmark/runner/fio.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1460)
=> tools: missing direct_wrte_to_pmem exception added

tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1461)
=> tools: runners initialization fixes

tools/perf/lib/figure/base.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1451)
=> tools: fix collect_results() when collecting mix workloads

tools/perf/lib/benchmark/runner/executor.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1470)
=> tools: fix Executor.run()

tools/perf/lib/benchmark/runner/fio.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1467)
=> tools: tool added to mandatory keys

utils/docker/run-build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1473)
=> common: do not run pytest if TEST_PYTHON_TOOLS is not ON (fix)

tools/perf/tests/lib/benchmark/conftest.py, tools/perf/tests/lib/benchmark/runner/test_executor_run.py, tools/perf/tests/lib/benchmark/test_run.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1448)
=> test: add tests for the Executor runner

tools/perf/CMakeLists.txt, tools/perf/tests/lib/benchmark/test_run.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1474)
=> tools: check tools/perf/tests/lib/benchmark/*.py with pylint

tools/perf/lib/benchmark/runner/fio.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1471)
=> tools:  remove duplicate lines

tools/perf/lib/benchmark/runner/common.py, tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py, tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1477)
=> tools: improve validating oneseries

tools/perf/lib/benchmark/runner/fio.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1481)
=> tools: add randread, randwrite and randrw to fio rw modes

tools/perf/lib/Requirement.py, tools/perf/lib/benchmark/base.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1478)
=> tools: fix continue mode

tools/perf/lib/benchmark/runner/fio.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1479)
=> tools: add REMOTE_TRACER

tools/perf/lib/bench.py, tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py, tools/perf/tests/lib/bench/test_new.py
... and do not require auxiliary parameters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1485)
=> tools: check if all required parameters are set in the config

tools/perf/BENCHMARKING.md, tools/perf/report_figures.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1487)
=> tools: rename the '--names' option to '--prefixes'

tools/perf/BENCHMARKING.md, tools/perf/figures/example_read.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1484)
=> tools: update BENCHMARKING.md and add simple example of figure

tools/perf/CONFIG.JSON.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1486)
=> tools: document config.json parameters

tools/perf/CONFIG.JSON.md, tools/perf/config.json.example, tools/perf/lib/Requirement.py, tools/perf/lib/bench.py, tools/perf/lib/benchmark/base.py, tools/perf/lib/benchmark/runner/common.py, tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py, tools/perf/lib/remote_cmd.py, tools/perf/tests/lib/bench/test_new.py, tools/perf/tests/lib/benchmark/runner/test_executor_run.py, tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, tools/perf/tests/lib/benchmark/test_run.py
Replace:
- 'platform_generation' with 'PLATFORM_GENERATION' and
- 'server_ip' with 'SERVER_IP'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1491)
=> tools: use only capital letters in config variables

tools/perf/CONFIG.JSON.md, tools/perf/config.json.example, tools/perf/lib/benchmark/runner/fio.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1492)
=> tools: replace REMOTE_JOB_MEM_PATH with REMOTE_PMEM_PATH

tools/perf/CONFIG.JSON.md, tools/perf/lib/Requirement.py, tools/perf/lib/bench.py, tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py, tools/perf/lib/format/fio.py, tools/perf/lib/format/ib_read_bw.py, tools/perf/lib/format/ib_read_lat.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1482)
=> tools: add support for the SKIP_RUNNING_TOOLS option

utils/docker/images/Dockerfile.archlinux-latest, utils/docker/images/Dockerfile.centos-7, utils/docker/images/Dockerfile.centos-8, utils/docker/images/Dockerfile.centos-stream, utils/docker/images/Dockerfile.debian-10, utils/docker/images/Dockerfile.debian-11, utils/docker/images/Dockerfile.debian-9, utils/docker/images/Dockerfile.debian-experimental, utils/docker/images/Dockerfile.debian-stable, utils/docker/images/Dockerfile.debian-testing, utils/docker/images/Dockerfile.fedora-26, utils/docker/images/Dockerfile.fedora-27, utils/docker/images/Dockerfile.fedora-28, utils/docker/images/Dockerfile.fedora-29, utils/docker/images/Dockerfile.fedora-30, utils/docker/images/Dockerfile.fedora-31, utils/docker/images/Dockerfile.fedora-32, utils/docker/images/Dockerfile.fedora-33, utils/docker/images/Dockerfile.fedora-34, utils/docker/images/Dockerfile.fedora-rawhide, utils/docker/images/Dockerfile.opensuse-leap-latest, utils/docker/images/Dockerfile.opensuse-tumbleweed-latest, utils/docker/images/Dockerfile.rockylinux-8.4, utils/docker/images/Dockerfile.ubuntu-18.04, utils/docker/images/Dockerfile.ubuntu-20.04, utils/docker/images/Dockerfile.ubuntu-21.04, utils/docker/images/Dockerfile.ubuntu-21.10, utils/docker/images/Dockerfile.ubuntu-rolling, utils/docker/images/Dockerfile.vzlinux-latest
#1490
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1496)
=> common: deleted pandas from all docker files

tools/perf/CONFIG.JSON.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1500)
=> tools: describe REMOTE_PMEM_PATH in details

tools/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1507)
=> tools: clarify the ddio.sh script usage

.github/workflows/nightly.yml, .github/workflows/nightly_experimental.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1508)
=> common: move OpenSUSE Tumbleweed back to Nightly

examples/05-flush-to-persistent/server.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1505)
=> examples: add rpma_mr_advise

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1506)
=> rpma: update CHANGELOG

examples/03-read-to-persistent/server.c, examples/04-write-to-persistent/server.c, examples/05-flush-to-persistent/server.c, examples/07-atomic-write/server.c, examples/09-flush-to-persistent-GPSPM/server.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1510)
=> examples: add rpma_mr_advise to the rest of examples

CHANGELOG.md, CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1512)
=> common: 0.10.0-rc1 release

src/librpma.map
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1514)
=> rpma: update linker version script

src/include/librpma.h
PR  #1271
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1504)
=> rpma: comparison of old and new API

doc/manuals_3.txt, examples/02-read-to-volatile/client.c, src/cq.c, src/include/librpma.h, src/librpma.map, tests/unit/cq/CMakeLists.txt, tests/unit/cq/cq-get_wc.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/979)
=> rpma: implement rpma_cq_get_wc(3)

utils/docker/run-doc-update.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1516)
=> common: rename gh-pages branch to man-pages

tools/perf/lib/compare.py, tools/perf/lib/figure/__init__.py, tools/perf/lib/figure/html.py, tools/perf/lib/figure/image.py, tools/perf/report_figures.py, tools/perf/templates/layout_cmp.html
Ref: #1495
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1503)
=> tools: create html compare files

utils/docker/images/Dockerfile.archlinux-latest, utils/docker/images/Dockerfile.centos-7, utils/docker/images/Dockerfile.centos-8, utils/docker/images/Dockerfile.centos-stream, utils/docker/images/Dockerfile.debian-10, utils/docker/images/Dockerfile.debian-11, utils/docker/images/Dockerfile.debian-9, utils/docker/images/Dockerfile.debian-experimental, utils/docker/images/Dockerfile.debian-stable, utils/docker/images/Dockerfile.debian-testing, utils/docker/images/Dockerfile.fedora-26, utils/docker/images/Dockerfile.fedora-27, utils/docker/images/Dockerfile.fedora-28, utils/docker/images/Dockerfile.fedora-29, utils/docker/images/Dockerfile.fedora-30, utils/docker/images/Dockerfile.fedora-31, utils/docker/images/Dockerfile.fedora-32, utils/docker/images/Dockerfile.fedora-33, utils/docker/images/Dockerfile.fedora-34, utils/docker/images/Dockerfile.fedora-rawhide, utils/docker/images/Dockerfile.opensuse-leap-latest, utils/docker/images/Dockerfile.opensuse-tumbleweed-latest, utils/docker/images/Dockerfile.rockylinux-8.4, utils/docker/images/Dockerfile.ubuntu-18.04, utils/docker/images/Dockerfile.ubuntu-20.04, utils/docker/images/Dockerfile.ubuntu-21.04, utils/docker/images/Dockerfile.ubuntu-21.10, utils/docker/images/Dockerfile.ubuntu-rolling, utils/docker/images/Dockerfile.vzlinux-latest
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1502)
=> common: add coverage library to docker images

tools/perf/CONFIG.JSON.md, tools/perf/lib/benchmark/runner/fio.py, tools/perf/lib/benchmark/runner/ib_read.py
Replace:
- `SHORT_RUNTIME` with `DEBUG_SHORT_RUNTIME`,
- `TRACER` with `DEBUG_TRACER` and
- `REMOTE_TRACER` with `DEBUG_REMOTE_TRACER`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1520)
=> tools: add _DEBUG prefix to the rest of debug config.json variables

examples/03-read-to-persistent/server.c, examples/04-write-to-persistent/client.c, examples/05-flush-to-persistent/client.c, examples/06-multiple-connections/README.md, examples/06-multiple-connections/server.c, examples/07-atomic-write/client.c, examples/08-messages-ping-pong/client.c, examples/08-messages-ping-pong/server.c, examples/09-flush-to-persistent-GPSPM/client.c, examples/09-flush-to-persistent-GPSPM/server.c, examples/10-send-with-imm/client.c, examples/10-send-with-imm/server.c, examples/11-write-with-imm/client.c, examples/11-write-with-imm/server.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1519)
=> examples: use rpma_cq_get_wc() in all examples

CHANGELOG.md
Update CHANGELOG.md with the latest changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1524)
=> common: update CHANGELOG.md

tools/perf/BENCHMARKING.md, tools/perf/config.json.example
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1522)
=> tools: update BENCHMARKING.md and config.json.example

utils/docker/run-build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1498)
=> common: run-build.sh python test coverage

examples/05-flush-to-persistent/server.c, examples/07-atomic-write/server.c, examples/08-messages-ping-pong/client.c, examples/10-send-with-imm/client.c
Do not ignore correct arguments if excessive ones were added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1530)
=> examples: do not ignore correct arguments

src/include/librpma.h
This is a continuation of #1525.
Ref: #1525
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1539)
=> rpma: replace rpma_cq_get_completion() with rpma_cq_get_wc()

examples/12-receive-completion-queue/CMakeLists.txt, examples/12-receive-completion-queue/README.md, examples/12-receive-completion-queue/client.c, examples/12-receive-completion-queue/receive-completion-queue-common.c, examples/12-receive-completion-queue/receive-completion-queue-common.h, examples/12-receive-completion-queue/server.c, examples/CMakeLists.txt, examples/run-all-on-SoftRoCE.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1528)
=> examples: add the example_12 receive_completion_queue

tools/perf/lib/benchmark/runner/fio.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1536)
=> tools: busy-wait-poling added to mandatory keys

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1543)
=> common: fix RCQ shortcut in CHANGELOG.md of release v0.10.0

src/include/librpma.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1541)
=> rpma: make usage of rpma_cq_wait() and rpma_cq_get_wc() more precise

examples/08-messages-ping-pong/CMakeLists.txt, examples/08-messages-ping-pong/client.c, examples/08-messages-ping-pong/messages-ping-pong-common.c, examples/08-messages-ping-pong/messages-ping-pong-common.h, examples/08-messages-ping-pong/server.c, examples/CMakeLists.txt
Ref: https://github.com/pmem/rpma/pull/1541
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1540)
=> examples: delete rpma_cq_get_wc() appearing before rpma_cq_wait()

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1544)
=> common: update CHANGELOG

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1547)
=> common: fix date of release v0.10.0 in CHANGELOG.md

README.md
Thank you, Jan, very much for all your contributions
and maintaining librpma from the very begining!
See you, Jan!
RPMA team
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1550)
=> rpma: see you, Jan!

README.md
Thank you, Jan, very much for all your contributions
and maintaining librpma from the very begining!
See you, Jan!
RPMA team
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1554)
=> doc: see you, Jan!

examples/07-atomic-write/client.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1553)
=> examples: make sure the word is always null-terminated

src/include/librpma.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1555)
=> rpma: update DEPRECATED documentation of struct rpma_completion

utils/mans_header.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1558)
=> common: update API version in header of manuals in utils/mans_header.md

utils/mans_header.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1564)
=> common: update header of manuals in utils/mans_header.md

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1568)
=> doc: examples 07 and 08 were fixed in v0.11.0

src/include/librpma.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1569)
=> rpma: prevent a link from being corrupted by txt2man

manpages/v0.10.0/librpma.7.md, manpages/v0.11.0/librpma.7.md, manpages/v0.9.0/librpma.7.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1570)
=> doc: fix links to the article

utils/mans_header.md, utils/src2mans.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1575)
=> common: update manuals header to the hugo format

utils/docker/build.sh, utils/docker/run-doc-update.sh, utils/docker/valid-branches.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1574)
=> common: add automatic update of man pages in the pmem.github.io repo

doc/manuals_3.txt, src/conn.c, src/include/librpma.h, src/librpma.map, src/mr.c, src/mr.h, tests/unit/common/mocks-rpma-mr.c, tests/unit/conn/CMakeLists.txt, tests/unit/conn/conn-atomic_write.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1594)
=> rpma: scaffolding for rpma_atomic_write()

CHANGELOG.md, tools/perf/templates/part_write.json
Fixes a bug introduced in PR:
https://github.com/pmem/rpma/commit/296e4e3755079876f31afb5c8060fdf52d64a1ef
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1596)
=> tools: fix part_write.json

src/include/librpma.h, src/mr.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1598)
=> rpma: finish the documentation for rpma_atomic_write()

CHANGELOG.md, src/include/librpma.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1605)
=> rpma: fix documentation of rpma_utils_conn_event_2str()

CHANGELOG.md, src/conn.c, src/mr.c, src/peer.c, tests/integration/common/mocks.h, tests/unit/common/mocks-rpma-conn_cfg.h, tests/unit/common/mocks-rpma-mr.c, tests/unit/conn/conn-atomic_write.c, tests/unit/mr/CMakeLists.txt, tests/unit/mr/mr-atomic_write.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1601)
=> rpma: implement rpma_atomic_write()

CHANGELOG.md, src/include/librpma.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1608)
=> rpma: mark rpma_write_atomic() as deprecated

CHANGELOG.md, examples/07-atomic-write/client.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1607)
=> examples: replace rpma_write_atomic() with rpma_atomic_write()

examples/07-atomic-write/client.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1612)
=> examples: set the return value if an error occurs

tests/multithreaded/example/example.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1625)
=> test: fixing a typo in the multithread example

documentation/perf-tuning.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1626)
=> doc: update perf-tuning.md for ICX

documentation/basic-hw_sw_setup_starting_point.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1633)
=> doc: update basic-hw_sw_setup_starting_point.md

CHANGELOG.md, src/conn_req.c, tests/unit/common/mocks-rdma_cm.c, tests/unit/common/mocks-rdma_cm.h, tests/unit/common/mocks-rpma-log.c, tests/unit/conn_req/CMakeLists.txt, tests/unit/conn_req/conn_req-common.c, tests/unit/conn_req/conn_req-common.h, tests/unit/conn_req/conn_req-from_cm_event.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1634)
=> rpma: log GID addresses in rpma_conn_req_from_id()

CHANGELOG.md, src/rpma_err.c, tests/unit/error/error.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1639)
=> rpma: add error message for RPMA_E_AGAIN

documentation/basic-direct-write-to-pmem.md, documentation/perf-tuning.md, manpages/v0.9.0/rpma_mr_get_descriptor_size.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1640)
=> doc: fix spelling errors

tests/multithreaded/common/mtt.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1641)
=> test: zero the allocated memory in mtt_malloc_aligned()

tools/perf/CONFIG.JSON.md, tools/perf/config.json.example, tools/perf/lib/Requirement.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1636)
=> tools: add checking xADR parameter for Ice Lake platforms

tests/multithreaded/common/mtt.c, tests/multithreaded/common/mtt.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1642)
=> test: add child error messages to mtt_malloc_aligned()

documentation/basic-direct-write-to-pmem.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1638)
=> doc: update pmem.io benchmarking manuals for ICX

tests/multithreaded/common/mtt.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1644)
=> test: MTT: check if the child process terminated

src/conn.c, tests/unit/conn/conn-new.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1646)
=> rpma: add missing rpma_private_data_discard (fix)

examples/run-all-on-SoftRoCE.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1645)
=> examples: print out log file in case of error

tests/multithreaded/common/mtt_connect.h, tests/multithreaded/mr/CMakeLists.txt, tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1630)
=> test: add the rpma_mr_remote_from_descriptor multithreaded test

CHANGELOG.md, src/conn.c, src/include/librpma.h, src/rpma_err.c, tests/unit/error/error.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1651)
=> rpma: fix rpma_conn_get_compl_fd()

doc/manuals_3.txt, src/include/librpma.h, tests/unit/conn_cfg/CMakeLists.txt, tests/unit/conn_cfg/conn_cfg-compl_channel.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1649)
=> rpma: add doc + ut for set/get_compl_channel

src/conn.c, src/include/librpma.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1654)
=> rpma: add bool *is_rcq argument to rpma_conn_wait

tests/unit/common/mocks-rpma-conn_cfg.c, tests/unit/common/mocks-rpma-conn_cfg.h, tests/unit/conn_req/conn_req-common.c, tests/unit/conn_req/conn_req-from_cm_event.c, tests/unit/conn_req/conn_req-new.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1659)
=> test: add mock of rpma_conn_cfg_get_compl_channel()

src/conn_req.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1663)
=> rpma: enable shared completion channel when there is no RCQ

documentation/basic-direct-write-to-pmem.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1660)
=> doc: update pmem.io benchmarking manuals for ICX and CLX DDIO

tests/unit/common/mocks-rpma-conn.c, tests/unit/conn_req/conn_req-common.h, tests/unit/conn_req/conn_req-connect.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1666)
=> test: verify channel in rpma_conn_new()

tests/unit/conn/conn-common.c, tests/unit/conn/conn-common.h, tests/unit/conn/conn-get_compl_fd.c, tests/unit/conn/conn-wait.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1672)
=> test: rename Conn_with_rcq_and_channel to Conn_with_rcq_with_channel

tests/unit/conn/conn-common.h, tests/unit/conn/conn-get_cq_rcq.c, tests/unit/conn/conn-new.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1670)
=> test: update CONN_TEST_SETUP_TEARDOWN_WITH_AND_WITHOUT_RCQ()

tests/unit/conn/conn-common.c, tests/unit/conn/conn-common.h
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1671)
=> test: add Conn_no_rcq_with_channel

tests/unit/conn/conn-new.c
Required:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1662)
=> test: add missing unit tests for rpma_conn_delete()

tests/unit/conn_req/conn_req-from_cm_event.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1673)
=> test: add missing test for rpma_conn_req_from_cm_event()

tests/unit/conn_req/conn_req-delete.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1675)
=> test: add missing tests for rpma_conn_req_delete()

CONTRIBUTING.md, utils/cstyle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1679)
=> common: set maximum line length to 100

CHANGELOG.md, src/include/librpma.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1678)
=> rpma: update librpma.h and CHANGELOG

tests/unit/conn/conn-get_compl_fd.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1682)
=> test: minor fixes in conn-get_compl_fd.c

src/include/librpma.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1683)
=> rpma: fix SYNOPSIS of rpma_conn_wait()

CHANGELOG.md, src/peer.c, tests/unit/peer/peer-common.c, tests/unit/peer/peer-new.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1686)
=> rpma: fix memory leak in rpma_peer_delete()

src/conn_cfg.c, src/conn_cfg.h, src/conn_req.c, tests/integration/common/mocks.c, tests/unit/common/mocks-rpma-conn_cfg.c, tests/unit/conn_cfg/conn_cfg-cqe.c, tests/unit/conn_cfg/conn_cfg-rcqe.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1685)
=> rpma: make rpma_conn_cfg_get_cqe() and rpma_conn_cfg_get_rcqe() void

examples/run-all-on-SoftRoCE.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1699)
=> examples: always print suppressions for all errors

src/log_internal.h
See: https://kernelnewbies.org/FAQ/DoWhile0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1695)
=> rpma: use 'do { ... } while(0)' in the RPMA_LOG() macro

examples/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1705)
=> examples: add common-conn.c and USE_LIBIBVERBS inside add_example()

examples/13-flush-to-persistent-GPSPM-SHCCH/server.c, examples/common/common-conn.c, examples/common/common-conn.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1704)
=> examples: use shared completion channel in example 13 (server part)

examples/13-flush-to-persistent-GPSPM-SHCCH/client.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1706)
=> examples: use shared completion channel in example 13 (client part)

examples/13-flush-to-persistent-GPSPM-SHCCH/README.md, examples/14-receive-completion-queue-SHCCH/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1709)
=> examples: improve README files (13, 14)

tests/multithreaded/common/mtt_common-epoll.c, tests/multithreaded/common/mtt_common-epoll.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1713)
=> test: add common epoll functions to MT framework

examples/15-multiple-connections-SHCCH/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1718)
=> examples: add a readme to the example15

tests/multithreaded/conn/rpma_conn_get_private_data.c, tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1721)
=> test: fix coding style in MT tests

examples/15-multiple-connections-SHCCH/client.c, examples/15-multiple-connections-SHCCH/server.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1712)
=> example: add example 15

tests/multithreaded/conn/CMakeLists.txt, tests/multithreaded/conn/rpma_common.c, tests/multithreaded/conn/rpma_common.h, tests/multithreaded/conn/rpma_read.c, tests/multithreaded/conn/rpma_write.c, tests/multithreaded/conn/rpma_write_read.c, tests/multithreaded/conn/server_rpma_common.c, tests/multithreaded/conn/server_rpma_common.h, tests/multithreaded/conn/server_rpma_empty.c, tests/multithreaded/run_group.cmake
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1717)
=> test: add one rpma_read and two rpma_write MT tests

tests/multithreaded/conn/CMakeLists.txt, tests/multithreaded/conn/rpma_common.c, tests/multithreaded/conn/rpma_common.h, tests/multithreaded/conn/rpma_read.c, tests/multithreaded/conn/rpma_send.c, tests/multithreaded/conn/rpma_write_read.c, tests/multithreaded/conn/server_rpma_common.c, tests/multithreaded/conn/server_rpma_send.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1719)
=> test: add rpma_send MT test

examples/03-read-to-persistent/CMakeLists.txt, examples/03-read-to-persistent/client.c, examples/CMakeLists.txt, examples/common/common-conn.h, examples/common/common-pmem.h, examples/common/common-pmem2_map_file.c, examples/common/common-pmem_map_file.c, examples/common/common-pmem_map_file.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1631)
=> examples: add libpmem2 to example 03

examples/run-all-on-SoftRoCE.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1723)
=> examples: add functions to start commands in run-all-on-SoftRoCE.sh

src/conn_req.c, tests/unit/conn_req/conn_req-connect.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1726)
=> rpma: add missing rpma_private_data_discard() to rpma_conn_req_accept()

CMakeLists.txt, INSTALL.md, src/CMakeLists.txt, src/conn.c, src/conn_cfg.c, src/conn_req.c, src/cq.c, src/debug.c, src/debug.h, src/ep.c, src/flush.c, src/include/librpma.h, src/info.c, src/mr.c, src/peer.c, src/peer_cfg.c, src/private_data.c, src/rpma.c, src/rpma_err.c, tests/unit/error/error.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1647)
=> rpma: add fault injection and debug tracing

src/conn_req.c
Ref: #1728
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1730)
=> rpma: move common code into rpma_conn_req_delete()

examples/04-write-to-persistent/client.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1731)
=> examples: fix memory leak in example 04

src/ep.c, tests/unit/ep/ep-listen.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1733)
=> rpma: fix memory leak in rpma_ep_shutdown()

src/conn_req.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1735)
=> rpma: simplify fault injection in rpma_conn_req_accept()

src/conn.c, src/conn_cfg.c, src/conn_req.c, src/cq.c, src/debug.c, src/debug.h, src/ep.c, src/flush.c, src/include/librpma.h, src/info.c, src/mr.c, src/peer.c, src/peer_cfg.c, src/private_data.c, src/rpma.c, src/rpma_err.c, tests/unit/error/error.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1736)
=> rpma: add fault injection also inside functions

examples/CMakeLists.txt
inside add_example()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1745)
=> examples: add common-pmem2_map_file.c and common-pmem2_map_file.c

THREAD_SAFETY.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1751)
=> rpma: scaffolding of thread safety analysis of the librpma library

THREAD_SAFETY.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1755)
=> rpma: add main assumptions of the analysis of thread safety

THREAD_SAFETY.md, src/include/librpma.h
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1758)
=> rpma: move description of thread safety to THREAD_SAFETY.md

THREAD_SAFETY.md, src/peer_cfg.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1756)
=> rpma: analysis of thread safety (peer + peer_cfg)

THREAD_SAFETY.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1757)
=> rpma: analysis of thread safety: rpma_conn_cfg_

THREAD_SAFETY.md
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1759)
=> rpma: analysis of thread safety: rpma_conn_req_

THREAD_SAFETY.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1763)
=> rpma: analysis of thread safety: rpma_mr_

THREAD_SAFETY.md
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1761)
=> rpma: analysis of thread safety: rpma_ep_

THREAD_SAFETY.md
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1760)
=> rpma: analysis of thread safety: rpma_conn_

THREAD_SAFETY.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1764)
=> rpma: analysis of thread safety: rpma_cq_

THREAD_SAFETY.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1765)
=> rpma: analysis of thread safety: rpma.c

THREAD_SAFETY.md, src/rpma_err.c
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1770)
=> rpma: analysis of thread safety: rpma_err_2str

THREAD_SAFETY.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1772)
=> rpma: analysis of thread safety: rpma_log_

utils/docker/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1777)
=> common: run doc update should be run only on the master branch

src/include/librpma.h
Test run-doc-update (DO NOT MERGE TO MASTER).
It will be reverted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1778)
=> test: test run-doc-update DO NOT MERGE TO MASTER

src/include/librpma.h
This reverts commit 17b842a895b6062cd9d6b4b400df037628819703.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1779)
=> test: revert "test: test run-doc-update DO NOT MERGE TO MASTER"

utils/docker/images/Dockerfile.ubuntu-rolling
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1781)
=> common: install pylint on Ubuntu-rolling

utils/docker/prepare-for-build.sh
Add a comment to prepare-for-build.sh missed in 69ac575.
Ref: 69ac575
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1783)
=> common: add comment to prepare-for-build.sh

examples/03-read-to-persistent/client.c, examples/common/common-pmem2_map_file.c, examples/common/common-pmem_map_file.c, examples/common/common-pmem_map_file.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1744)
=> examples: fix example03's client

examples/03-read-to-persistent/CMakeLists.txt, examples/03-read-to-persistent/client.c, examples/03-read-to-persistent/server.c, examples/common/common-pmem2_map_file.c, examples/common/common-pmem_map_file.c, examples/common/common-pmem_map_file.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1746)
=> examples: add libpmem2 to example03's server

utils/docker/prepare-for-build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1786)
=> common: set WORKDIR as a safe directory

THREAD_SAFETY.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1785)
=> rpma: the main assumptions must be met

.github/workflows/nightly.yml, .github/workflows/on_pull_request.yml, utils/docker/images/Dockerfile.ubuntu-22.04
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1787)
=> common: add Ubuntu 22.04 to CI and remove EOLed 21.04

THREAD_SAFETY.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1788)
=> rpma: relationship of libibverbs and librdmacm

THREAD_SAFETY.md, src/include/librpma.h, src/peer_cfg.c, src/rpma_err.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1799)
=> rpma: add thread safety analysis of the librpma library

reports/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1789)
=> doc: add performance reports for Ice Lake

THREAD_SAFETY.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1802)
=> rpma: change order of NOT thread-safe API calls

CMakeLists.txt, cmake/functions.cmake, tests/cmake/helpers.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1804)
=> common: check if valgrind supports -s option

tests/multithreaded/common/mtt.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1768)
=> test: enable user error messages with actual values

.circleci/config.yml, tests/drd.supp, tests/helgrind.supp, tests/memcheck-libibverbs.supp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1800)
=> test: Upgrade Circle CI to Ubuntu 22.04

src/CMakeLists.txt, src/utils.c, tests/integration/example-01-connection/CMakeLists.txt, tests/integration/example-02-read-to-volatile/CMakeLists.txt, tests/integration/example-04-write-to-persistent/CMakeLists.txt, tests/unit/common/mocks-rpma-utils.c, tests/unit/utils/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1803)
=> rpma: rename rpma.c to utils.c as it is a utils functions src file.

tests/helgrind.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1810)
=> test: add one suppression for rpma_conn_req_delete()

tests/multithreaded/peer/rpma_peer_cfg_new.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1767)
=> test: adapt rpma_perr_cfg_new mtt to the new test template

THREAD_SAFETY.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1813)
=> rpma: update THREAD_SAFETY.md to the master branch version

CMakeLists.txt, examples/README.md, examples/run-all-examples.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1815)
=> common: rename run-all-on-SoftRoCE.sh to run-all-examples.sh

DEVELOPMENT.md, INSTALL.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1808)
=> rpma: scaffolding of the DEVELOPMENT.md file

CMakeLists.txt, examples/run-all-examples.sh
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1816)
=> examples: run all examples with fault injection

examples/run-all-examples.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1820)
=> examples: add support for PMem to run-all-examples.sh

.circleci/install-pkgs-ubuntu.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1826)
=> common: import missing GPG keys of CircleCI Ubuntu

examples/run-all-examples.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1823)
=> examples: always set S_FI_VAL and C_FI_VAL

DEVELOPMENT.md, examples/run-all-examples.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1822)
=> examples: run integration tests on SoftRoCE or RDMA HW

CONTRIBUTING.md, DEVELOPMENT.md, INSTALL.md, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1825)
=> common: documentation of building, installing and testing

tests/drd.supp, tests/helgrind.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1835)
=> test: add missing suppressions for drd and helgrind

tests/drd.supp, tests/helgrind.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1832)
=> test: update description to newly added suppressions

tests/drd.supp, tests/helgrind.supp
See: https://app.circleci.com/pipelines/github/ldorau/rpma/4252/workflows/f50c40ac-b135-43b2-a281-8cabc79fc05c/jobs/4335
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1837)
=> test: add new suppressions for drd and helgrind

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1840)
=> rpma: fix a link in the README.md file

DEVELOPMENT.md, examples/run-all-examples.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1841)
=> rpma: fix description of usage of PMem in the integration tests

DEVELOPMENT.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1845)
=> doc: remove non-existing option TEST_LONG

examples/run-all-examples.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1848)
=> examples: fix checking IP address

examples/run-all-examples.sh
Fix checking the `<binary-examples-directory>` CLI argument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1851)
=> examples: fix checking a CLI argument

tests/drd.supp, tests/helgrind.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1850)
=> test: suppression format definition

tests/drd.supp, tests/helgrind.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1855)
=> test: update suppressions of syslog

examples/run-all-examples.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1856)
=> examples: fix verifying a path of PMem given in RPMA_EXAMPLES_PMEM_PATH

src/log_default.c, tests/drd.supp, tests/helgrind.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1857)
=> rpma: rename get_timestamp_prefix to rpma_get_timestamp_prefix

tests/drd.supp, tests/helgrind.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1860)
=> test: update suppression of ucma_init()

tests/drd.supp, tests/helgrind.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1858)
=> test: update suppressions of rpma_get_timestamp_prefix

tests/multithreaded/conn_cfg/rpma_conn_cfg_set_cq_size.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1863)
=> test: fix expected value of cq_size

tests/CMakeLists.txt, tests/multithreaded/run_group.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1870)
=> test: RPMA_TESTING_IP cannot be set to 127.0.0.1

tests/cmake/ctest_helpers.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1868)
=> test: add a notice when TESTS_USE_VALGRIND is OFF

DEVELOPMENT.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1871)
=> rpma: improve DEVELOPMENT.md file

DEVELOPMENT.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1874)
=> rpma: clean up and improve DEVELOPMENT.md file

.circleci/config.yml, CHANGELOG.md, CMakeLists.txt, DEVELOPMENT.md, tests/cmake/ctest_helpers.cmake
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1880)
=> common: remove the TESTS_USE_VALGRIND option

tests/drd.supp, tests/helgrind.supp, tests/multithreaded/conn_cfg/CMakeLists.txt, tests/multithreaded/conn_cfg/rpma_conn_cfg_set_rq_size.c, tests/multithreaded/conn_cfg/rpma_conn_cfg_set_sq_size.c, tests/multithreaded/conn_cfg/rpma_conn_cfg_set_timeout.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1861)
=> rpma: rpma_conn_cfg_set_... test modification and add suppresions

examples/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1885)
=> examples: fix building examples with libpmem

CMakeLists.txt, DEVELOPMENT.md, examples/run-all-examples.sh
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1881)
=> common: replace the --fault-injection option with --integration-tests

CMakeLists.txt, DEVELOPMENT.md, examples/run-all-examples.sh, tests/CMakeLists.txt
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1876)
=> common: MTT and integration tests require valgrind and RDMA connection

tests/multithreaded/ep/CMakeLists.txt, tests/multithreaded/ep/rpma_ep_shutdown.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1872)
=> test: add rpma_ep_shutdown mt test

tests/multithreaded/mr/CMakeLists.txt, tests/multithreaded/mr/rpma_mr_dereg.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1873)
=> test: add rpma_mr_dereg mt test

.circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1883)
=> tools: configure SoftRoCE before build commands on CircleCi

tests/drd.supp, tests/helgrind.supp
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1862)
=> test: update suppressions of libibverbs and librdmacm

DEVELOPMENT.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1893)
=> doc: fix info about IP of RDMA-capable network interface

examples/run-all-examples.sh
Fix setting IP address of an RDMA-capable network interface
and remove calling the config_softroce.sh script (not needed).
`RPMA_TESTING_IP` is used when `IP_ADDRESS` is not given.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1895)
=> examples: fix setting IP address of an RDMA-capable network interface

tests/drd.supp, tests/helgrind.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1896)
=> test: fix names of two suppressions

CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1888)
=> rpma: set default value of CMAKE_BUILD_TYPE to Release

examples/03-read-to-persistent/CMakeLists.txt, examples/04-write-to-persistent/CMakeLists.txt, examples/04-write-to-persistent/client.c, examples/04-write-to-persistent/server.c, examples/CMakeLists.txt, examples/cmake/common.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1853)
=> examples: add common-pmem_map_file and signature_check to example04

examples/05-flush-to-persistent/CMakeLists.txt, examples/05-flush-to-persistent/client.c, examples/05-flush-to-persistent/server.c, examples/CMakeLists.txt, examples/cmake/common.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1854)
=> examples: add common-pmem_map_file and signature_check to example05

CONTRIBUTING.md, INSTALL.md, tools/perf/BENCHMARKING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1911)
=> doc: unify shell command folder

.circleci/install-pkgs-ubuntu.sh, tests/drd.supp
For details see:
https://app.circleci.com/pipelines/github/pmem/rpma/1860/workflows/c18ca9dd-26ab-4caa-a1b1-e95c9b4f8cba/jobs/1881
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1912)
=> common: remove -dbgsym pkgs from CircleCI environment

CHANGELOG.md, tests/multithreaded/peer/CMakeLists.txt, tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1915)
=> test: add rpma_peer_cfg_set_direct_write_to_pmem MT test

tests/drd.supp, tests/helgrind.supp, tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1919)
=> test: improve rpma_peer_cfg_set... MT test

CHANGELOG.md, src/peer_cfg.c, tests/drd.supp, tests/helgrind.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1917)
=> rpma: make peer_cfg thread-safe

utils/docker/images/Dockerfile.ubuntu-22.04
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1916)
=> common: organize Dockerfile.Ubuntu-22.04

examples/common/common-hello.c, examples/common/hello.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1906)
=> rpma: remove unused RPMA_INTEGRATION_TEST

tests/unit/common/mocks-rpma-conn_cfg.c, tests/unit/common/mocks-rpma-conn_cfg.h, tests/unit/conn_req/conn_req-common.c, tests/unit/conn_req/conn_req-common.h, tests/unit/conn_req/conn_req-connect.c, tests/unit/conn_req/conn_req-delete.c, tests/unit/conn_req/conn_req-from_cm_event.c, tests/unit/conn_req/conn_req-new.c, tests/unit/conn_req/conn_req-private_data.c, tests/unit/peer/peer-create_qp.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1925)
=> test: do some cleanup for unit tests

DEVELOPMENT.md, INSTALL.md, tools/perf/BENCHMARKING.md
https://github.com/Patryk717/rpma/blob/add_Docker/DEVELOPMENT.md
https://github.com/Patryk717/rpma/blob/add_Docker/INSTALL.md
https://github.com/Patryk717/rpma/blob/add_Docker/tools/perf/BENCHMARKING.md
-[ ] #1916
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1921)
=> doc: add Dockerfiles references to documentations

examples/09-flush-to-persistent-GPSPM/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1926)
=> examples: remove redundant src from Cmakelist example09

tests/multithreaded/common/mtt.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1929)
=> test: check if result is NULL in MTT_RPMA_ERR()

utils/docker/images/Dockerfile.centos-7, utils/docker/images/Dockerfile.centos-stream, utils/docker/images/Dockerfile.debian-10, utils/docker/images/Dockerfile.debian-11, utils/docker/images/Dockerfile.debian-experimental, utils/docker/images/Dockerfile.debian-stable, utils/docker/images/Dockerfile.debian-testing, utils/docker/images/Dockerfile.fedora-32, utils/docker/images/Dockerfile.fedora-33, utils/docker/images/Dockerfile.fedora-34, utils/docker/images/Dockerfile.fedora-rawhide, utils/docker/images/Dockerfile.opensuse-leap-latest, utils/docker/images/Dockerfile.opensuse-tumbleweed-latest, utils/docker/images/Dockerfile.rockylinux-8.4, utils/docker/images/Dockerfile.ubuntu-20.04, utils/docker/images/Dockerfile.ubuntu-21.10, utils/docker/images/Dockerfile.ubuntu-rolling, utils/docker/images/Dockerfile.vzlinux-latest
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1927)
=> common: organize Dockerfile

CHANGELOG.md, tests/multithreaded/ep/CMakeLists.txt, tests/multithreaded/ep/client_rpma_ep_next_conn_req.c, tests/multithreaded/ep/rpma_ep_next_conn_req.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1928)
=> test: add MT test for rpma_ep_next_conn_req()

CHANGELOG.md, tests/multithreaded/common/mtt_client_process.c, tests/multithreaded/conn/CMakeLists.txt, tests/multithreaded/conn/rpma_conn_req_connect.c, tests/multithreaded/ep/CMakeLists.txt
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1931)
=> test: add MT test for rpma_conn_req_connect()

tests/multithreaded/common/mtt_connect.c
It will help to debug the issues like:
https://app.circleci.com/pipelines/github/ldorau/rpma/4643/workflows/fe01ffbd-0fb6-40b2-985f-448d6bb6268b/jobs/4735
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1939)
=> test: fix error messages in mtt_client_connect()

CMakeLists.txt, cmake/functions.cmake, examples/03-read-to-persistent/CMakeLists.txt, examples/03-read-to-persistent/server.c, examples/04-write-to-persistent/CMakeLists.txt, examples/04-write-to-persistent/server.c, examples/05-flush-to-persistent/CMakeLists.txt, examples/05-flush-to-persistent/server.c, examples/07-atomic-write/CMakeLists.txt, examples/07-atomic-write/server.c, examples/09-flush-to-persistent-GPSPM/CMakeLists.txt, examples/09-flush-to-persistent-GPSPM/server.c, examples/09s-flush-to-persistent-GPSPM/CMakeLists.txt, examples/09s-flush-to-persistent-GPSPM/server.c, examples/CMakeLists.txt, examples/cmake/common.cmake, src/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1905)
=> common: disable rpma_mr_advise() if IBV_ADVISE_MR flags are not supported

utils/docker/images/Dockerfile.fedora-rawhide
This reverts commit 53d48621d0dc34c2024edd0b5398a79182346a21.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1945)
=> Revert "common: temporarily downgrade python3-wrapt in Fedora Rawhide"

tests/unit/conn_cfg/CMakeLists.txt, tests/unit/conn_req/CMakeLists.txt, tests/unit/cq/CMakeLists.txt, tests/unit/ep/CMakeLists.txt, tests/unit/flush/CMakeLists.txt, tests/unit/info/CMakeLists.txt, tests/unit/peer/CMakeLists.txt, tests/unit/private_data/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1943)
=> test: fix wrong indentation and order of some unit tests

src/log.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1947)
=> rpma: fix a comment of Rpma_log_function

CMakeLists.txt, cmake/functions.cmake, src/conn_cfg.c, src/peer_cfg.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1950)
=> rpma: fix checking if atomic operations are supported

tests/memcheck-libibverbs-librdmacm.supp
See: https://app.circleci.com/pipelines/github/haichangsi/rpma/236/workflows/9db454df-3620-4a3c-8d19-f587896c3320/jobs/237
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1952)
=> test: add a suppression for a memory leak in pthread_create()

src/conn_cfg.c, src/peer_cfg.c
Before: https://github.com/ldorau/rpma/runs/7518863918?check_suite_focus=true
After: https://github.com/ldorau/rpma/actions/runs/2739074360
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1953)
=> rpma: fix atomic operations for Debian 10 with clang

THREAD_SAFETY.md
Preview https://github.com/pmem/rpma/pull/1923/files?short_path=ea207e6#diff-ea207e67fe0d4bb1af009552a536828a143e75e0689c11647debe197efae06f0
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1923)
=> doc: document rpma_log_default_func()

tools/perf/multiply_connection_benchmark.md
See the file in a final shape here: https://github.com/Patryk717/rpma/blob/Multi-fio/tools/perf/multiply_connection_benchmark.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1879)
=> tools: add file multiply_connection_benchmark.md

CHANGELOG.md, tests/multithreaded/log/CMakeLists.txt, tests/multithreaded/log/rpma_log_set_get_threshold.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1954)
=> test: add a rpma_log_set_get_threshold MT test

src/log.c, src/log_internal.h, tests/unit/common/mocks-rpma-log.c, tests/unit/common/mocks-rpma-log_default.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1956)
=> rpma: make rpma_log_set_function() thread-safe

examples/07-atomic-write/CMakeLists.txt, examples/07-atomic-write/server.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1957)
=> examples: add common-pmem_map_file to example07

examples/09-flush-to-persistent-GPSPM/server.c, examples/09s-flush-to-persistent-GPSPM/server.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1959)
=> examples: use USE_PMEM instead of USE_LIBPMEM in examples 09 and 09s

CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1961)
=> rpma: improve CONTRIBUTING.md file

CHANGELOG.md, src/log_internal.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1968)
=> rpma: use librpma without any article

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1966)
=> rpma: improve README.md file

INSTALL.md, tools/perf/BENCHMARKING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1970)
=> rpma: improve INSTALL.md file

examples/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1971)
=> rpma: improve examples/README.md file

src/conn.c, src/include/librpma.h, src/mr.c, src/mr.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1964)
=> rpma: remove redundant whitespace

utils/docker/images/Dockerfile.centos-7, utils/docker/images/Dockerfile.centos-stream, utils/docker/images/Dockerfile.debian-10, utils/docker/images/Dockerfile.debian-11, utils/docker/images/Dockerfile.debian-experimental, utils/docker/images/Dockerfile.debian-stable, utils/docker/images/Dockerfile.debian-testing, utils/docker/images/Dockerfile.fedora-32, utils/docker/images/Dockerfile.fedora-33, utils/docker/images/Dockerfile.fedora-34, utils/docker/images/Dockerfile.fedora-rawhide, utils/docker/images/Dockerfile.opensuse-leap-latest, utils/docker/images/Dockerfile.opensuse-tumbleweed-latest, utils/docker/images/Dockerfile.rockylinux-8.4, utils/docker/images/Dockerfile.ubuntu-20.04, utils/docker/images/Dockerfile.ubuntu-22.04, utils/docker/images/Dockerfile.ubuntu-rolling, utils/docker/images/Dockerfile.vzlinux-latest
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1965)
=> common: add missing packages to Dockerfiles

examples/08-messages-ping-pong/CMakeLists.txt, examples/08-messages-ping-pong/client.c, examples/12-receive-completion-queue/CMakeLists.txt, examples/12-receive-completion-queue/client.c, examples/12s-receive-completion-queue/CMakeLists.txt, examples/12s-receive-completion-queue/client.c, examples/13-messages-ping-pong-with-srq/CMakeLists.txt, examples/13-messages-ping-pong-with-srq/client.c, examples/CMakeLists.txt, examples/common/common-utils.c, examples/common/common-utils.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1977)
=> examples: move strtoul_noerror() to common-utils

examples/13-messages-ping-pong-with-srq/server.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1978)
=> examples: validate a value of timeout in example 13

CHANGELOG.md, examples/08srq-simple-messages-ping-pong-with-srq/CMakeLists.txt, examples/08srq-simple-messages-ping-pong-with-srq/README.md, examples/08srq-simple-messages-ping-pong-with-srq/client.c, examples/08srq-simple-messages-ping-pong-with-srq/server.c, examples/CMakeLists.txt, examples/common/common-messages-ping-pong.c, examples/common/common-messages-ping-pong.h, examples/run-all-examples.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1981)
=> examples: add 08srq-simple-messages-ping-pong-with-srq example

examples/01-connection/client.c, examples/01-connection/server.c, examples/02-read-to-volatile/client.c, examples/02-read-to-volatile/server.c, examples/06-multiple-connections/client.c, examples/06-multiple-connections/server.c, examples/06scch-multiple-connections/client.c, examples/06scch-multiple-connections/server.c, examples/07-atomic-write/client.c, examples/07-atomic-write/server.c, examples/08-messages-ping-pong/client.c, examples/08-messages-ping-pong/server.c, examples/09-flush-to-persistent-GPSPM/client.c, examples/09-flush-to-persistent-GPSPM/server.c, examples/09scch-flush-to-persistent-GPSPM/client.c, examples/09scch-flush-to-persistent-GPSPM/server.c, examples/10-send-with-imm/client.c, examples/10-send-with-imm/server.c, examples/11-write-with-imm/client.c, examples/11-write-with-imm/server.c, examples/12-receive-completion-queue/client.c, examples/12-receive-completion-queue/server.c, examples/12scch-receive-completion-queue/client.c, examples/12scch-receive-completion-queue/server.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1984)
=> examples: make all examples comply the new chars line limit

CHANGELOG.md, THREAD_SAFETY.md, tests/multithreaded/conn_cfg/CMakeLists.txt, tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c, tests/multithreaded/conn_cfg/rpma_conn_cfg_common.h, tests/multithreaded/conn_cfg/rpma_conn_cfg_get_srq.c, tests/multithreaded/conn_cfg/rpma_conn_cfg_set_srq.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1955)
=> test: add rpma_conn_cfg_get/set_srq MT tests

CHANGELOG.md, src/conn.c, src/conn.h, src/conn_cfg.c, src/conn_req.c, src/conn_req.h, src/ep.c, src/flush.c, src/mr.c, src/mr.h, src/peer.c, src/peer.h, src/private_data.c, src/private_data.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1987)
=> examples: make the internal API comply the new chars line limit

DEVELOPMENT.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1989)
=> common: fix a command in the DEVELOPMENT.md file

utils/docker/images/set-images-version.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1991)
=> common: set version of docker images to 'devel' for the devel branch

src/cq.c, src/cq.h, src/debug.c, src/ep.c, src/info.c, src/info.h, src/log_default.c, src/log_default.h, src/peer.c, src/peer.h, src/private_data.h, src/utils.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1994)
=> rpma: make other internal API files comply with the new chars line limit

CHANGELOG.md, src/include/librpma.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1993)
=> rpma: make the librpma.h comply the new chars line limit

examples/run-all-examples.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1999)
=> examples: fix running example 08srq

tests/cmocka_headers.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2001)
=> test: remove unused functions from cmocka_headers.h

utils/docker/prepare-for-build.sh
Ref: #1875
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2007)
=> common: make sure WORKDIR has correct permissions

tools/perf/BENCHMARKING.md, tools/perf/lib/report/base.py
https://github.com/pmem/rpma/issues/1526
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2008)
=> tools: describe the schematic variable in the report.json file

src/mr.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2011)
=> rpma: standardize the if condition in the mr.c file

examples/01-connection/client.c, examples/01-connection/server.c, examples/06-multiple-connections/server.c, examples/06scch-multiple-connections/server.c, examples/08-messages-ping-pong/server.c, examples/09-flush-to-persistent-GPSPM/server.c, examples/09scch-flush-to-persistent-GPSPM/server.c, examples/10-send-with-imm/server.c, examples/11-write-with-imm/server.c, examples/common/common-conn.c
#1747
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2010)
=> examples: remove unnecessary rpma_conn_req_delete()

CHANGELOG.md, examples/04-write-to-persistent/client.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2017)
=> examples: change read-after-write (RAW) buffer size

CHANGELOG.md, examples/04-write-to-persistent/client.c, examples/04-write-to-persistent/server.c, examples/05-flush-to-persistent/client.c, examples/05-flush-to-persistent/server.c, examples/09-flush-to-persistent-GPSPM/client.c, examples/09-flush-to-persistent-GPSPM/server.c, examples/09scch-flush-to-persistent-GPSPM/client.c, examples/09scch-flush-to-persistent-GPSPM/server.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2016)
=> examples: change the write size from KILOBYTE to HELLO_STR_SIZE

CHANGELOG.md, examples/07-atomic-write/client.c, examples/07-atomic-write/server.c, examples/08-messages-ping-pong/client.c, examples/08-messages-ping-pong/server.c, examples/08srq-simple-messages-ping-pong-with-srq/client.c, examples/08srq-simple-messages-ping-pong-with-srq/server.c, examples/09-flush-to-persistent-GPSPM/client.c, examples/09-flush-to-persistent-GPSPM/server.c, examples/09scch-flush-to-persistent-GPSPM/client.c, examples/09scch-flush-to-persistent-GPSPM/server.c, examples/10-send-with-imm/server.c, examples/11-write-with-imm/server.c, examples/12-receive-completion-queue/client.c, examples/12-receive-completion-queue/receive-completion-queue-common.c, examples/12-receive-completion-queue/server.c, examples/12scch-receive-completion-queue/client.c, examples/12scch-receive-completion-queue/server.c, examples/13-messages-ping-pong-with-srq/client.c, examples/13-messages-ping-pong-with-srq/server.c, examples/common/common-conn.c, examples/common/common-messages-ping-pong.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2015)
=> examples: standardize the code style in example files

tests/multithreaded/common/mtt.c, tests/multithreaded/peer/rpma_peer_cfg_new.c, tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2018)
=> test: standardize the code style in test files

src/librpma.map
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2025)
=> rpma: fix ABI version from 1.1 to 1.0

CHANGELOG.md, tests/memcheck-libibverbs-librdmacm.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2037)
=> test: add one suppression for Memcheck on Ubuntu 22.04

CHANGELOG.md, tools/perf/multiply_connection_benchmark.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2038)
=> common: fix some spelling errors

CHANGELOG.md, examples/03-read-to-persistent/server.c, examples/05-flush-to-persistent/client.c, examples/09-flush-to-persistent-GPSPM/client.c, examples/09-flush-to-persistent-GPSPM/server.c, examples/09scch-flush-to-persistent-GPSPM/client.c, examples/09scch-flush-to-persistent-GPSPM/server.c
This continuation of commit 06520917cefc1fc18874b6eb60bf8b25fa29e6dc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2045)
=> examples: use HELLO_STR_SIZE instead of KILOBYTE

examples/07-atomic-write/client.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2047)
=> examples: clarify setting and using mr_size in example 07

src/include/librpma.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2050)
=> rpma: fix one spelling mistake

CHANGELOG.md, examples/03-read-to-persistent/client.c, examples/03-read-to-persistent/server.c, examples/04-write-to-persistent/client.c, examples/04-write-to-persistent/server.c, examples/05-flush-to-persistent/client.c, examples/05-flush-to-persistent/server.c, examples/09-flush-to-persistent-GPSPM/client.c, examples/09-flush-to-persistent-GPSPM/server.c, examples/09scch-flush-to-persistent-GPSPM/client.c, examples/09scch-flush-to-persistent-GPSPM/server.c, examples/common/common-hello.c, examples/common/common-hello.h, examples/common/common-map_file_with_signature_check.c, examples/common/common-map_file_with_signature_check.h
Depends on:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2049)
=> examples: use HELLO_T_SIZE instead of sizeof(struct hello_t)

examples/03-read-to-persistent/client.c, examples/04-write-to-persistent/client.c, examples/05-flush-to-persistent/client.c, examples/09-flush-to-persistent-GPSPM/client.c, examples/09scch-flush-to-persistent-GPSPM/client.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2053)
=> examples: replace (offsetof(struct hello_t, str)) with HELLO_STR_OFFSET

examples/common/common-pmem2_map_file.c, examples/common/common-pmem_map_file.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2054)
=> examples: print size of PMem if it is too small

src/mr.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2057)
=> rpma: initialize to 0 wr passed to ibv_post_send()

CHANGELOG.md, src/mr.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2059)
=> rpma: initialize to 0 wr passed to ibv_post_(srq_)recv()

CHANGELOG.md, src/mr.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2058)
=> rpma: initialize to 0 sge passed to a log message

CHANGELOG.md, src/peer.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2060)
=> rpma: initialize rq_size with RPMA_DEFAULT_SRQ_SIZE

examples/06scch-multiple-connections/server.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2063)
=> examples: initialize values passed to functions in example 06scch

.github/workflows/coverity.yml, README.md, utils/docker/build.sh, utils/docker/coverity-command.sh, utils/docker/images/Dockerfile.ubuntu-22.04, utils/docker/pull-or-rebuild-image.sh, utils/docker/run-coverity.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2064)
=> common: add Coverity build to GitHub Actions

CHANGELOG.md, CONTRIBUTING.md, README.md, examples/run-all-examples.sh, src/include/librpma.h, tests/cmake/helpers.cmake, utils/check_license/check-headers.sh, utils/docker/build.sh, utils/docker/images/download-scripts.sh, utils/docker/images/set-images-version.sh, utils/docker/pull-or-rebuild-image.sh, utils/docker/run-doc-update.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2068)
=> common: the 'master' branch has been renamed to 'main'

utils/docker/pull-or-rebuild-image.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2065)
=> common: print out why pushing the image has been skipped

utils/docker/images/Dockerfile.ubuntu-22.04
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2067)
=> common: force rebuild of Ubuntu 22.04 docker image

.github/workflows/on_pull_request.yml, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2070)
=> common: change name printed on the badge of GHA build

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2071)
=> common: swap two badges with each other

examples/06-multiple-connections/server.c, tests/multithreaded/conn/server_rpma_conn_common.c
This is a continuation of commit 5bf10bde321f4a5961ae4b67af3e5f552de8e200
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2072)
=> common: initialize values passed to functions

utils/docker/run-coverity.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2074)
=> common: make possible running the Coverity build on forked repos

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2076)
=> common: add info about the Coverity build to CHANGELOG.md

tests/unit/srq_cfg/srq_cfg-new.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2078)
=> test: check return value of rpma_srq_cfg_get_rq_size()

CHANGELOG.md, examples/06-multiple-connections/server.c, examples/06scch-multiple-connections/server.c, src/conn_req.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2077)
=> examples: do not overwrite the previous return value

tests/unit/peer/peer-common.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2079)
=> test: use real ibv_transport_type in the prestate

tests/unit/utils/utils-conn_event_2str.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2080)
=> test: use RPMA_CONN_UNSUPPORTED instead of RPMA_E_UNKNOWN

CHANGELOG.md, examples/07-atomic-write/server.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2081)
=> examples: fix memory allocations in example 07

README.md, utils/docker/run-coverity.sh
We have regained access to the original "pmem/rpma" Coverity project, so let's switch to it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2082)
=> common: switch to the original pmem/rpma Coverity project

src/mr.c, src/peer_cfg.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2086)
=> rpma: fix two messages about a new structure

utils/docker/run-doc-update.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2092)
=> common: add a file brief to run-doc-update.sh

utils/mans_header.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2094)
=> common: update copyright date in utils/mans_header.md

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2097)
=> common: CHANGELOG.md: update info about the native atomic write support

CHANGELOG.md, CMakeLists.txt, utils/mans_header.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2083)
=> common: 1.1.1-rc1 release

CHANGELOG.md, CMakeLists.txt, utils/mans_header.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2100)
=> common: 1.2.0-rc1 release

.gitignore
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2105)
=> common: don't ignore .circleci directory in .gitignore

tests/unit/peer/peer-mr_reg.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2107)
=> test: fix some wrong and misleading comments

tests/unit/mr/mr-atomic_write.c
Current unit tests cannot cover the following lines in rpma_mr_atomic_write():
https://app.codecov.io/gh/pmem/rpma/pull/2108/blob/src/mr.c#L248 https://app.codecov.io/gh/pmem/rpma/pull/2108/blob/src/mr.c#L252
Add missing unit tests by restructuring mr-atomic_write.c.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2110)
=> test: add missing unit tests for rpma_mr_atomic_write()

utils/docker/images/install-pmdk.sh
Verify if PMDK was successfully installed - fail the build if not.
Ref: https://github.com/pmem/pmdk/issues/5540
Requires:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2109)
=> common: verify if PMDK was successfully installed

.github/workflows/coverity.yml, utils/docker/images/build-image.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2114)
=> common: fix Coverity CI build

utils/docker/run-build.sh
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2120)
=> common: replace echos with set -x when installing packages

tests/unit/utils/CMakeLists.txt, tests/unit/utils/utils-ibv_context_is_odp_capable.c
Run as many cases as possible even if ON_DEMAND_PAGING_SUPPORTED is not defined.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2128)
=> test: enhance rpma_utils_ibv_context_is_odp_capable() unit test

DEVELOPMENT.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2129)
=> common: add CPACK_GENERATOR to DEVELOPMENT.md
